### ISSUE TITLE
PyTorch and huggingface compatibility on A100 GPU

### ISSUE THREAD

**Issue by ddomingof** [microsoft/DeepSpeed#1109]
Hi, I am currently facing issues to train a transformer model using huggingface and PyTorch together with DeepSpeed on the new A100s. Is there any configuration of CUDA drivers + specific versions of PyTorch and DeepSpeed that would not either raise issues with the CUDA or with the two/three libraries.

```
packages/torch/cuda/__init__.py:104: UserWarning: A100-SXM4-40GB with CUDA capability sm_80 is not compatible with the current PyTorch installation. The current PyTorch install supports CUDA capabilities sm_37 sm_50 sm_60 sm_61 sm_70 sm_75 compute_37. If you want to use the A100-SXM4-40GB GPU with PyTorch, please check the instructions at https://pytorch.org/get-started/locally/
warnings.warn(incompatible_device_warn.format(device_name, capability, " ".join(arch_list), device_name))`
```
```
--------------------------------------------------
DeepSpeed C++/CUDA extension op report
--------------------------------------------------
NOTE: Ops not installed will be just-in-time (JIT) compiled at
runtime if needed. Op compatibility means that your system
meet the required dependencies to JIT install the op.
--------------------------------------------------
JIT compiled ops requires ninja
ninja .................. [OKAY]
--------------------------------------------------
op name ................ installed .. compatible
--------------------------------------------------
cpu_adam ............... [NO] ....... [OKAY]
fused_adam ............. [NO] ....... [OKAY]
fused_lamb ............. [NO] ....... [OKAY]
/bin/sh: line 0: type: llvm-config: not found
/bin/sh: line 0: type: llvm-config-9: not found
[WARNING] sparse_attn requires one of the following commands '['llvm-config', 'llvm-config-9']', but it does not exist!
/bin/sh: line 0: type: cmake: not found
[WARNING] sparse_attn requires the 'cmake' command, but it does not exist!
[WARNING] sparse_attn requires CUDA version 10.1+, does not currently support >=11 or <10.1
sparse_attn ............ [NO] ....... [NO]
transformer ............ [NO] ....... [OKAY]
stochastic_transformer . [NO] ....... [OKAY]
[WARNING] async_io requires the libraries: ['libaio-dev'] but are missing. Can be fixed by: `apt install libaio-dev`.
async_io ............... [NO] ....... [NO]
transformer_inference .. [NO] ....... [OKAY]
utils .................. [NO] ....... [OKAY]
quantizer .............. [NO] ....... [OKAY]
--------------------------------------------------
DeepSpeed general environment info:
torch install path ............... ['/./lib/python3.8/site-packages/torch']
torch version .................... 1.8.1+cu111
torch cuda version ............... 11.1
nvcc version ..................... 11.1
deepspeed install path ........... ['./software/DeepSpeed/deepspeed']
deepspeed info ................... 0.4.0+d2cf66a, d2cf66a, master
deepspeed wheel compiled w. ...... torch 1.8, cuda 10.2

```

**Comment by Santosh-Gupta** [comment]
I seem to be having issued with a 4 gpu a100 rig. Specifically I am getting this error

> arguments are located on different GPUs

**Comment by ludgerpaehler** [comment]
Have you found a solution by now?

I am running into the same issue and am at the point where I am thinking of a deepspeed fork to get it to compile with CUDA 11.1

**Comment by ddomingof** [comment]
No sorry...we dropped usnig DeepSpeed and that's all...

**Comment by jeffra** [comment]
@ddomingof so sorry you’re having these issues :( a few questions 

* When do you see the incompatible_device warning?

* did you upgrade torch after installing deepspeed? ds-report is saying it was installed with a torch version with cuda 10.2 (which is not compatible with a100).

**Comment by Santosh-Gupta** [comment]
I've been running it, so far I don't think I've seen any major issues. 

What is the issue you've been running into? I see a warning. Did that prevent you from running it?

a100s are tricky in general. I am using 11.2 on the gpu and the system. I am using the pytorch docker with deepspeed pip installed.

**Comment by ddomingof** [comment]
Can you share the exact versions of pytorch and deepspeed? Unfortunately I can't install pytorch with Docker

**Comment by ddomingof** [comment]
With CUDA10:
```
[distributed.py:36:init_distributed] Not using the DeepSpeed or torch.distributed launchers, attempting to detect MPI environment...
Illegal instruction (core dumped)
```
 With CUDA11 also illegal instruction error

Installing pytorch with conda via `conda install pytorch torchvision torchaudio cudatoolkit=10.2 -c pytorch`:
```
A100-SXM4-40GB with CUDA capability sm_80 is not compatible with the current PyTorch installation.
	The current PyTorch install supports CUDA capabilities sm_37 sm_50 sm_60 sm_61 sm_70 sm_75 compute_37.
	If you want to use the A100-SXM4-40GB GPU with PyTorch, please check the instructions at https://pytorch.org/get-started/locally/

```

**Comment by jeffra** [comment]
I see, one issue is that A100 requires at least cuda 11.0.

Can you try cuda 11.1, torch 1.8.1, and deepspeed 0.4? This should work.

Also how many gpus are you wanting to run with? can you share how you’re launching your model? The init_distributed error above is telling me maybe you’re not launching with torch.distributed or deepspeed launchers maybe?

**Comment by helena-balabin** [comment]
Thanks for the suggestion @jeffra! 

@ddomingof and I made sure to use the suggested versions, which helped in getting rid of the incompatibility issues. We're using our script in a single-node multi-GPU setting with 4x A100s. Yes, the `init_distributed` error appears when we're launching our script without the deepspeed launcher (`python3 stonkgs_finetuning.py`, in which we implicitly rely on the deepspeed argument in huggingface transformers' `TrainingArguments`). If we're launching with the deepspeed launcher (`deepspeed stonkgs_finetuning.py`) we run into following issue: 

`ImportError: No module named 'fused_adam'`

I tried installing the named extension (all extensions) using `DS_BUILD_OPS=1 pip install deepspeed`, however, `ds_report` reports that the extensions are still not installed afterwards, even though they are indicated as compatible. I'll try to take another look at it later on, I'll post an update if I'm able to find a solution.

**Comment by Santosh-Gupta** [comment]
Which optimizer are you using? Are you using AMP?

**Comment by jeffra** [comment]
@helena-balabin that sounds promising! Can you post your ds_report results? Also there might be a ninja issue. Can you try ‘apt-get install ninja-build’?

**Comment by helena-balabin** [comment]
@Santosh-Gupta We're using the AdamW optimizer, and I don't think that we're using AMP. This is how our DeepSpeed configuration file looks like:

```
{
    "fp16": {
        "enabled": "true",
        "loss_scale": 0,
        "loss_scale_window": 1000,
        "initial_scale_power": 16,
        "hysteresis": 2,
        "min_loss_scale": 1
    },

    "optimizer": {
        "type": "AdamW",
        "params": {
            "lr": "auto",
            "betas": "auto",
            "eps": "auto",
            "weight_decay": "auto"
        }
    },

    "scheduler": {
        "type": "WarmupDecayLR",
        "params": {
            "warmup_min_lr": "auto",
            "warmup_max_lr": "auto",
            "warmup_num_steps": "auto"
        }
    },

    "zero_optimization": {
        "stage": 2,
        "allgather_partitions": true,
        "allgather_bucket_size": 2e8,
        "overlap_comm": true,
        "reduce_scatter": true,
        "reduce_bucket_size": 2e8,
        "contiguous_gradients": true,
        "cpu_offload": false
    },

    "gradient_accumulation_steps": "auto",
    "gradient_clipping": "auto",
    "steps_per_print": 2000,
    "train_batch_size": "auto",
    "train_micro_batch_size_per_gpu": "auto",
    "wall_clock_breakdown": false
}
```

@jeffra So I tried to look deeper into installing the extensions, unfortunately I still haven't found a solution yet. The ds_report looks like this:  

```
--------------------------------------------------
DeepSpeed C++/CUDA extension op report
--------------------------------------------------
NOTE: Ops not installed will be just-in-time (JIT) compiled at
      runtime if needed. Op compatibility means that your system
      meet the required dependencies to JIT install the op.
--------------------------------------------------
JIT compiled ops requires ninja
ninja .................. [OKAY]
--------------------------------------------------
op name ................ installed .. compatible
--------------------------------------------------
cpu_adam ............... [NO] ....... [OKAY]
fused_adam ............. [NO] ....... [OKAY]
fused_lamb ............. [NO] ....... [OKAY]
sparse_attn ............ [NO] ....... [OKAY]
transformer ............ [NO] ....... [OKAY]
stochastic_transformer . [NO] ....... [OKAY]
 [WARNING]  async_io requires the libraries: ['libaio-dev'] but are missing. Can be fixed by: `apt install libaio-dev`.
async_io ............... [NO] ....... [NO]
transformer_inference .. [NO] ....... [OKAY]
utils .................. [NO] ....... [OKAY]
quantizer .............. [NO] ....... [OKAY]
--------------------------------------------------
DeepSpeed general environment info:
torch install path ............... ['/home/hbalabin/software/conda/envs/stonkgs/lib/python3.8/site-packages/torch']
torch version .................... 1.8.1
torch cuda version ............... 11.1
nvcc version ..................... 11.1
deepspeed install path ........... ['/home/hbalabin/software/conda/envs/stonkgs/lib/python3.8/site-packages/deepspeed']
deepspeed info ................... 0.4.0, unknown, unknown
deepspeed wheel compiled w. ...... torch 1.8, cuda 11.1`
```

Thanks for the hint regarding the ninja issue, that seems to be the reason. I found the following error message in the stack trace as well: `subprocess.CalledProcessError: Command '['ninja', '-v']' returned non-zero exit status 1.`. Running `ninja -v` indeed results in the following error: `ninja: error: loading 'build.ninja': No such file or directory`. However, installing the ninja-build turns out to be tricky on a CentOS 7 machine with no admin rights :confused:. I guess I'll have to contact our admins tomorrow. I'll keep you updated once I've managed to install ninja-build!

**Comment by Santosh-Gupta** [comment]
Something that might be useful is running without the zero optimizer enabled.

**Comment by jeffra** [comment]
Unfortunately, I think `ninja` will be required even if zero is disabled. If it's a permission issue to install ninja you might be able to install it without apt via here: https://github.com/ninja-build/ninja. I have not tried it myself though.

**Comment by jeffra** [comment]
Please re-open if not resolved.
