### ISSUE TITLE
[BUG]When using multiple nodes, no GPUs found!

### ISSUE THREAD

**Issue by Vladimir-Bayes** [microsoft/DeepSpeed#1481]
**Describe the bug**
I'm using Deepspedd to train my model with 2 nodes. Each node has 8  gpus. When it goes to **"deepspeed.init_distributed(dist_backend='nccl', verbose=True)"**
an error **"ProcessGroupNCCL is only supported with GPUs, no GPUs found!"** occurs.
It is so weird, because when I train my mode on one single node (8 gpus), it works well.

File "/root/miniconda3/lib/python3.8/site-packages/deepspeed/utils/distributed.py", line 49, in init_distributed
    torch.distributed.init_process_group(backend=dist_backend,
File "/root/miniconda3/lib/python3.8/site-packages/torch/distributed/distributed_c10d.py", line 537, in init_process_group
    default_pg = _new_process_group_helper(
File "/root/miniconda3/lib/python3.8/site-packages/torch/distributed/distributed_c10d.py", line 650, in _new_process_group_helper
pg = ProcessGroupNCCL(
RuntimeError: ProcessGroupNCCL is only supported with GPUs, no GPUs found!

I further check whether cuda is available. It turns out that **torch.cuda.is_available() is false and torch.cuda.device_count() is 0**. 

**System info (please complete the following information):**
 - OS: Ubuntu 18.04
 - GPU count and types: two machines with x8 V100 each
 - Python version: 3.8
 - CUDA: 10.2
 - Pytorch: 1.9.1
 - NCCL: 2.7.8
 - cuDNN: 7.6.5.32

**Launcher context**
 `deepspeed` launcher

**Comment by Vladimir-Bayes** [comment]
Thanks. 
I use python script to check the python path. It seems the reason why GPUs are not found becomes clear.
When I use multiple nodes to run my train script. The log shows:
before it goes into deepspeed, the python path is
```
/root/miniconda3/bin/python
```
After it goes into deepspeed, the python path is
```
/usr/bin/python
```
I further check python path using deepspeed with only 1 node. The python path keeps unchanged, which is
```
/root/miniconda3/bin/python
```
I compare these two logs when launching deepspeed. 
In single node, it is
```
 [2021-10-29 14:41:42,921] [WARNING] [runner.py:122:fetch_hostfile] Unable to find hostfile, will proceed with training with local resources only.
[2021-10-29 14:41:42,984] [INFO] [runner.py:360:main] cmd = /root/miniconda3/bin/python -u -m deepspeed.launcher.launch --world_info=eyJsb2NhbGhvc3QiOiBbMCwgMSwgMiwgMywgNCwgNSwgNiwgN119 --master_addr=127.0.0.1 --master_port=29500 /home/work/user-job-dir/ds_multinodes_test/ds_train.py --multiprocessing-distributed --deepspeed --deepspeed_config /cache/user-job-dir/ds_multinodes_test/wenlan_deepspeed_config.json
[2021-10-29 14:41:43,625] [INFO] [launch.py:73:main] 0 NCCL_VERSION 2.7.8
[2021-10-29 14:41:43,626] [INFO] [launch.py:80:main] WORLD INFO DICT: {'localhost': [0, 1, 2, 3, 4, 5, 6, 7]}
[2021-10-29 14:41:43,626] [INFO] [launch.py:86:main] nnodes=1, num_local_procs=8, node_rank=0
[2021-10-29 14:41:43,626] [INFO] [launch.py:101:main] global_rank_mapping=defaultdict(<class 'list'>, {'localhost': [0, 1, 2, 3, 4, 5, 6, 7]})
[2021-10-29 14:41:43,626] [INFO] [launch.py:102:main] dist_world_size=8
[2021-10-29 14:41:43,626] [INFO] [launch.py:104:main] Setting CUDA_VISIBLE_DEVICES=0,1,2,3,4,5,6,7
```
In 2 nodes. it is
```
[2021-10-29 14:31:18,378] [INFO] [runner.py:291:main] Using IP address of 169.254.132.118 for node job8c03acbc-custom0-0.job8c03acbc
[2021-10-29 14:31:18,379] [INFO] [multinode_runner.py:51:get_cmd] Running on the following workers: job8c03acbc-custom0-0.job8c03acbc,job8c03acbc-custom1-0.job8c03acbc
[2021-10-29 14:31:18,379] [INFO] [runner.py:360:main] cmd = pdsh -f 1024 -w job8c03acbc-custom0-0.job8c03acbc,job8c03acbc-custom1-0.job8c03acbc export PYTHONUNBUFFERED=1; export NCCL_VERSION=2.7.8; export PYTHONPATH=/cache/user-job-dir:/home/work/user-job-dir:;  cd /cache/user-job-dir; /root/miniconda3/bin/python -u -m deepspeed.launcher.launch --world_info=eyJqb2I4YzAzYWNiYy1jdXN0b20wLTAuam9iOGMwM2FjYmMiOiBbMCwgMSwgMiwgMywgNCwgNSwgNiwgN10sICJqb2I4YzAzYWNiYy1jdXN0b20xLTAuam9iOGMwM2FjYmMiOiBbMCwgMSwgMiwgMywgNCwgNSwgNiwgN119 --node_rank=%n --master_addr=169.254.132.118 --master_port=29500 /home/work/user-job-dir/ds_multinodes_test/ds_train.py --multiprocessing-distributed --deepspeed --deepspeed_config '/cache/user-job-dir/ds_multinodes_test/wenlan_deepspeed_config.json'
job8c03acbc-custom0-0: [2021-10-29 14:31:19,769] [INFO] [launch.py:73:main] 0 NCCL_VERSION 2.7.8
job8c03acbc-custom0-0: [2021-10-29 14:31:19,769] [INFO] [launch.py:80:main] WORLD INFO DICT: {'job8c03acbc-custom0-0.job8c03acbc': [0, 1, 2, 3, 4, 5, 6, 7], 'job8c03acbc-custom1-0.job8c03acbc': [0, 1, 2, 3, 4, 5, 6, 7]}
job8c03acbc-custom0-0: [2021-10-29 14:31:19,769] [INFO] [launch.py:86:main] nnodes=2, num_local_procs=8, node_rank=0
job8c03acbc-custom0-0: [2021-10-29 14:31:19,770] [INFO] [launch.py:101:main] global_rank_mapping=defaultdict(<class 'list'>, {'job8c03acbc-custom0-0.job8c03acbc': [0, 1, 2, 3, 4, 5, 6, 7], 'job8c03acbc-custom1-0.job8c03acbc': [8, 9, 10, 11, 12, 13, 14, 15]})
job8c03acbc-custom0-0: [2021-10-29 14:31:19,770] [INFO] [launch.py:102:main] dist_world_size=16
job8c03acbc-custom0-0: [2021-10-29 14:31:19,770] [INFO] [launch.py:104:main] Setting CUDA_VISIBLE_DEVICES=0,1,2,3,4,5,6,7
job8c03acbc-custom1-0: [2021-10-29 14:31:19,775] [INFO] [launch.py:73:main] 1 NCCL_VERSION 2.7.8
job8c03acbc-custom1-0: [2021-10-29 14:31:19,775] [INFO] [launch.py:80:main] WORLD INFO DICT: {'job8c03acbc-custom0-0.job8c03acbc': [0, 1, 2, 3, 4, 5, 6, 7], 'job8c03acbc-custom1-0.job8c03acbc': [0, 1, 2, 3, 4, 5, 6, 7]}
job8c03acbc-custom1-0: [2021-10-29 14:31:19,775] [INFO] [launch.py:86:main] nnodes=2, num_local_procs=8, node_rank=1
job8c03acbc-custom1-0: [2021-10-29 14:31:19,775] [INFO] [launch.py:101:main] global_rank_mapping=defaultdict(<class 'list'>, {'job8c03acbc-custom0-0.job8c03acbc': [0, 1, 2, 3, 4, 5, 6, 7], 'job8c03acbc-custom1-0.job8c03acbc': [8, 9, 10, 11, 12, 13, 14, 15]})
job8c03acbc-custom1-0: [2021-10-29 14:31:19,775] [INFO] [launch.py:102:main] dist_world_size=16
job8c03acbc-custom1-0: [2021-10-29 14:31:19,775] [INFO] [launch.py:104:main] Setting CUDA_VISIBLE_DEVICES=0,1,2,3,4,5,6,7
```
The reason is the changing of python path, it is right? If so, how can I fix it?

**Comment by jeffra** [comment]
```
[2021-10-29 14:31:18,379] [INFO] [runner.py:360:main] cmd = ... /root/miniconda3/bin/python ...
```

I do see in your 2 node example it is also using the same miniconda path though. It's a longer command but i've reduced it above.

In the multi-node launching case the launcher will use `pdsh` to launch new processes over `ssh` which sometimes we've seen drop certain parts of the environment. Can you try the single node case but pass `--force_multi`, this will force the single node case to use pdsh for launching the local processes.

Also can you try running a test python script that only has these contents? this will also tell us what python path is being used:

```python
import sys
print(sys.executable)
```

**Comment by Vladimir-Bayes** [comment]
Thanks for your advice. 
I tried to use `sys.executable` to check the python path, the log gives `/root/miniconda3/bin/python`. It seems there is no problem about the python path.
I also tried to use `--force_multi` on a single node with 8 gpus. Also, gpus are not found. Here are some logs:

```
2021-11-03 14:41:15,165] [WARNING] [runner.py:122:fetch_hostfile] Unable to find hostfile, will proceed with training with local resources only.
[2021-11-03 14:41:15,228] [INFO] [multinode_runner.py:51:get_cmd] Running on the following workers: localhost
[2021-11-03 14:41:15,228] [INFO] [runner.py:360:main] cmd = pdsh -f 1024 -w localhost export PYTHONUNBUFFERED=1; export NCCL_VERSION=2.7.8; export PYTHONPATH=/cache/user-job-dir:/home/work/user-job-dir:;  cd /cache/user-job-dir; /root/miniconda3/bin/python -u -m deepspeed.launcher.launch --world_info=eyJsb2NhbGhvc3QiOiBbMCwgMSwgMiwgMywgNCwgNSwgNiwgN119 --node_rank=%n --master_addr=127.0.0.1 --master_port=29500 /home/work/user-job-dir/ds_multinodes_test/ds_train.py --multiprocessing-distributed --deepspeed --deepspeed_config '/cache/user-job-dir/ds_multinodes_test/wenlan_deepspeed_config.json'
localhost: Warning: Permanently added '[localhost]:3411' (RSA) to the list of known hosts.
localhost: [2021-11-03 14:41:16,575] [INFO] [launch.py:73:main] 0 NCCL_VERSION 2.7.8
localhost: [2021-11-03 14:41:16,575] [INFO] [launch.py:80:main] WORLD INFO DICT: {'localhost': [0, 1, 2, 3, 4, 5, 6, 7]}
localhost: [2021-11-03 14:41:16,575] [INFO] [launch.py:86:main] nnodes=1, num_local_procs=8, node_rank=0
localhost: [2021-11-03 14:41:16,575] [INFO] [launch.py:101:main] global_rank_mapping=defaultdict(<class 'list'>, {'localhost': [0, 1, 2, 3, 4, 5, 6, 7]})
localhost: [2021-11-03 14:41:16,575] [INFO] [launch.py:102:main] dist_world_size=8
localhost: [2021-11-03 14:41:16,576] [INFO] [launch.py:104:main] Setting CUDA_VISIBLE_DEVICES=0,1,2,3,4,5,6,7
localhost: ************** which python *******************
localhost: /usr/bin/python
localhost: /root/miniconda3/bin/python
localhost: ************** end which python *******************
localhost: torch.version: 1.8.1+cu102
localhost: torch.cuda.device_count():  0
localhost: torch.cuda.torch.cuda.is_available():  False
localhost: 11/03/2021 14:41:17 - INFO - __main__ - start deepspeed_main for global_rank: 5, is_gpu_available: False
localhost: 11/03/2021 14:41:17 - INFO - __main__ - ************** Training Configs *******************
localhost: 11/03/2021 14:41:17 - INFO - __main__ - torch.cuda.device_count(): 0
localhost: 11/03/2021 14:41:17 - INFO - __main__ - args: Namespace(deepscale=False, deepscale_config=None, deepspeed=True, deepspeed_config='/cache/user-job-dir/ds_multinodes_test/wenlan_deepspeed_config.json', deepspeed_mpi=False, local_rank=5, multiprocessing_distributed=True)
localhost: 11/03/2021 14:41:17 - INFO - __main__ - ************** end Training Configs *******************
localhost: [2021-11-03 14:41:17,255] [INFO] [distributed.py:46:init_distributed] Initializing torch distributed with backend: nccl

...

localhost: Traceback (most recent call last):
localhost:   File "/home/work/user-job-dir/ds_multinodes_test/ds_train.py", line 152, in <module>
localhost:     deepspeed_main()
localhost:   File "/home/work/user-job-dir/ds_multinodes_test/ds_train.py", line 43, in deepspeed_main
localhost:     deepspeed.init_distributed(dist_backend='nccl', verbose=True)
localhost:   File "/root/miniconda3/lib/python3.8/site-packages/deepspeed/utils/distributed.py", line 49, in init_distributed
localhost:     torch.distributed.init_process_group(backend=dist_backend,
localhost:   File "/root/miniconda3/lib/python3.8/site-packages/torch/distributed/distributed_c10d.py", line 503, in init_process_group
localhost:     _update_default_pg(_new_process_group_helper(
localhost:   File "/root/miniconda3/lib/python3.8/site-packages/torch/distributed/distributed_c10d.py", line 599, in _new_process_group_helper
localhost:     pg = ProcessGroupNCCL(
localhost: RuntimeError: ProcessGroupNCCL is only supported with GPUs, no GPUs found!
```

**Comment by jeffra** [comment]
Interesting. Can you create a test script that outputs device count called testy.py? Then ssh into localhost and try execute it like this:

ssh -p <port> localhost “python test.py”

This is essentially what the launcher is doing, let’s see if we can repro the issue like this. If so, then it might be easier to debug how/why the environment is not working across ssh.

**Comment by Vladimir-Bayes** [comment]
Thanks for your advices.
I finally solved this problem. The reason is that the environment variables are changed when multi-node training. I write a script to construct the pdsh command and supply these environment variables like "export XXX=XXX." It may also be related to our computing platform e.g., some specific settings. Nevertheless, the problem is solved now.
Thanks again.

**Comment by XiaoYee** [comment]
Hello, may you share your new script for pdsh? I had the exact same problem as you. @Vladimir-Bayes

**Comment by huqinghao** [comment]
I just met a similar problem.   I  run the deepspeed codes inside the  Nvidia docker container, and the codes work well on a single node but fail on two distributed nodes.  The output said "RuntimeError: ProcessGroupNCCL is only supported with GPUs, no GPUs found!". 
The pdsh launcher executes the program via SSH, but my docker container's environment variables changed via SSH. It seems that SSH wipes out the environment as part of the login process.  By running 
`env | grep _ >> /etc/environment` in the container, the problem is solved.

**Comment by EsonJohn** [comment]
> Thanks for your advices. I finally solved this problem. The reason is that the environment variables are changed when multi-node training. I write a script to construct the pdsh command and supply these environment variables like "export XXX=XXX." It may also be related to our computing platform e.g., some specific settings. Nevertheless, the problem is solved now. Thanks again.

I have a similar problem using deepspeed+pdsh+docker. It seems to be the environment variable issue.
What variables did you export manually via pdsh command?
