### ISSUE TITLE
[BUG] Illegal memory access CUDA error when using long sequences 

### ISSUE THREAD

**Issue by tomeras91** [microsoft/DeepSpeed#2062]
**Describe the bug**
Running a forward pass on a `DeepSpeedTransformerInference` layer, with a sequence length of ~1000 tokens, results in an illegal memory access CUDA error.

**To Reproduce**
Here is a minimal reproducible example that shows the bug:
```
from deepspeed.ops.transformer import DeepSpeedInferenceConfig, DeepSpeedTransformerInference
import torch

torch.cuda.set_device(0)

hidden_size = 256
heads = 8
num_layers = 12
fp16 = True
layernorm_epsilon = 1e-5
deepspeed_config = DeepSpeedInferenceConfig(hidden_size=hidden_size,
                                            intermediate_size=hidden_size * 4,
                                            heads=heads,
                                            num_hidden_layers=num_layers,
                                            layer_norm_eps=layernorm_epsilon,
                                            # encoder_decoder=False,
                                            fp16=fp16,
                                            pre_layer_norm=True,
                                            stochastic_mode=False,
                                            scale_attention=True,
                                            triangular_masking=True,
                                            local_attention=False,
                                            window_size=256,
                                            )
transformer = DeepSpeedTransformerInference(config=deepspeed_config)
transformer.half()
new_state_dict = {k: 0.01*torch.ones(*v.shape, dtype=v.dtype, device=v.device)
                  for k,v in transformer.state_dict().items()}
transformer.load_state_dict(new_state_dict)
transformer.cuda()
device = list(transformer.parameters())[0].device

batch_size = 1
seq_len = 1000
inputs = torch.ones((batch_size, seq_len, hidden_size), dtype=torch.float16, device=device)
input_mask = torch.ones(*inputs.shape[:2], dtype=bool, device=device)

output, _ = transformer(
    input=inputs,
    input_mask=input_mask)

print(f"outupt: \n {output}")
```

**Running the code resulted with the following exception**
```
RuntimeError: CUDA error: an illegal memory access was encountered
```

**Expected behavior**
I was expecting to get a correct output, without the excpetion.

**ds_report output**
```
[2022-06-28 10:35:33,425] [WARNING] [partition_parameters.py:60:<module>] unable to find torch.distributed._all_gather_base. will fall back to torch.distributed.all_gather which will result in suboptimal performance. please consider upgrading your pytorch installation.
--------------------------------------------------
DeepSpeed C++/CUDA extension op report
--------------------------------------------------
NOTE: Ops not installed will be just-in-time (JIT) compiled at
      runtime if needed. Op compatibility means that your system
      meet the required dependencies to JIT install the op.
--------------------------------------------------
JIT compiled ops requires ninja
ninja .................. [OKAY]
--------------------------------------------------
op name ................ installed .. compatible
--------------------------------------------------
cpu_adam ............... [NO] ....... [OKAY]
cpu_adagrad ............ [NO] ....... [OKAY]
fused_adam ............. [NO] ....... [OKAY]
fused_lamb ............. [NO] ....... [OKAY]
 [WARNING]  using untested triton version (1.1.1), only 1.0.0 is known to be compatible
sparse_attn ............ [NO] ....... [NO]
transformer ............ [NO] ....... [OKAY]
stochastic_transformer . [NO] ....... [OKAY]
 [WARNING]  async_io requires the dev libaio .so object and headers but these were not found.
 [WARNING]  async_io: please install the libaio-dev package with apt
 [WARNING]  If libaio is already installed (perhaps from source), try setting the CFLAGS and LDFLAGS environment variables to where it can be found.
async_io ............... [NO] ....... [NO]
utils .................. [NO] ....... [OKAY]
quantizer .............. [NO] ....... [OKAY]
transformer_inference .. [NO] ....... [OKAY]
--------------------------------------------------
DeepSpeed general environment info:
torch install path ............... ['/opt/conda/lib/python3.8/site-packages/torch']
torch version .................... 1.8.0a0+1606899
torch cuda version ............... 11.1
torch hip version ................ None
nvcc version ..................... 11.1
deepspeed install path ........... ['/opt/conda/lib/python3.8/site-packages/deepspeed']
deepspeed info ................... 0.6.5, unknown, unknown
deepspeed wheel compiled w. ...... torch 1.8, cuda 11.1
```

**System info (please complete the following information):**
 - OS: Ubuntu 20.04
 - GPU count and types: a single A100 GPU
 - Python version: 3.8.5

**Launcher context**
Launching directly using Python interpreter.

**Additional context**
_Maybe_ the bug is related to line 20 in `csrc/transformer/inference/includes/custom_cuda_layers.h`? It reads:
```
#define MAX_OUT_TOKES 1024
```

**Comment by mrwyattii** [comment]
@tomeras91 I can confirm that I'm able to reproduce this error. I don't think it has anything to do with `MAX_OUT_TOKES`. @RezaYazdaniAminabadi could you take a look at this?

**Comment by RezaYazdaniAminabadi** [comment]
Hi @tomeras91 

Thanks for reporting this issue. I will look into this.
@mrwyattii, thanks for reproducing this. Yes, I think the issue is probably somewhere else.
Thanks,
Reza

**Comment by mallorbc** [comment]
I also have encountered this error.  Trying small inputs such as what the tutorial uses "DeepSpeed is" leads to normal results, but using significantly longer input leads to an illegal memory error.

I would try version 0.6.6 or earlier as suggested by @trianxy but I want to use long sequences with GPTJ and GPT Neo 2.7B and those had issues up until recently as can be seen in #2233 .  

My build is the same as the one in that issue, just with DeepSpeed built from source shortly after the PR that fixed the issue.

**Comment by mallorbc** [comment]
> FYI @mallorbc , @tomeras91 , @RezaYazdaniAminabadi :
> 
> My related issue which I detailed above is fixed in [this PR](https://github.com/microsoft/DeepSpeed/pull/2212). More precisely, my issue does not appear when I install the commit [4abd455](https://github.com/microsoft/DeepSpeed/commit/4abd455521965930d0e921de8afc0073ea7df9d1)
> 
> Thanks for that fix!

If I recall, I also tried building from that PR and had issues with poor outputs for GPT Neo and GPTJ.  I believe one of the branches I built fixed the memory error but still gave garbage output for long inputs.  Perhaps this is the one.  

Perhaps I am remembering wrong though, I will try this again later and see if it fixed anything, but again I think I tried this already.

Thanks!

**Comment by EdouardVilain-Git** [comment]
Hi everyone,
I am encountering the same issues with a RoBERTa type model on which I ran 8 bit MoQ during training. 
When instantiating the inference engine using:
`engine = deepspeed.init_inference(deepspeed_trainer.model,
    dtype=torch.half,
    quantization_setting=(False,64),
    replace_with_kernel_inject=True
)` 
I get the same error than the one mentioned by @tomeras91 and @trianxy. Do you know when this issue may be fixed?
This also raises a question I had: is it possible to use Deepspeed for training (typically for QAT) and infer using torch? 
I would like to use the quantized weights of my model trained using Deepspeed to create a quantized torch instance for inference. It is still unclear if/how I could do so.

Thank you for your help!

**Comment by carlose2108** [comment]
Hi @trianxy!
Could you solve this issue?
