### ISSUE TITLE
Question about DDP error in DeepSpeed

### ISSUE THREAD

**Issue by tjdgh0715** [microsoft/DeepSpeed#2069]
Hello, Thanks for the excellent work. I opened the ticket to get some support for my issue.
I have some issues when running DeepSpeed with DDP in my environment.

I was trying to evaluate the performance of Progressive Layer Dropping system by launching <https://github.com/microsoft/DeepSpeedExamples/blob/master/bing_bert/deepspeed_train.py>.
I have configured the BERT-base model and DeepSpeed configuration with the reference of Deepspeed’s document and ‘DeepSpeedExamples’ code. Also, I used NVIDIA's wikicorpus data subset for training.


This is my DeepSpeed configuration JSON file.
```
{
  "train_batch_size": 4096,
  "train_micro_batch_size_per_gpu": 16,
  "steps_per_print": 1000,
  "prescale_gradients": true,
  "gradient_predivide_factor": 8,
  
  "optimizer": {
    "type": "Adam",
    "params": {
      "lr": 1e-3,
      "weight_decay": 0.01,
      "bias_correction": false
    }
  },
  "gradient_clipping": 1.0,
  "wall_clock_breakdown": false,

  "fp16": {
    "enabled": true,
    "loss_scale": 0
  }
}
```
And this is my bert configuration JSON file.
```
{
    "name": "bing_bert_base_adam_seq",
    "bert_token_file": "bert-base-uncased",
    "bert_model_file": "bert-base-uncased",
    "bert_model_config": {
        "vocab_size_or_config_json_file": 119547,
        "hidden_size": 768,
        "num_hidden_layers": 12,
        "num_attention_heads": 12,
        "intermediate_size": 3072,
        "hidden_act": "gelu",
        "hidden_dropout_prob": 0.1,
        "attention_probs_dropout_prob": 0.1,
        "max_position_embeddings": 512,
        "type_vocab_size": 2,
        "initializer_range": 0.02
    },
    "data": {
        "flags": {
            "pretrain_dataset": true,
            "pretrain_type": "wiki_bc"
        },
        "mixed_seq_datasets": {
            "128": {
                "pretrain_dataset": "/data/private/Layer_Skipping/Progressive_Layer_Dropping/DeepSpeedExamples/data/wikicorpus_en/train"
            },
            "512": {
                "pretrain_dataset": "data/512"
            }
        }
    },
    "mixed_seq_training": {
        "128": {
            "num_epochs": 200,
            "warmup_proportion": 0.02,
            "learning_rate": 1e-3,
            "num_workers": 0,
            "async_worker": true,
            "decay_rate": 0.99,
            "decay_step": 1000,
            "total_training_steps": 200000
        }
    },
    "validation": {
        "path": "/data/private/Layer_Skipping/Progressive_Layer_Dropping/DeepSpeedExamples/data/wikicorpus_en/test"
    }
}

```

However, when I started pre-training using DDP, the script got frozen at epoch 1, and it looks very strange.
The GPU usage is stuck at 100% and the process also uses CPU over 100%. 
I have a doubt about this issue that occurred at the backward computation with DeepSpeed, but I am not totally sure about it.

I am launching DeepSpeed with DDP in VPN cloud server. The server has 4 x Tesla V100-SXM2-32GB GPU, and 56 x Intel(R) Xeon(R) Gold 5120 CPU @ 2.20GHz. I have 503G memory & 10G swap memory. I tried to specify the issue by using the following checklist.

1.  I checked the log of DDP training without PLD. The error persists when I started DDP training without PLD too.

2.  I checked if the issue is related to all-reduce in my H/W setup. I used this code to test all-reduce, and I set the `local_rank` to 0. 
```
import torch
import torch.distributed as dist
import time
import argparse
import os
import deepspeed

TRIALS = 5

# 6GB
N = 500000
M = 500 * 6

def timed_allreduce(mat):
    torch.cuda.synchronize()
    pre = time.perf_counter()
    dist.all_reduce(mat)
    #print('ignore me', mat[0][0])  # required due to lazy evaluation
    torch.cuda.synchronize()
    duration = time.perf_counter() - pre
    #print("duration: %f sec" % duration)
    tput = ((M*N*4*2)/duration)*8
    #print("algo throughput: %f bps, %f Gbps" % (tput, tput/1e9))
    size = M * N * 4
    n = dist.get_world_size()
    busbw = (size / duration) * (2 * (n - 1) / n) * 8
    #print("busbw: %f Gbps" % (busbw / 1e9))
    return tput, busbw

def run(local_rank):
    global_rank = dist.get_rank()
    if global_rank == 0:
        print(global_rank, "data size:", M*N*4/1e9, "GB")
    mat = torch.rand(N, M, dtype=torch.float32).cuda(local_rank)

    tputs = []
    busbws = []
    for trial in range(TRIALS):
        tput, busbw = timed_allreduce(mat)
        if trial > 2:
            tputs.append(tput)
            busbws.append(busbw)

    local_avg = sum(tputs) / len(tputs)
    local_avg_bb = sum(busbws) / len(busbws)
    t = torch.tensor([local_avg/1e9, local_avg_bb/1e9], device='cuda')
    dist.all_reduce(t)
    tput_avg = t[0] / dist.get_world_size()
    busbw_avg = t[1] / dist.get_world_size()
    if dist.get_rank() == 0:
        print('tput_avg (Gbps):', tput_avg.item(), 'busbw_avg (Gbps):', busbw_avg.item())
    dist.barrier()

def init_processes(local_rank, fn, backend='nccl'):
    deepspeed.init_distributed(dist_backend=backend)
    local_rank = int(os.environ['LOCAL_RANK'])
    torch.cuda.set_device(local_rank)
    fn(local_rank)


if __name__ == "__main__":
    parser = argparse.ArgumentParser()
    parser.add_argument("--local_rank", type=int)
    args = parser.parse_args()
    rank = args.local_rank
    #print("local_rank: %d" % rank)
    init_processes(local_rank=rank, fn=run)
```
The all-reduce performed well. But, when I changed the data size to 8GB, the GPU with rank #0 raised OOM.

3. I checked if the batch size is the issue in my environment. So I changed the configuration, which has `global_batch_size=4` and `micro_batch_size=1`. With the smallest batch size, the error still persists.

4. I checked if my distributed environment is the problem with DDP training. I launched Pytorch DDP to train ResNet-101 without DeepSpeed in my distributed environment, and it worked well.




This is my output with `ds_report`.
 
```
[2022-07-05 16:25:44,914] [WARNING] [partition_parameters.py:60:<module>] unable to find torch.distributed._all_gather_base. will fall back to torch.distributed.all_gather which will result in suboptimal performance. please consider upgrading your pytorch installation.
--------------------------------------------------
DeepSpeed C++/CUDA extension op report
--------------------------------------------------
NOTE: Ops not installed will be just-in-time (JIT) compiled at
      runtime if needed. Op compatibility means that your system
      meet the required dependencies to JIT install the op.
--------------------------------------------------
JIT compiled ops requires ninja
ninja .................. [OKAY]
--------------------------------------------------
op name ................ installed .. compatible
--------------------------------------------------
cpu_adam ............... [YES] ...... [OKAY]
cpu_adagrad ............ [YES] ...... [OKAY]
fused_adam ............. [YES] ...... [OKAY]
fused_lamb ............. [YES] ...... [OKAY]
sparse_attn ............ [YES] ...... [OKAY]
transformer ............ [YES] ...... [OKAY]
stochastic_transformer . [YES] ...... [OKAY]
async_io ............... [YES] ...... [OKAY]
utils .................. [YES] ...... [OKAY]
quantizer .............. [YES] ...... [OKAY]
transformer_inference .. [YES] ...... [OKAY]
--------------------------------------------------
DeepSpeed general environment info:
torch install path ............... ['/opt/conda/envs/deepspeed/lib/python3.8/site-packages/torch']
torch version .................... 1.8.0
torch cuda version ............... 11.1
torch hip version ................ None
nvcc version ..................... 11.1
deepspeed install path ........... ['/opt/conda/envs/deepspeed/lib/python3.8/site-packages/deepspeed']
deepspeed info ................... 0.6.5, unknown, unknown
deepspeed wheel compiled w. ...... torch 1.8, cuda 11.1
```



And this my full log with DDP issue. The script got frozen at the end of this log.

```
[2022-07-05 16:29:26,180] [WARNING] [partition_parameters.py:60:<module>] unable to find torch.distributed._all_gather_base. will fall back to torch.distributed.all_gather which will result in suboptimal performance. please consider upgrading your pytorch installation.
[2022-07-05 16:29:26,214] [WARNING] [runner.py:159:fetch_hostfile] Unable to find hostfile, will proceed with training with local resources only.
[2022-07-05 16:29:26,375] [INFO] [runner.py:457:main] cmd = /opt/conda/envs/deepspeed/bin/python -u -m deepspeed.launcher.launch --world_info=eyJsb2NhbGhvc3QiOiBbMCwgMSwgMiwgM119 --master_addr=127.0.0.1 --master_port=29500 /data/private/Layer_Skipping/Progressive_Layer_Dropping/DeepSpeedExamples/bing_bert/deepspeed_train.py --deepspeed --deepspeed_config /data/private/Layer_Skipping/Progressive_Layer_Dropping/DeepSpeedExamples/data/deepspeed_PLD_base.json --cf /data/private/Layer_Skipping/Progressive_Layer_Dropping/DeepSpeedExamples/data/bert_base.json --max_seq_length 128 --print_steps 100 --use_nvidia_dataset --validation_data_path_prefix /data/private/Layer_Skipping/Progressive_Layer_Dropping/DeepSpeedExamples/data/wikicorpus_en/test --output_dir /data/private/Layer_Skipping/Progressive_Layer_Dropping/DeepSpeedExamples/bert_output/DDP/base
[2022-07-05 16:29:27,384] [WARNING] [partition_parameters.py:60:<module>] unable to find torch.distributed._all_gather_base. will fall back to torch.distributed.all_gather which will result in suboptimal performance. please consider upgrading your pytorch installation.
[2022-07-05 16:29:27,418] [INFO] [launch.py:103:main] WORLD INFO DICT: {'localhost': [0, 1, 2, 3]}
[2022-07-05 16:29:27,418] [INFO] [launch.py:109:main] nnodes=1, num_local_procs=4, node_rank=0
[2022-07-05 16:29:27,418] [INFO] [launch.py:122:main] global_rank_mapping=defaultdict(<class 'list'>, {'localhost': [0, 1, 2, 3]})
[2022-07-05 16:29:27,418] [INFO] [launch.py:123:main] dist_world_size=4
[2022-07-05 16:29:27,418] [INFO] [launch.py:125:main] Setting CUDA_VISIBLE_DEVICES=0,1,2,3
[2022-07-05 16:29:28,751] [WARNING] [partition_parameters.py:60:<module>] unable to find torch.distributed._all_gather_base. will fall back to torch.distributed.all_gather which will result in suboptimal performance. please consider upgrading your pytorch installation.
[2022-07-05 16:29:28,751] [WARNING] [partition_parameters.py:60:<module>] unable to find torch.distributed._all_gather_base. will fall back to torch.distributed.all_gather which will result in suboptimal performance. please consider upgrading your pytorch installation.
[2022-07-05 16:29:28,760] [WARNING] [partition_parameters.py:60:<module>] unable to find torch.distributed._all_gather_base. will fall back to torch.distributed.all_gather which will result in suboptimal performance. please consider upgrading your pytorch installation.
[2022-07-05 16:29:28,764] [WARNING] [partition_parameters.py:60:<module>] unable to find torch.distributed._all_gather_base. will fall back to torch.distributed.all_gather which will result in suboptimal performance. please consider upgrading your pytorch installation.
Running Config File:  bing_bert_base_adam_seq
Args = Namespace(attention_dropout_checkpoint=False, ckpt_to_save=None, config={'name': 'bing_bert_base_adam_seq', 'bert_token_file': 'bert-base-uncased', 'bert_model_file': 'bert-base-uncased', 'bert_model_config': {'vocab_size_or_config_json_file': 119547, 'hidden_size': 768, 'num_hidden_layers': 12, 'num_attention_heads': 12, 'intermediate_size': 3072, 'hidden_act': 'gelu', 'hidden_dropout_prob': 0.1, 'attention_probs_dropout_prob': 0.1, 'max_position_embeddings': 512, 'type_vocab_size': 2, 'initializer_range': 0.02}, 'data': {'flags': {'pretrain_dataset': True, 'pretrain_type': 'wiki_bc'}, 'datasets': {'pretrain_dataset': '/data/private/Layer_Skipping/Progressive_Layer_Dropping/DeepSpeedExamples/data/wikicorpus_en/train'}}, 'validation': {'path': '/data/private/Layer_Skipping/Progressive_Layer_Dropping/DeepSpeedExamples/data/wikicorpus_en/test'}, 'training': {'num_epochs': 200, 'warmup_proportion': 0.02, 'learning_rate': 0.001, 'num_workers': 0, 'async_worker': True, 'decay_rate': 0.99, 'decay_step': 1000, 'total_training_steps': 200000}}, config_file='/data/private/Layer_Skipping/Progressive_Layer_Dropping/DeepSpeedExamples/data/bert_base.json', data_path_prefix='', deepscale=False, deepscale_config=None, deepspeed=True, deepspeed_config='/data/private/Layer_Skipping/Progressive_Layer_Dropping/DeepSpeedExamples/data/deepspeed_PLD_base.json', deepspeed_mpi=False, deepspeed_sparse_attention=False, deepspeed_transformer_kernel=False, do_lower_case=True, finetune=False, gelu_checkpoint=False, job_name='bing_bert_base_adam_seq', load_checkpoint_id=None, load_training_checkpoint=None, local_rank=1, logger=<turing.logger.Logger object at 0x7f0d95f2ad90>, lr_offset=0.0, lr_schedule='LE', max_predictions_per_seq=80, max_seq_length=128, max_steps=9223372036854775807, max_steps_per_epoch=9223372036854775807, no_cuda=False, normalize_invertible=False, output_dir='/data/private/Layer_Skipping/Progressive_Layer_Dropping/DeepSpeedExamples/bert_output/DDP/base', print_steps=100, progressive_layer_drop=False, refresh_bucket_size=1, rewarmup=False, seed=42, stochastic_mode=False, use_nvidia_dataset=True, use_pretrain=False, validation_data_path_prefix='/data/private/Layer_Skipping/Progressive_Layer_Dropping/DeepSpeedExamples/data/wikicorpus_en/test')
Running Config File:  bing_bert_base_adam_seq
Args = Namespace(attention_dropout_checkpoint=False, ckpt_to_save=None, config={'name': 'bing_bert_base_adam_seq', 'bert_token_file': 'bert-base-uncased', 'bert_model_file': 'bert-base-uncased', 'bert_model_config': {'vocab_size_or_config_json_file': 119547, 'hidden_size': 768, 'num_hidden_layers': 12, 'num_attention_heads': 12, 'intermediate_size': 3072, 'hidden_act': 'gelu', 'hidden_dropout_prob': 0.1, 'attention_probs_dropout_prob': 0.1, 'max_position_embeddings': 512, 'type_vocab_size': 2, 'initializer_range': 0.02}, 'data': {'flags': {'pretrain_dataset': True, 'pretrain_type': 'wiki_bc'}, 'datasets': {'pretrain_dataset': '/data/private/Layer_Skipping/Progressive_Layer_Dropping/DeepSpeedExamples/data/wikicorpus_en/train'}}, 'validation': {'path': '/data/private/Layer_Skipping/Progressive_Layer_Dropping/DeepSpeedExamples/data/wikicorpus_en/test'}, 'training': {'num_epochs': 200, 'warmup_proportion': 0.02, 'learning_rate': 0.001, 'num_workers': 0, 'async_worker': True, 'decay_rate': 0.99, 'decay_step': 1000, 'total_training_steps': 200000}}, config_file='/data/private/Layer_Skipping/Progressive_Layer_Dropping/DeepSpeedExamples/data/bert_base.json', data_path_prefix='', deepscale=False, deepscale_config=None, deepspeed=True, deepspeed_config='/data/private/Layer_Skipping/Progressive_Layer_Dropping/DeepSpeedExamples/data/deepspeed_PLD_base.json', deepspeed_mpi=False, deepspeed_sparse_attention=False, deepspeed_transformer_kernel=False, do_lower_case=True, finetune=False, gelu_checkpoint=False, job_name='bing_bert_base_adam_seq', load_checkpoint_id=None, load_training_checkpoint=None, local_rank=2, logger=<turing.logger.Logger object at 0x7fd517157dc0>, lr_offset=0.0, lr_schedule='LE', max_predictions_per_seq=80, max_seq_length=128, max_steps=9223372036854775807, max_steps_per_epoch=9223372036854775807, no_cuda=False, normalize_invertible=False, output_dir='/data/private/Layer_Skipping/Progressive_Layer_Dropping/DeepSpeedExamples/bert_output/DDP/base', print_steps=100, progressive_layer_drop=False, refresh_bucket_size=1, rewarmup=False, seed=42, stochastic_mode=False, use_nvidia_dataset=True, use_pretrain=False, validation_data_path_prefix='/data/private/Layer_Skipping/Progressive_Layer_Dropping/DeepSpeedExamples/data/wikicorpus_en/test')
Running Config File:  bing_bert_base_adam_seq
Args = Namespace(attention_dropout_checkpoint=False, ckpt_to_save=None, config={'name': 'bing_bert_base_adam_seq', 'bert_token_file': 'bert-base-uncased', 'bert_model_file': 'bert-base-uncased', 'bert_model_config': {'vocab_size_or_config_json_file': 119547, 'hidden_size': 768, 'num_hidden_layers': 12, 'num_attention_heads': 12, 'intermediate_size': 3072, 'hidden_act': 'gelu', 'hidden_dropout_prob': 0.1, 'attention_probs_dropout_prob': 0.1, 'max_position_embeddings': 512, 'type_vocab_size': 2, 'initializer_range': 0.02}, 'data': {'flags': {'pretrain_dataset': True, 'pretrain_type': 'wiki_bc'}, 'datasets': {'pretrain_dataset': '/data/private/Layer_Skipping/Progressive_Layer_Dropping/DeepSpeedExamples/data/wikicorpus_en/train'}}, 'validation': {'path': '/data/private/Layer_Skipping/Progressive_Layer_Dropping/DeepSpeedExamples/data/wikicorpus_en/test'}, 'training': {'num_epochs': 200, 'warmup_proportion': 0.02, 'learning_rate': 0.001, 'num_workers': 0, 'async_worker': True, 'decay_rate': 0.99, 'decay_step': 1000, 'total_training_steps': 200000}}, config_file='/data/private/Layer_Skipping/Progressive_Layer_Dropping/DeepSpeedExamples/data/bert_base.json', data_path_prefix='', deepscale=False, deepscale_config=None, deepspeed=True, deepspeed_config='/data/private/Layer_Skipping/Progressive_Layer_Dropping/DeepSpeedExamples/data/deepspeed_PLD_base.json', deepspeed_mpi=False, deepspeed_sparse_attention=False, deepspeed_transformer_kernel=False, do_lower_case=True, finetune=False, gelu_checkpoint=False, job_name='bing_bert_base_adam_seq', load_checkpoint_id=None, load_training_checkpoint=None, local_rank=0, logger=<turing.logger.Logger object at 0x7fe04bbe1d90>, lr_offset=0.0, lr_schedule='LE', max_predictions_per_seq=80, max_seq_length=128, max_steps=9223372036854775807, max_steps_per_epoch=9223372036854775807, no_cuda=False, normalize_invertible=False, output_dir='/data/private/Layer_Skipping/Progressive_Layer_Dropping/DeepSpeedExamples/bert_output/DDP/base', print_steps=100, progressive_layer_drop=False, refresh_bucket_size=1, rewarmup=False, seed=42, stochastic_mode=False, use_nvidia_dataset=True, use_pretrain=False, validation_data_path_prefix='/data/private/Layer_Skipping/Progressive_Layer_Dropping/DeepSpeedExamples/data/wikicorpus_en/test')
Running Config File:  bing_bert_base_adam_seq
Args = Namespace(attention_dropout_checkpoint=False, ckpt_to_save=None, config={'name': 'bing_bert_base_adam_seq', 'bert_token_file': 'bert-base-uncased', 'bert_model_file': 'bert-base-uncased', 'bert_model_config': {'vocab_size_or_config_json_file': 119547, 'hidden_size': 768, 'num_hidden_layers': 12, 'num_attention_heads': 12, 'intermediate_size': 3072, 'hidden_act': 'gelu', 'hidden_dropout_prob': 0.1, 'attention_probs_dropout_prob': 0.1, 'max_position_embeddings': 512, 'type_vocab_size': 2, 'initializer_range': 0.02}, 'data': {'flags': {'pretrain_dataset': True, 'pretrain_type': 'wiki_bc'}, 'datasets': {'pretrain_dataset': '/data/private/Layer_Skipping/Progressive_Layer_Dropping/DeepSpeedExamples/data/wikicorpus_en/train'}}, 'validation': {'path': '/data/private/Layer_Skipping/Progressive_Layer_Dropping/DeepSpeedExamples/data/wikicorpus_en/test'}, 'training': {'num_epochs': 200, 'warmup_proportion': 0.02, 'learning_rate': 0.001, 'num_workers': 0, 'async_worker': True, 'decay_rate': 0.99, 'decay_step': 1000, 'total_training_steps': 200000}}, config_file='/data/private/Layer_Skipping/Progressive_Layer_Dropping/DeepSpeedExamples/data/bert_base.json', data_path_prefix='', deepscale=False, deepscale_config=None, deepspeed=True, deepspeed_config='/data/private/Layer_Skipping/Progressive_Layer_Dropping/DeepSpeedExamples/data/deepspeed_PLD_base.json', deepspeed_mpi=False, deepspeed_sparse_attention=False, deepspeed_transformer_kernel=False, do_lower_case=True, finetune=False, gelu_checkpoint=False, job_name='bing_bert_base_adam_seq', load_checkpoint_id=None, load_training_checkpoint=None, local_rank=3, logger=<turing.logger.Logger object at 0x7f53a6309dc0>, lr_offset=0.0, lr_schedule='LE', max_predictions_per_seq=80, max_seq_length=128, max_steps=9223372036854775807, max_steps_per_epoch=9223372036854775807, no_cuda=False, normalize_invertible=False, output_dir='/data/private/Layer_Skipping/Progressive_Layer_Dropping/DeepSpeedExamples/bert_output/DDP/base', print_steps=100, progressive_layer_drop=False, refresh_bucket_size=1, rewarmup=False, seed=42, stochastic_mode=False, use_nvidia_dataset=True, use_pretrain=False, validation_data_path_prefix='/data/private/Layer_Skipping/Progressive_Layer_Dropping/DeepSpeedExamples/data/wikicorpus_en/test')
07/05/2022 16:29:29 - INFO - pytorch_pretrained_bert.tokenization -   loading vocabulary file https://s3.amazonaws.com/models.huggingface.co/bert/bert-base-uncased-vocab.txt from cache at /root/.pytorch_pretrained_bert/26bc1ad6c0ac742e9b52263248f6d0f00068293b33709fae12320c0e35ccfbbb.542ce4285a40d23a559526243235df47c5f75c197f04f37d1a0c124c32c9a084
07/05/2022 16:29:29 - INFO - pytorch_pretrained_bert.tokenization -   loading vocabulary file https://s3.amazonaws.com/models.huggingface.co/bert/bert-base-uncased-vocab.txt from cache at /root/.pytorch_pretrained_bert/26bc1ad6c0ac742e9b52263248f6d0f00068293b33709fae12320c0e35ccfbbb.542ce4285a40d23a559526243235df47c5f75c197f04f37d1a0c124c32c9a084
07/05/2022 16:29:29 - INFO - pytorch_pretrained_bert.tokenization -   loading vocabulary file https://s3.amazonaws.com/models.huggingface.co/bert/bert-base-uncased-vocab.txt from cache at /root/.pytorch_pretrained_bert/26bc1ad6c0ac742e9b52263248f6d0f00068293b33709fae12320c0e35ccfbbb.542ce4285a40d23a559526243235df47c5f75c197f04f37d1a0c124c32c9a084
07/05/2022 16:29:29 - INFO - pytorch_pretrained_bert.tokenization -   loading vocabulary file https://s3.amazonaws.com/models.huggingface.co/bert/bert-base-uncased-vocab.txt from cache at /root/.pytorch_pretrained_bert/26bc1ad6c0ac742e9b52263248f6d0f00068293b33709fae12320c0e35ccfbbb.542ce4285a40d23a559526243235df47c5f75c197f04f37d1a0c124c32c9a084
[2022-07-05 16:29:29,866] [INFO] [distributed.py:48:init_distributed] Initializing torch distributed with backend: nccl
07/05/2022 16:29:29 - INFO - root -   Added key: store_based_barrier_key:1 to store for rank: 3
07/05/2022 16:29:30 - INFO - root -   Added key: store_based_barrier_key:1 to store for rank: 1
07/05/2022 16:29:30 - INFO - root -   Added key: store_based_barrier_key:1 to store for rank: 2
07/05/2022 16:29:30 - INFO - root -   Added key: store_based_barrier_key:1 to store for rank: 0
VOCAB SIZE: 30528
VOCAB SIZE: 30528
VOCAB SIZE: 30528
VOCAB SIZE: 30528
07/05/2022 16:29:32 - INFO - nvidia.modelingpreln -   Init BERT pretrain model
07/05/2022 16:29:32 - INFO - nvidia.modelingpreln -   Init BERT pretrain model
07/05/2022 16:29:32 - INFO - nvidia.modelingpreln -   Init BERT pretrain model
07/05/2022 16:29:32 - INFO - nvidia.modelingpreln -   Init BERT pretrain model
[2022-07-05 16:29:33,949] [INFO] [logging.py:69:log_dist] [Rank 0] DeepSpeed info: version=0.6.5, git-hash=unknown, git-branch=unknown
07/05/2022 16:29:37 - INFO - root -   Added key: store_based_barrier_key:2 to store for rank: 2
07/05/2022 16:29:37 - INFO - root -   Added key: store_based_barrier_key:2 to store for rank: 1
07/05/2022 16:29:37 - INFO - root -   Added key: store_based_barrier_key:2 to store for rank: 3
07/05/2022 16:29:37 - INFO - root -   Added key: store_based_barrier_key:2 to store for rank: 0
[2022-07-05 16:29:38,160] [INFO] [engine.py:278:__init__] DeepSpeed Flops Profiler Enabled: False
[2022-07-05 16:29:38,162] [INFO] [engine.py:1100:_configure_optimizer] Using DeepSpeed Optimizer param name adam as basic optimizer
[2022-07-05 16:29:38,171] [INFO] [engine.py:1108:_configure_optimizer] DeepSpeed Basic Optimizer = FusedAdam
[2022-07-05 16:29:38,172] [INFO] [logging.py:69:log_dist] [Rank 0] Creating fp16 optimizer with dynamic loss scale
[2022-07-05 16:29:38,210] [INFO] [logging.py:69:log_dist] [Rank 0] DeepSpeed Final Optimizer = adam
[2022-07-05 16:29:38,210] [INFO] [engine.py:795:_configure_lr_scheduler] DeepSpeed using client LR scheduler
[2022-07-05 16:29:38,210] [INFO] [logging.py:69:log_dist] [Rank 0] DeepSpeed LR Scheduler = None
[2022-07-05 16:29:38,210] [INFO] [logging.py:69:log_dist] [Rank 0] step=0, skipped=0, lr=[0.001, 0.001], mom=[(0.9, 0.999), (0.9, 0.999)]
[2022-07-05 16:29:38,211] [INFO] [config.py:1059:print] DeepSpeedEngine configuration:
[2022-07-05 16:29:38,211] [INFO] [config.py:1063:print]   activation_checkpointing_config  {
    "partition_activations": false,
    "contiguous_memory_optimization": false,
    "cpu_checkpointing": false,
    "number_checkpoints": null,
    "synchronize_checkpoint_boundary": false,
    "profile": false
}
[2022-07-05 16:29:38,211] [INFO] [config.py:1063:print]   aio_config ................... {'block_size': 1048576, 'queue_depth': 8, 'thread_count': 1, 'single_submit': False, 'overlap_events': True}
[2022-07-05 16:29:38,211] [INFO] [config.py:1063:print]   amp_enabled .................. False
[2022-07-05 16:29:38,211] [INFO] [config.py:1063:print]   amp_params ................... False
[2022-07-05 16:29:38,215] [INFO] [config.py:1063:print]   autotuning_config ............ {
    "enabled": false,
    "start_step": null,
    "end_step": null,
    "metric_path": null,
    "arg_mappings": null,
    "metric": "throughput",
    "model_info": null,
    "results_dir": null,
    "exps_dir": null,
    "overwrite": true,
    "fast": true,
    "start_profile_step": 3,
    "end_profile_step": 5,
    "tuner_type": "gridsearch",
    "tuner_early_stopping": 5,
    "tuner_num_trials": 50,
    "model_info_path": null,
    "mp_size": 1,
    "max_train_batch_size": null,
    "min_train_batch_size": 1,
    "max_train_micro_batch_size_per_gpu": 1.024000e+03,
    "min_train_micro_batch_size_per_gpu": 1,
    "num_tuning_micro_batch_sizes": 3
}
[2022-07-05 16:29:38,215] [INFO] [config.py:1063:print]   bfloat16_enabled ............. False
[2022-07-05 16:29:38,215] [INFO] [config.py:1063:print]   checkpoint_tag_validation_enabled  True
[2022-07-05 16:29:38,215] [INFO] [config.py:1063:print]   checkpoint_tag_validation_fail  False
[2022-07-05 16:29:38,215] [INFO] [config.py:1063:print]   communication_data_type ...... None
[2022-07-05 16:29:38,215] [INFO] [config.py:1063:print]   curriculum_enabled ........... False
[2022-07-05 16:29:38,215] [INFO] [config.py:1063:print]   curriculum_params ............ False
[2022-07-05 16:29:38,215] [INFO] [config.py:1063:print]   dataloader_drop_last ......... False
[2022-07-05 16:29:38,215] [INFO] [config.py:1063:print]   disable_allgather ............ False
[2022-07-05 16:29:38,215] [INFO] [config.py:1063:print]   dump_state ................... False
[2022-07-05 16:29:38,216] [INFO] [config.py:1063:print]   dynamic_loss_scale_args ...... None
[2022-07-05 16:29:38,216] [INFO] [config.py:1063:print]   eigenvalue_enabled ........... False
[2022-07-05 16:29:38,216] [INFO] [config.py:1063:print]   eigenvalue_gas_boundary_resolution  1
[2022-07-05 16:29:38,216] [INFO] [config.py:1063:print]   eigenvalue_layer_name ........ bert.encoder.layer
[2022-07-05 16:29:38,216] [INFO] [config.py:1063:print]   eigenvalue_layer_num ......... 0
[2022-07-05 16:29:38,216] [INFO] [config.py:1063:print]   eigenvalue_max_iter .......... 100
[2022-07-05 16:29:38,216] [INFO] [config.py:1063:print]   eigenvalue_stability ......... 1e-06
[2022-07-05 16:29:38,216] [INFO] [config.py:1063:print]   eigenvalue_tol ............... 0.01
[2022-07-05 16:29:38,216] [INFO] [config.py:1063:print]   eigenvalue_verbose ........... False
[2022-07-05 16:29:38,216] [INFO] [config.py:1063:print]   elasticity_enabled ........... False
[2022-07-05 16:29:38,216] [INFO] [config.py:1063:print]   flops_profiler_config ........ {
    "enabled": false,
    "profile_step": 1,
    "module_depth": -1,
    "top_modules": 1,
    "detailed": true,
    "output_file": null
}
[2022-07-05 16:29:38,216] [INFO] [config.py:1063:print]   fp16_enabled ................. True
[2022-07-05 16:29:38,216] [INFO] [config.py:1063:print]   fp16_master_weights_and_gradients  False
[2022-07-05 16:29:38,216] [INFO] [config.py:1063:print]   fp16_mixed_quantize .......... False
[2022-07-05 16:29:38,216] [INFO] [config.py:1063:print]   global_rank .................. 0
[2022-07-05 16:29:38,216] [INFO] [config.py:1063:print]   gradient_accumulation_steps .. 64
[2022-07-05 16:29:38,216] [INFO] [config.py:1063:print]   gradient_clipping ............ 1.0
[2022-07-05 16:29:38,216] [INFO] [config.py:1063:print]   gradient_predivide_factor .... 8
[2022-07-05 16:29:38,216] [INFO] [config.py:1063:print]   initial_dynamic_scale ........ 4294967296
[2022-07-05 16:29:38,216] [INFO] [config.py:1063:print]   loss_scale ................... 0
[2022-07-05 16:29:38,216] [INFO] [config.py:1063:print]   memory_breakdown ............. False
[2022-07-05 16:29:38,216] [INFO] [config.py:1063:print]   optimizer_legacy_fusion ...... False
[2022-07-05 16:29:38,216] [INFO] [config.py:1063:print]   optimizer_name ............... adam
[2022-07-05 16:29:38,216] [INFO] [config.py:1063:print]   optimizer_params ............. {'lr': 0.001, 'weight_decay': 0.01, 'bias_correction': False}
[2022-07-05 16:29:38,216] [INFO] [config.py:1063:print]   pipeline ..................... {'stages': 'auto', 'partition': 'best', 'seed_layers': False, 'activation_checkpoint_interval': 0}
[2022-07-05 16:29:38,216] [INFO] [config.py:1063:print]   pld_enabled .................. False
[2022-07-05 16:29:38,216] [INFO] [config.py:1063:print]   pld_params ................... False
[2022-07-05 16:29:38,216] [INFO] [config.py:1063:print]   prescale_gradients ........... True
[2022-07-05 16:29:38,217] [INFO] [config.py:1063:print]   quantize_change_rate ......... 0.001
[2022-07-05 16:29:38,217] [INFO] [config.py:1063:print]   quantize_groups .............. 1
[2022-07-05 16:29:38,217] [INFO] [config.py:1063:print]   quantize_offset .............. 1000
[2022-07-05 16:29:38,217] [INFO] [config.py:1063:print]   quantize_period .............. 1000
[2022-07-05 16:29:38,217] [INFO] [config.py:1063:print]   quantize_rounding ............ 0
[2022-07-05 16:29:38,217] [INFO] [config.py:1063:print]   quantize_start_bits .......... 16
[2022-07-05 16:29:38,217] [INFO] [config.py:1063:print]   quantize_target_bits ......... 8
[2022-07-05 16:29:38,217] [INFO] [config.py:1063:print]   quantize_training_enabled .... False
[2022-07-05 16:29:38,217] [INFO] [config.py:1063:print]   quantize_type ................ 0
[2022-07-05 16:29:38,217] [INFO] [config.py:1063:print]   quantize_verbose ............. False
[2022-07-05 16:29:38,217] [INFO] [config.py:1063:print]   scheduler_name ............... None
[2022-07-05 16:29:38,217] [INFO] [config.py:1063:print]   scheduler_params ............. None
[2022-07-05 16:29:38,217] [INFO] [config.py:1063:print]   sparse_attention ............. None
[2022-07-05 16:29:38,217] [INFO] [config.py:1063:print]   sparse_gradients_enabled ..... False
[2022-07-05 16:29:38,217] [INFO] [config.py:1063:print]   steps_per_print .............. 1000
[2022-07-05 16:29:38,217] [INFO] [config.py:1063:print]   tensorboard_enabled .......... False
[2022-07-05 16:29:38,217] [INFO] [config.py:1063:print]   tensorboard_job_name ......... DeepSpeedJobName
[2022-07-05 16:29:38,217] [INFO] [config.py:1063:print]   tensorboard_output_path ......
[2022-07-05 16:29:38,217] [INFO] [config.py:1063:print]   train_batch_size ............. 4096
[2022-07-05 16:29:38,217] [INFO] [config.py:1063:print]   train_micro_batch_size_per_gpu  16
[2022-07-05 16:29:38,217] [INFO] [config.py:1063:print]   use_quantizer_kernel ......... False
[2022-07-05 16:29:38,217] [INFO] [config.py:1063:print]   wall_clock_breakdown ......... False
[2022-07-05 16:29:38,217] [INFO] [config.py:1063:print]   world_size ................... 4
[2022-07-05 16:29:38,217] [INFO] [config.py:1063:print]   zero_allow_untested_optimizer  False
[2022-07-05 16:29:38,217] [INFO] [config.py:1063:print]   zero_config .................. {
    "stage": 0,
    "contiguous_gradients": true,
    "reduce_scatter": true,
    "reduce_bucket_size": 5.000000e+08,
    "allgather_partitions": true,
    "allgather_bucket_size": 5.000000e+08,
    "overlap_comm": false,
    "load_from_fp32_weights": true,
    "elastic_checkpoint": false,
    "offload_param": null,
    "offload_optimizer": null,
    "sub_group_size": 1.000000e+09,
    "prefetch_bucket_size": 5.000000e+07,
    "param_persistence_threshold": 1.000000e+05,
    "max_live_parameters": 1.000000e+09,
    "max_reuse_distance": 1.000000e+09,
    "gather_16bit_weights_on_model_save": false,
    "ignore_unused_parameters": true,
    "round_robin_gradients": false,
    "legacy_stage1": false
}
[2022-07-05 16:29:38,217] [INFO] [config.py:1063:print]   zero_enabled ................. False
[2022-07-05 16:29:38,218] [INFO] [config.py:1063:print]   zero_optimization_stage ...... 0
[2022-07-05 16:29:38,218] [INFO] [config.py:1065:print]   json = {
    "train_batch_size": 4.096000e+03,
    "train_micro_batch_size_per_gpu": 16,
    "steps_per_print": 1000,
    "prescale_gradients": true,
    "gradient_predivide_factor": 8,
    "optimizer": {
        "type": "Adam",
        "params": {
            "lr": 0.001,
            "weight_decay": 0.01,
            "bias_correction": false
        }
    },
    "gradient_clipping": 1.0,
    "wall_clock_breakdown": false,
    "fp16": {
        "enabled": true,
        "loss_scale": 0
    }
}
07/05/2022 16:29:38 - INFO - turing.logger -   NvidiaBertDatasetProvider - Initialization:  num_files = 256
07/05/2022 16:29:38 - INFO - turing.logger -   Training Epoch: 1
07/05/2022 16:29:38 - INFO - turing.logger -   worker-0: begin epoch 1 current_sample_count 0 shard_length 25609 global_data_samples 0
  4%|█████████▍                                                                                                                                                                                                                             | 63/1533 [00:05<01:08, 21.45it/s][2022-07-05 16:29:43,730] [INFO] [fused_optimizer.py:382:_update_scale]
Grad overflow on iteration 0
[2022-07-05 16:29:43,730] [INFO] [fused_optimizer.py:382:_update_scale]
Grad overflow on iteration 0
[2022-07-05 16:29:43,730] [INFO] [fused_optimizer.py:382:_update_scale]
Grad overflow on iteration 0
[2022-07-05 16:29:43,730] [INFO] [fused_optimizer.py:382:_update_scale]
Grad overflow on iteration 0
[2022-07-05 16:29:43,730] [INFO] [fused_optimizer.py:383:_update_scale] Reducing dynamic loss scale from 4294967296 to 2147483648.0
[2022-07-05 16:29:43,730] [INFO] [fused_optimizer.py:383:_update_scale] Reducing dynamic loss scale from 4294967296 to 2147483648.0
[2022-07-05 16:29:43,730] [INFO] [fused_optimizer.py:383:_update_scale] Reducing dynamic loss scale from 4294967296 to 2147483648.0
[2022-07-05 16:29:43,730] [INFO] [fused_optimizer.py:383:_update_scale] Reducing dynamic loss scale from 4294967296 to 2147483648.0
[2022-07-05 16:29:43,730] [INFO] [logging.py:69:log_dist] [Rank 0] Overflow detected. Skipping step. Attempted loss scale: 4294967296, reducing to 2147483648.0
  8%|███████████████████                                                                                                                                                                                                                   | 126/1523 [00:08<01:04, 21.53it/s][2022-07-05 16:29:46,796] [INFO] [fused_optimizer.py:382:_update_scale]
Grad overflow on iteration 1
[2022-07-05 16:29:46,796] [INFO] [fused_optimizer.py:382:_update_scale]
Grad overflow on iteration 1
[2022-07-05 16:29:46,796] [INFO] [fused_optimizer.py:382:_update_scale]
Grad overflow on iteration 1
[2022-07-05 16:29:46,796] [INFO] [fused_optimizer.py:383:_update_scale] Reducing dynamic loss scale from 2147483648.0 to 1073741824.0
[2022-07-05 16:29:46,796] [INFO] [fused_optimizer.py:383:_update_scale] Reducing dynamic loss scale from 2147483648.0 to 1073741824.0
[2022-07-05 16:29:46,796] [INFO] [fused_optimizer.py:382:_update_scale]
Grad overflow on iteration 1
[2022-07-05 16:29:46,796] [INFO] [fused_optimizer.py:383:_update_scale] Reducing dynamic loss scale from 2147483648.0 to 1073741824.0
[2022-07-05 16:29:46,796] [INFO] [fused_optimizer.py:383:_update_scale] Reducing dynamic loss scale from 2147483648.0 to 1073741824.0
[2022-07-05 16:29:46,796] [INFO] [logging.py:69:log_dist] [Rank 0] Overflow detected. Skipping step. Attempted loss scale: 2147483648.0, reducing to 1073741824.0
 12%|████████████████████████████▎                                                                                                                                                                                                         | 189/1533 [00:11<01:02, 21.49it/s][2022-07-05 16:29:49,802] [INFO] [fused_optimizer.py:382:_update_scale]
Grad overflow on iteration 2
[2022-07-05 16:29:49,802] [INFO] [fused_optimizer.py:383:_update_scale] Reducing dynamic loss scale from 1073741824.0 to 536870912.0
[2022-07-05 16:29:49,802] [INFO] [fused_optimizer.py:382:_update_scale]
Grad overflow on iteration 2
[2022-07-05 16:29:49,803] [INFO] [logging.py:69:log_dist] [Rank 0] Overflow detected. Skipping step. Attempted loss scale: 1073741824.0, reducing to 536870912.0
[2022-07-05 16:29:49,802] [INFO] [fused_optimizer.py:382:_update_scale]
Grad overflow on iteration 2
[2022-07-05 16:29:49,803] [INFO] [fused_optimizer.py:383:_update_scale] Reducing dynamic loss scale from 1073741824.0 to 536870912.0
[2022-07-05 16:29:49,803] [INFO] [fused_optimizer.py:383:_update_scale] Reducing dynamic loss scale from 1073741824.0 to 536870912.0
[2022-07-05 16:29:49,802] [INFO] [fused_optimizer.py:382:_update_scale]
Grad overflow on iteration 2
[2022-07-05 16:29:49,803] [INFO] [fused_optimizer.py:383:_update_scale] Reducing dynamic loss scale from 1073741824.0 to 536870912.0
 17%|██████████████████████████████████████▎                                                                                                                                                                                               | 255/1533 [00:14<00:59, 21.47it/s][2022-07-05 16:29:52,803] [INFO] [fused_optimizer.py:382:_update_scale]
Grad overflow on iteration 3
[2022-07-05 16:29:52,803] [INFO] [fused_optimizer.py:382:_update_scale]
Grad overflow on iteration 3
[2022-07-05 16:29:52,803] [INFO] [fused_optimizer.py:382:_update_scale]
Grad overflow on iteration 3
[2022-07-05 16:29:52,803] [INFO] [fused_optimizer.py:383:_update_scale] Reducing dynamic loss scale from 536870912.0 to 268435456.0
[2022-07-05 16:29:52,803] [INFO] [fused_optimizer.py:383:_update_scale] Reducing dynamic loss scale from 536870912.0 to 268435456.0
[2022-07-05 16:29:52,803] [INFO] [fused_optimizer.py:383:_update_scale] Reducing dynamic loss scale from 536870912.0 to 268435456.0
[2022-07-05 16:29:52,803] [INFO] [logging.py:69:log_dist] [Rank 0] Overflow detected. Skipping step. Attempted loss scale: 536870912.0, reducing to 268435456.0
[2022-07-05 16:29:52,803] [INFO] [fused_optimizer.py:382:_update_scale]
Grad overflow on iteration 3
[2022-07-05 16:29:52,804] [INFO] [fused_optimizer.py:383:_update_scale] Reducing dynamic loss scale from 536870912.0 to 268435456.0
 21%|███████████████████████████████████████████████▋                                                                                                                                                                                      | 318/1533 [00:17<00:56, 21.51it/s][2022-07-05 16:29:55,795] [INFO] [fused_optimizer.py:382:_update_scale]
Grad overflow on iteration 4
[2022-07-05 16:29:55,795] [INFO] [fused_optimizer.py:382:_update_scale]
Grad overflow on iteration 4
[2022-07-05 16:29:55,795] [INFO] [fused_optimizer.py:382:_update_scale]
Grad overflow on iteration 4
[2022-07-05 16:29:55,795] [INFO] [fused_optimizer.py:382:_update_scale]
Grad overflow on iteration 4
[2022-07-05 16:29:55,795] [INFO] [fused_optimizer.py:383:_update_scale] Reducing dynamic loss scale from 268435456.0 to 134217728.0
[2022-07-05 16:29:55,795] [INFO] [fused_optimizer.py:383:_update_scale] Reducing dynamic loss scale from 268435456.0 to 134217728.0
[2022-07-05 16:29:55,795] [INFO] [fused_optimizer.py:383:_update_scale] Reducing dynamic loss scale from 268435456.0 to 134217728.0
[2022-07-05 16:29:55,795] [INFO] [fused_optimizer.py:383:_update_scale] Reducing dynamic loss scale from 268435456.0 to 134217728.0
[2022-07-05 16:29:55,795] [INFO] [logging.py:69:log_dist] [Rank 0] Overflow detected. Skipping step. Attempted loss scale: 268435456.0, reducing to 134217728.0
 25%|█████████████████████████████████████████████████████████▏                                                                                                                                                                            | 381/1533 [00:20<00:53, 21.46it/s][2022-07-05 16:29:58,793] [INFO] [fused_optimizer.py:382:_update_scale]
Grad overflow on iteration 5
[2022-07-05 16:29:58,793] [INFO] [fused_optimizer.py:382:_update_scale]
Grad overflow on iteration 5
[2022-07-05 16:29:58,793] [INFO] [fused_optimizer.py:382:_update_scale]
Grad overflow on iteration 5
[2022-07-05 16:29:58,793] [INFO] [fused_optimizer.py:382:_update_scale]
Grad overflow on iteration 5
[2022-07-05 16:29:58,793] [INFO] [fused_optimizer.py:383:_update_scale] Reducing dynamic loss scale from 134217728.0 to 67108864.0
[2022-07-05 16:29:58,793] [INFO] [fused_optimizer.py:383:_update_scale] Reducing dynamic loss scale from 134217728.0 to 67108864.0
[2022-07-05 16:29:58,793] [INFO] [fused_optimizer.py:383:_update_scale] Reducing dynamic loss scale from 134217728.0 to 67108864.0
[2022-07-05 16:29:58,793] [INFO] [fused_optimizer.py:383:_update_scale] Reducing dynamic loss scale from 134217728.0 to 67108864.0
[2022-07-05 16:29:58,793] [INFO] [logging.py:69:log_dist] [Rank 0] Overflow detected. Skipping step. Attempted loss scale: 134217728.0, reducing to 67108864.0
 29%|███████████████████████████████████████████████████████████████████                                                                                                                                                                   | 447/1533 [00:23<00:51, 21.27it/s][2022-07-05 16:30:01,798] [INFO] [fused_optimizer.py:382:_update_scale]
Grad overflow on iteration 6
[2022-07-05 16:30:01,798] [INFO] [fused_optimizer.py:382:_update_scale]
Grad overflow on iteration 6
[2022-07-05 16:30:01,798] [INFO] [fused_optimizer.py:383:_update_scale] Reducing dynamic loss scale from 67108864.0 to 33554432.0
[2022-07-05 16:30:01,798] [INFO] [fused_optimizer.py:382:_update_scale]
Grad overflow on iteration 6
[2022-07-05 16:30:01,798] [INFO] [fused_optimizer.py:383:_update_scale] Reducing dynamic loss scale from 67108864.0 to 33554432.0
[2022-07-05 16:30:01,798] [INFO] [fused_optimizer.py:382:_update_scale]
Grad overflow on iteration 6
[2022-07-05 16:30:01,798] [INFO] [fused_optimizer.py:383:_update_scale] Reducing dynamic loss scale from 67108864.0 to 33554432.0
[2022-07-05 16:30:01,798] [INFO] [fused_optimizer.py:383:_update_scale] Reducing dynamic loss scale from 67108864.0 to 33554432.0
[2022-07-05 16:30:01,798] [INFO] [logging.py:69:log_dist] [Rank 0] Overflow detected. Skipping step. Attempted loss scale: 67108864.0, reducing to 33554432.0
 33%|█████████████████████████████████████████████████████████████████████████████                                                                                                                                                         | 510/1523 [00:26<00:46, 21.57it/s][2022-07-05 16:30:04,804] [INFO] [fused_optimizer.py:382:_update_scale]
Grad overflow on iteration 7
[2022-07-05 16:30:04,805] [INFO] [fused_optimizer.py:382:_update_scale]
Grad overflow on iteration 7
[2022-07-05 16:30:04,805] [INFO] [fused_optimizer.py:382:_update_scale]
Grad overflow on iteration 7
[2022-07-05 16:30:04,805] [INFO] [fused_optimizer.py:383:_update_scale] Reducing dynamic loss scale from 33554432.0 to 16777216.0
[2022-07-05 16:30:04,805] [INFO] [fused_optimizer.py:383:_update_scale] Reducing dynamic loss scale from 33554432.0 to 16777216.0
[2022-07-05 16:30:04,805] [INFO] [fused_optimizer.py:383:_update_scale] Reducing dynamic loss scale from 33554432.0 to 16777216.0
[2022-07-05 16:30:04,805] [INFO] [fused_optimizer.py:382:_update_scale]
Grad overflow on iteration 7
[2022-07-05 16:30:04,805] [INFO] [logging.py:69:log_dist] [Rank 0] Overflow detected. Skipping step. Attempted loss scale: 33554432.0, reducing to 16777216.0
[2022-07-05 16:30:04,805] [INFO] [fused_optimizer.py:383:_update_scale] Reducing dynamic loss scale from 33554432.0 to 16777216.0
 37%|█████████████████████████████████████████████████████████████████████████████████████▉                                                                                                                                                | 573/1533 [00:29<00:44, 21.45it/s][2022-07-05 16:30:07,802] [INFO] [fused_optimizer.py:382:_update_scale]
Grad overflow on iteration 8
[2022-07-05 16:30:07,802] [INFO] [fused_optimizer.py:382:_update_scale]
Grad overflow on iteration 8
[2022-07-05 16:30:07,802] [INFO] [fused_optimizer.py:382:_update_scale]
Grad overflow on iteration 8
[2022-07-05 16:30:07,802] [INFO] [fused_optimizer.py:383:_update_scale] Reducing dynamic loss scale from 16777216.0 to 8388608.0
[2022-07-05 16:30:07,802] [INFO] [fused_optimizer.py:383:_update_scale] Reducing dynamic loss scale from 16777216.0 to 8388608.0
[2022-07-05 16:30:07,802] [INFO] [fused_optimizer.py:383:_update_scale] Reducing dynamic loss scale from 16777216.0 to 8388608.0
[2022-07-05 16:30:07,802] [INFO] [logging.py:69:log_dist] [Rank 0] Overflow detected. Skipping step. Attempted loss scale: 16777216.0, reducing to 8388608.0
[2022-07-05 16:30:07,802] [INFO] [fused_optimizer.py:382:_update_scale]
Grad overflow on iteration 8
[2022-07-05 16:30:07,802] [INFO] [fused_optimizer.py:383:_update_scale] Reducing dynamic loss scale from 16777216.0 to 8388608.0
 42%|████████████████████████████████████████████████████████████████████████████████████████████████▌                                                                                                                                     | 639/1523 [00:32<00:41, 21.56it/s][2022-07-05 16:30:10,796] [INFO] [fused_optimizer.py:382:_update_scale]
Grad overflow on iteration 9
[2022-07-05 16:30:10,796] [INFO] [fused_optimizer.py:382:_update_scale]
Grad overflow on iteration 9
[2022-07-05 16:30:10,796] [INFO] [fused_optimizer.py:382:_update_scale]
Grad overflow on iteration 9
[2022-07-05 16:30:10,796] [INFO] [fused_optimizer.py:382:_update_scale]
Grad overflow on iteration 9
[2022-07-05 16:30:10,796] [INFO] [fused_optimizer.py:383:_update_scale] Reducing dynamic loss scale from 8388608.0 to 4194304.0
[2022-07-05 16:30:10,796] [INFO] [fused_optimizer.py:383:_update_scale] Reducing dynamic loss scale from 8388608.0 to 4194304.0
[2022-07-05 16:30:10,797] [INFO] [fused_optimizer.py:383:_update_scale] Reducing dynamic loss scale from 8388608.0 to 4194304.0
[2022-07-05 16:30:10,797] [INFO] [fused_optimizer.py:383:_update_scale] Reducing dynamic loss scale from 8388608.0 to 4194304.0
[2022-07-05 16:30:10,797] [INFO] [logging.py:69:log_dist] [Rank 0] Overflow detected. Skipping step. Attempted loss scale: 8388608.0, reducing to 4194304.0
 46%|█████████████████████████████████████████████████████████████████████████████████████████████████████████▊                                                                                                                            | 702/1526 [00:35<00:38, 21.48it/s][2022-07-05 16:30:13,787] [INFO] [fused_optimizer.py:382:_update_scale]
Grad overflow on iteration 10
[2022-07-05 16:30:13,787] [INFO] [fused_optimizer.py:382:_update_scale]
Grad overflow on iteration 10
[2022-07-05 16:30:13,787] [INFO] [fused_optimizer.py:382:_update_scale]
Grad overflow on iteration 10
[2022-07-05 16:30:13,787] [INFO] [fused_optimizer.py:382:_update_scale]
Grad overflow on iteration 10
[2022-07-05 16:30:13,787] [INFO] [fused_optimizer.py:383:_update_scale] Reducing dynamic loss scale from 4194304.0 to 2097152.0
[2022-07-05 16:30:13,787] [INFO] [fused_optimizer.py:383:_update_scale] Reducing dynamic loss scale from 4194304.0 to 2097152.0
[2022-07-05 16:30:13,787] [INFO] [fused_optimizer.py:383:_update_scale] Reducing dynamic loss scale from 4194304.0 to 2097152.0
[2022-07-05 16:30:13,787] [INFO] [logging.py:69:log_dist] [Rank 0] Overflow detected. Skipping step. Attempted loss scale: 4194304.0, reducing to 2097152.0
[2022-07-05 16:30:13,787] [INFO] [fused_optimizer.py:383:_update_scale] Reducing dynamic loss scale from 4194304.0 to 2097152.0
 50%|██████████████████████████████████████████████████████████████████████████████████████████████████████████████████▊                                                                                                                   | 765/1533 [00:38<00:35, 21.46it/s][2022-07-05 16:30:16,787] [INFO] [fused_optimizer.py:382:_update_scale]
Grad overflow on iteration 11
[2022-07-05 16:30:16,787] [INFO] [fused_optimizer.py:382:_update_scale]
Grad overflow on iteration 11
[2022-07-05 16:30:16,787] [INFO] [fused_optimizer.py:382:_update_scale]
Grad overflow on iteration 11
[2022-07-05 16:30:16,787] [INFO] [fused_optimizer.py:383:_update_scale] Reducing dynamic loss scale from 2097152.0 to 1048576.0
[2022-07-05 16:30:16,787] [INFO] [fused_optimizer.py:383:_update_scale] Reducing dynamic loss scale from 2097152.0 to 1048576.0
[2022-07-05 16:30:16,787] [INFO] [fused_optimizer.py:382:_update_scale]
Grad overflow on iteration 11
[2022-07-05 16:30:16,787] [INFO] [fused_optimizer.py:383:_update_scale] Reducing dynamic loss scale from 2097152.0 to 1048576.0
[2022-07-05 16:30:16,787] [INFO] [logging.py:69:log_dist] [Rank 0] Overflow detected. Skipping step. Attempted loss scale: 2097152.0, reducing to 1048576.0
[2022-07-05 16:30:16,787] [INFO] [fused_optimizer.py:383:_update_scale] Reducing dynamic loss scale from 2097152.0 to 1048576.0
 52%|███████████████████████████████████████████████████████████████████████████████████████████████████████████████████████▍                                                                                                              | 831/1601 [00:41<00:35, 21.60it/s][2022-07-05 16:30:19,883] [INFO] [fused_optimizer.py:382:_update_scale]
Grad overflow on iteration 12
[2022-07-05 16:30:19,883] [INFO] [fused_optimizer.py:382:_update_scale]
Grad overflow on iteration 12
[2022-07-05 16:30:19,883] [INFO] [fused_optimizer.py:382:_update_scale]
Grad overflow on iteration 12
[2022-07-05 16:30:19,883] [INFO] [fused_optimizer.py:382:_update_scale]
Grad overflow on iteration 12
[2022-07-05 16:30:19,883] [INFO] [fused_optimizer.py:383:_update_scale] Reducing dynamic loss scale from 1048576.0 to 524288.0
[2022-07-05 16:30:19,883] [INFO] [fused_optimizer.py:383:_update_scale] Reducing dynamic loss scale from 1048576.0 to 524288.0
[2022-07-05 16:30:19,883] [INFO] [fused_optimizer.py:383:_update_scale] Reducing dynamic loss scale from 1048576.0 to 524288.0
[2022-07-05 16:30:19,883] [INFO] [fused_optimizer.py:383:_update_scale] Reducing dynamic loss scale from 1048576.0 to 524288.0
[2022-07-05 16:30:19,883] [INFO] [logging.py:69:log_dist] [Rank 0] Overflow detected. Skipping step. Attempted loss scale: 1048576.0, reducing to 524288.0
 59%|███████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████                                                                                               | 894/1523 [00:44<00:29, 21.44it/s][2022-07-05 16:30:22,874] [INFO] [fused_optimizer.py:382:_update_scale]
Grad overflow on iteration 13
[2022-07-05 16:30:22,874] [INFO] [fused_optimizer.py:382:_update_scale]
Grad overflow on iteration 13
[2022-07-05 16:30:22,874] [INFO] [fused_optimizer.py:382:_update_scale]
Grad overflow on iteration 13
[2022-07-05 16:30:22,874] [INFO] [fused_optimizer.py:382:_update_scale]
Grad overflow on iteration 13
[2022-07-05 16:30:22,874] [INFO] [fused_optimizer.py:383:_update_scale] Reducing dynamic loss scale from 524288.0 to 262144.0
[2022-07-05 16:30:22,874] [INFO] [fused_optimizer.py:383:_update_scale] Reducing dynamic loss scale from 524288.0 to 262144.0
[2022-07-05 16:30:22,874] [INFO] [fused_optimizer.py:383:_update_scale] Reducing dynamic loss scale from 524288.0 to 262144.0
[2022-07-05 16:30:22,874] [INFO] [fused_optimizer.py:383:_update_scale] Reducing dynamic loss scale from 524288.0 to 262144.0
[2022-07-05 16:30:22,874] [INFO] [logging.py:69:log_dist] [Rank 0] Overflow detected. Skipping step. Attempted loss scale: 524288.0, reducing to 262144.0
 62%|███████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████▌                                                                                      | 999/1601 [00:49<00:29, 20.57it/s][2022-07-05 16:30:27,753] [INFO] [timer.py:193:stop] 0/1000, SamplesPerSec=1418.7156532263152, MemAllocated=1.66GB, MaxMemAllocated=2.92GB
 88%|█████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████▋                           | 1341/1523 [01:05<00:08, 21.54it/s] At step 1280, the throughput is 1306.867328 Samples/s
 92%|██████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████▏                  | 1407/1533 [01:08<00:05, 21.46it/s][2022-07-05 16:30:46,975] [INFO] [fused_optimizer.py:382:_update_scale]
Grad overflow on iteration 21
[2022-07-05 16:30:46,975] [INFO] [fused_optimizer.py:382:_update_scale]
Grad overflow on iteration 21
[2022-07-05 16:30:46,975] [INFO] [fused_optimizer.py:382:_update_scale]
Grad overflow on iteration 21
[2022-07-05 16:30:46,975] [INFO] [fused_optimizer.py:382:_update_scale]
Grad overflow on iteration 21
[2022-07-05 16:30:46,975] [INFO] [fused_optimizer.py:383:_update_scale] Reducing dynamic loss scale from 262144.0 to 131072.0
[2022-07-05 16:30:46,975] [INFO] [fused_optimizer.py:383:_update_scale] Reducing dynamic loss scale from 262144.0 to 131072.0
[2022-07-05 16:30:46,975] [INFO] [fused_optimizer.py:383:_update_scale] Reducing dynamic loss scale from 262144.0 to 131072.0
[2022-07-05 16:30:46,975] [INFO] [logging.py:69:log_dist] [Rank 0] Overflow detected. Skipping step. Attempted loss scale: 262144.0, reducing to 131072.0
[2022-07-05 16:30:46,975] [INFO] [fused_optimizer.py:383:_update_scale] Reducing dynamic loss scale from 262144.0 to 131072.0
100%|█████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████| 1523/1523 [01:14<00:00, 20.39it/s]
100%|█████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████| 1526/1526 [01:14<00:00, 20.41it/s]
100%|█████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████| 1533/1533 [01:15<00:00, 20.40it/s]
 96%|███████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████▎         | 1533/1601 [01:29<00:03, 20.53it/s]
```




After the script gets frozen, this is my GPU status with `nvidia-smi`.
```
Tue Jul  5 16:37:34 2022
+-----------------------------------------------------------------------------+
| NVIDIA-SMI 450.102.04   Driver Version: 450.102.04   CUDA Version: 11.1     |
|-------------------------------+----------------------+----------------------+
| GPU  Name        Persistence-M| Bus-Id        Disp.A | Volatile Uncorr. ECC |
| Fan  Temp  Perf  Pwr:Usage/Cap|         Memory-Usage | GPU-Util  Compute M. |
|                               |                      |               MIG M. |
|===============================+======================+======================|
|   0  Tesla V100-SXM2...  On   | 00000000:1A:00.0 Off |                    0 |
| N/A   44C    P0    71W / 300W |   4890MiB / 32510MiB |    100%      Default |
|                               |                      |                  N/A |
+-------------------------------+----------------------+----------------------+
|   1  Tesla V100-SXM2...  On   | 00000000:1C:00.0 Off |                    0 |
| N/A   36C    P0    58W / 300W |   4860MiB / 32510MiB |      0%      Default |
|                               |                      |                  N/A |
+-------------------------------+----------------------+----------------------+
|   2  Tesla V100-SXM2...  On   | 00000000:1D:00.0 Off |                    0 |
| N/A   38C    P0    59W / 300W |   4918MiB / 32510MiB |      0%      Default |
|                               |                      |                  N/A |
+-------------------------------+----------------------+----------------------+
|   3  Tesla V100-SXM2...  On   | 00000000:1E:00.0 Off |                    0 |
| N/A   40C    P0    57W / 300W |   4864MiB / 32510MiB |      0%      Default |
|                               |                      |                  N/A |
+-------------------------------+----------------------+----------------------+

+-----------------------------------------------------------------------------+
| Processes:                                                                  |
|  GPU   GI   CI        PID   Type   Process name                  GPU Memory |
|        ID   ID                                                   Usage      |
|=============================================================================|
+-----------------------------------------------------------------------------+

```



And this is my server monitoring log with `top`.
```
top - 16:44:52 up 379 days,  5:56,  3 users,  load average: 2.73, 1.99, 1.48
Tasks:  30 total,   2 running,  28 sleeping,   0 stopped,   0 zombie
%Cpu(s):  1.3 us,  0.8 sy,  0.0 ni, 97.9 id,  0.0 wa,  0.0 hi,  0.0 si,  0.0 st
KiB Mem : 52773324+total,  2652580 free, 17675660 used, 50740499+buff/cache
KiB Swap: 10485756 total, 10091516 free,   394240 used. 50642121+avail Mem

  PID USER      PR  NI    VIRT    RES    SHR S  %CPU %MEM     TIME+ COMMAND
 5418 root      20   0 31.596g 3.684g 1.294g R 100.7  0.7   2:06.78 python
 5621 root      20   0   25656   4356   3600 S   0.3  0.0   0:00.28 htop
    1 root      20   0    4648   1548   1472 S   0.0  0.0   0:00.00 sh
   14 root      20   0   72308   6072   5324 S   0.0  0.0   0:00.00 sshd
   15 root      20   0  103864   6644   5680 S   0.0  0.0   0:00.28 sshd
   26 root      20   0   20448   3944   3224 S   0.0  0.0   0:00.06 bash
  208 root      20   0  103864   7028   6020 S   0.0  0.0   0:00.12 sshd
  219 root      20   0   20316   4052   3460 S   0.0  0.0   0:00.00 bash
 1427 root      20   0    4644    784    716 S   0.0  0.0   0:00.00 sh
 1437 root      20   0  960944  81640  35984 S   0.0  0.0   0:04.00 node
 1474 root      20   0  930324  46168  32728 S   0.0  0.0   0:00.39 node
 1615 root      20   0  104580   7604   5856 S   0.0  0.0   0:00.04 sshd
 1626 root      20   0   20056   3512   3184 S   0.0  0.0   0:00.00 bash
 1630 root      20   0   12128   3896   3028 S   0.0  0.0   0:00.01 bash
 1685 root      20   0  916940  93648  37768 S   0.0  0.0   0:02.15 node
 1696 root      20   0  846480  41788  32484 S   0.0  0.0   0:00.19 node
 1817 root      20   0  601328  40972  29380 S   0.0  0.0   0:00.20 node
 5406 root      20   0    4648    836    760 S   0.0  0.0   0:00.00 sh
 5407 root      20   0 21.128g 999856 714192 S   0.0  0.2   0:01.16 deepspeed
 5413 root      20   0 4918072 995904 711312 S   0.0  0.2   0:01.02 python
 5419 root      20   0 31.314g 3.692g 1.293g S   0.0  0.7   1:33.58 python
 5420 root      20   0 31.250g 3.691g 1.293g S   0.0  0.7   1:38.41 python
 5421 root      20   0 31.251g 3.688g 1.293g S   0.0  0.7   1:39.08 python
 5435 root      20   0   38288   3600   3136 R   0.0  0.0   0:00.07 top
 5565 root      20   0 29.985g 2.338g 107300 S   0.0  0.5   0:00.21 python
 5568 root      20   0 30.016g 2.337g 107228 S   0.0  0.5   0:00.21 python
 5573 root      20   0 30.026g 2.348g 107472 S   0.0  0.5   0:00.22 python
 5577 root      20   0 30.255g 2.343g 107624 S   0.0  0.5   0:00.20 python
 5598 root      20   0  103864   6928   5920 S   0.0  0.0   0:00.01 sshd
 5609 root      20   0   20316   4048   3456 S   0.0  0.0   0:00.00 bash

```


I was struggling for a while with this issue, but got no progress to solve this. Can I get some advice about my issue?

**Comment by mrwyattii** [comment]
@tjdgh0715 thank you for using DeepSpeed and this detailed write up! I want to try reproducing this issue on my side as a first step toward debugging. Could you share the exact command you used to launch the [deepspeed_train.py](https://github.com/microsoft/DeepSpeedExamples/blob/master/bing_bert/deepspeed_train.py) script?

**Comment by tjdgh0715** [comment]
@mrwyattii Of course. This is my code to launch the code. Thank you for your support!

```
#!/bin/bash
N_GPUS=4

deepspeed --num_gpus $N_GPUS \
    /data/private/Layer_Skipping/Progressive_Layer_Dropping/DeepSpeedExamples/bing_bert/deepspeed_train.py \
    --deepspeed \
    --deepspeed_config  /data/private/Layer_Skipping/Progressive_Layer_Dropping/DeepSpeedExamples/data/deepspeed_PLD_base.json \
    --cf /data/private/Layer_Skipping/Progressive_Layer_Dropping/DeepSpeedExamples/data/bert_base.json \
    --max_seq_length 128 \
    --print_steps 100 \
    --use_nvidia_dataset \
    --validation_data_path_prefix /data/private/Layer_Skipping/Progressive_Layer_Dropping/DeepSpeedExamples/data/wikicorpus_en/test \
    --output_dir /data/private/Layer_Skipping/Progressive_Layer_Dropping/DeepSpeedExamples/bert_output/DDP/base

```

**Comment by tjdgh0715** [comment]
@mrwyattii @conglongli I solved it by downgrading the version of DeepSpeed to 0.3.10. Maybe this could be a potential issue at version 0.6.5+.
Thank you for your support!
