### ISSUE TITLE
Illegal memory access with DeepSpeed Inference for RoBERTa-Large

### ISSUE THREAD

**Issue by sayakpaul** [microsoft/DeepSpeed#2086]
**Machine specifications**

* Tesla V100 (1x)
* CUDA 11.0
* transformers==4.20.1
* `ds_report`

```
--------------------------------------------------
DeepSpeed C++/CUDA extension op report
--------------------------------------------------
NOTE: Ops not installed will be just-in-time (JIT) compiled at
      runtime if needed. Op compatibility means that your system
      meet the required dependencies to JIT install the op.
--------------------------------------------------
JIT compiled ops requires ninja
ninja .................. [OKAY]
--------------------------------------------------
op name ................ installed .. compatible
--------------------------------------------------
cpu_adam ............... [NO] ....... [OKAY]
cpu_adagrad ............ [NO] ....... [OKAY]
fused_adam ............. [NO] ....... [OKAY]
fused_lamb ............. [NO] ....... [OKAY]
 [WARNING]  please install triton==1.0.0 if you want to use sparse attention
sparse_attn ............ [NO] ....... [NO]
transformer ............ [NO] ....... [OKAY]
stochastic_transformer . [NO] ....... [OKAY]
 [WARNING]  async_io requires the dev libaio .so object and headers but these were not found.
 [WARNING]  async_io: please install the libaio-dev package with apt
 [WARNING]  If libaio is already installed (perhaps from source), try setting the CFLAGS and LDFLAGS environment variables to where it can be found.
async_io ............... [NO] ....... [NO]
utils .................. [NO] ....... [OKAY]
quantizer .............. [NO] ....... [OKAY]
transformer_inference .. [NO] ....... [OKAY]
--------------------------------------------------
DeepSpeed general environment info:
torch install path ............... ['/opt/conda/lib/python3.7/site-packages/torch']
torch version .................... 1.11.0+cu113
torch cuda version ............... 11.3
torch hip version ................ None
nvcc version ..................... 11.0
deepspeed install path ........... ['/opt/conda/lib/python3.7/site-packages/deepspeed']
deepspeed info ................... 0.6.5, unknown, unknown
deepspeed wheel compiled w. ...... torch 0.0, cuda 0.0
```

**Code**

```py
import os
import time
import deepspeed
import torch
from transformers import pipeline

local_rank = int(os.getenv("LOCAL_RANK", "0"))
world_size = int(os.getenv("WORLD_SIZE", "1"))

fill_mask = pipeline("fill-mask", model="roberta-large", device=local_rank)
fill_mask.model = deepspeed.init_inference(
    fill_mask.model,
    mp_size=world_size,
    dtype=torch.float,
    replace_method="auto",
    replace_with_kernel_inject=True,
)

start_time = time.time()
for _ in range(50):
    string = fill_mask("The goal of life is <mask> and <mask>.")
    if not torch.distributed.is_initialized() or torch.distributed.get_rank() == 0:
        print(string)
end_time = time.time()
print("Time taken: {(end_time - start_time):.2f} seconds.")
```

**Error**

```
Traceback (most recent call last):
  File "inference.py", line 25, in <module>
    string = fill_mask("The goal of life is <mask> and <mask>.")
  File "/opt/conda/lib/python3.7/site-packages/transformers/pipelines/fill_mask.py", line 227, in __call__
    outputs = super().__call__(inputs, **kwargs)
  File "/opt/conda/lib/python3.7/site-packages/transformers/pipelines/base.py", line 1043, in __call__
    return self.run_single(inputs, preprocess_params, forward_params, postprocess_params)
  File "/opt/conda/lib/python3.7/site-packages/transformers/pipelines/base.py", line 1050, in run_single
    model_outputs = self.forward(model_inputs, **forward_params)
  File "/opt/conda/lib/python3.7/site-packages/transformers/pipelines/base.py", line 960, in forward
    model_outputs = self._ensure_tensor_on_device(model_outputs, device=torch.device("cpu"))
  File "/opt/conda/lib/python3.7/site-packages/transformers/pipelines/base.py", line 861, in _ensure_tensor_on_device
    {name: self._ensure_tensor_on_device(tensor, device) for name, tensor in inputs.items()}
  File "/opt/conda/lib/python3.7/site-packages/transformers/pipelines/base.py", line 861, in <dictcomp>
    {name: self._ensure_tensor_on_device(tensor, device) for name, tensor in inputs.items()}
  File "/opt/conda/lib/python3.7/site-packages/transformers/pipelines/base.py", line 874, in _ensure_tensor_on_device
    return inputs.to(device)
RuntimeError: CUDA error: an illegal memory access was encountered
CUDA kernel errors might be asynchronously reported at some other API call,so the stacktrace below might be incorrect.
For debugging consider passing CUDA_LAUNCH_BLOCKING=1.
[2022-07-11 08:42:53,226] [INFO] [launch.py:178:sigkill_handler] Killing subprocess 3940
[2022-07-11 08:42:53,226] [ERROR] [launch.py:184:sigkill_handler] ['/opt/conda/bin/python3.7', '-u', 'inference.py', '--local_rank=0'] exits with return code = 1
```

**Additional logs**

```

[2022-07-11 08:42:36,815] [WARNING] [runner.py:159:fetch_hostfile] Unable to find hostfile, will proceed with training with local resources only.
[2022-07-11 08:42:37,449] [INFO] [runner.py:457:main] cmd = /opt/conda/bin/python3.7 -u -m deepspeed.launcher.launch --world_info=eyJsb2NhbGhvc3QiOiBbMF19 --master_addr=127.0.0.1 --master_port=29500 inference.py
[2022-07-11 08:42:38,205] [INFO] [launch.py:103:main] WORLD INFO DICT: {'localhost': [0]}
[2022-07-11 08:42:38,205] [INFO] [launch.py:110:main] nnodes=1, num_local_procs=1, node_rank=0
[2022-07-11 08:42:38,205] [INFO] [launch.py:122:main] global_rank_mapping=defaultdict(<class 'list'>, {'localhost': [0]})
[2022-07-11 08:42:38,205] [INFO] [launch.py:123:main] dist_world_size=1
[2022-07-11 08:42:38,205] [INFO] [launch.py:125:main] Setting CUDA_VISIBLE_DEVICES=0
[2022-07-11 08:42:51,325] [INFO] [logging.py:69:log_dist] [Rank -1] DeepSpeed info: version=0.6.5, git-hash=unknown, git-branch=unknown
[2022-07-11 08:42:51,325] [INFO] [engine.py:199:_init_quantization_setting] quantize_bits = 8 mlp_extra_grouping = False, quantize_groups = 1
Installed CUDA version 11.0 does not match the version torch was compiled with 11.3 but since the APIs are compatible, accepting this combination
Using /home/jupyter/.cache/torch_extensions/py37_cu113 as PyTorch extensions root...
Detected CUDA files, patching ldflags
Emitting ninja build file /home/jupyter/.cache/torch_extensions/py37_cu113/transformer_inference/build.ninja...
Building extension module transformer_inference...
Allowing ninja to set a default number of workers... (overridable by setting the environment variable MAX_JOBS=N)
ninja: no work to do.
Loading extension module transformer_inference...
Time to load transformer_inference op: 0.33134889602661133 seconds
```

**Comment by mrwyattii** [comment]
@sayakpaul I believe this error was corrected in a recent PR. It will be included in the next release (0.6.6). Until that time, you can install DeepSpeed from source to avoid this problem:
`git clone https://github.com/microsoft/DeepSpeed.git && pip install ./DeepSpeed/`
or
`pip install git+https://github.com/microsoft/DeepSpeed.git`

**Comment by sayakpaul** [comment]
@mrwyattii thanks! That did the trick.

Here's a Colab Notebook in case anyone's interested: https://colab.research.google.com/gist/sayakpaul/6e6607e0cde5c8c409cfd4d12d22432d/scratchpad.ipynb. 

Maybe I am mistaken but I would have expected to see some speedup in the DeepSpeed Inference based `pipeline` compared to the regular one. As you would notice in the notebook, it is the not case. What am I missing out on?

**Comment by sayakpaul** [comment]
You were right. 

Here's the updated Colab: https://colab.research.google.com/gist/sayakpaul/9ca8fe1fb620d936241fd6f51a5a2814/scratchpad.ipynb

DS: 0.66 secs
Regular: 2.17 secs
