### ISSUE TITLE
[BUG] deepspeed inference. CUDA out of memory.

### ISSUE THREAD

**Issue by archieCanada** [microsoft/DeepSpeed#2375]
@RezaYazdaniAminabadi

**Describe the bug**
I try to run deepspeed inference for the T0pp transformer model. However, I receive the following Error:

```
RuntimeError: CUDA out of memory. Tried to allocate 160.00 MiB (GPU 0; 31.75 GiB total capacity; 30.99 GiB already allocated; 118.19 MiB free; 30.99 GiB reserved in total by PyTorch) If reserved memory is >> allocated memory try setting max_split_size_mb to avoid fragmentation.  See documentation for Memory Management and PYTORCH_CUDA_ALLOC_CONF
```
The size of the T0pp model is below 50GB. So using 2-3 GPUs with 32 GB each should be enough, but apparently, it is not.

**To Reproduce**
Here is my code:
First, I save the sharded version of this model:
```
from transformers import AutoModelForSeq2SeqLM; \
model = AutoModelForSeq2SeqLM.from_pretrained("bigscience/T0pp")
model.save_pretrained("/path/to/t0pp-sharded", max_shard_size="5GB")
```

Then I run the following script.

```
#Inputs
questionSet = ['question0', 'question1', 'question2']
context = 'Some context'

#installation of the necessary packages
import torch
from transformers import AutoTokenizer, AutoModelForSeq2SeqLM
import os
import deepspeed

#download the model
model_name_token = "bigscience/T0pp"
model_name = "/path/to/t0pp-sharded"

device = torch.device('cuda' if torch.cuda.is_available() else 'cpu')

local_rank = int(os.getenv('LOCAL_RANK', '0'))
world_size = int(os.getenv('WORLD_SIZE', '1'))

tokenizer = AutoTokenizer.from_pretrained(model_name_token)
model = AutoModelForSeq2SeqLM.from_pretrained(model_name)

model = model.to(device=local_rank)

model = deepspeed.init_inference(model,
                                mp_size=world_size,
                                dtype=torch.float,
                                replace_method='auto',
					   replace_with_kernel_inject=True)

#generate answers
answerSet = []
for query in questionSet:
  query_and_docs = "question: {} context: {}".format(query, context)
  model_input = tokenizer(query_and_docs, padding=True, return_tensors="pt")
  generated_answers_encoded = model.generate(input_ids=model_input["input_ids"].to(device=local_rank),
                                           attention_mask=model_input["attention_mask"].to(device=local_rank),
                                           min_length=200,
                                           max_length=400,
                                           do_sample=False,
                                           early_stopping=True,
                                           num_beams=8,
                                           temperature=1.0,
                                           top_k=None,
                                           top_p=None,
                                           eos_token_id=tokenizer.eos_token_id,
                                           no_repeat_ngram_size=3,
                                           num_return_sequences=1)
  answer = tokenizer.batch_decode(generated_answers_encoded, skip_special_tokens=True,clean_up_tokenization_spaces=True)[0]
  answerSet.append(answer)

for i in range(0,len(machineAnswerSet)):
  print(machineAnswerSet[i])
```

**Expected behavior**
I expect to see three generated answers.

**System info (please complete the following information):**
My resources:

I tried two different options:
1) 2 GPUs (Tesla V100-SXM2-32GB), 60 GB CPU RAM per GPU (120 GB CPU RAM total)
1) 3 GPUs (Tesla V100-SXM2-32GB), 60 GB CPU RAM per GPU (180 GB CPU RAM total)

Both times I received the same error.

**Comment by mrwyattii** [comment]
Hi @archieCanada, I'm guessing you are running into the Out of Memory error on this line: `model = model.to(device=local_rank)`?

You can remove this line from your script and it should work. This line is trying to move the entire model to **each** GPU, which explains the OOM error. Please let me know if this fixes it!

**Comment by archieCanada** [comment]
Thank you, @mrwyattii

I tried several options:
1) removing `model = model.to(device=local_rank)` 
2) removing `=local_rank` from two lines which start with  `generated_answers_encoded`
3) combination/variations of 1) and 2)

Nevertheless, I still have the same Error message:

```
    return t.to(device, dtype if t.is_floating_point() or t.is_complex() else None, non_blocking)
RuntimeError: CUDA out of memory. Tried to allocate 160.00 MiB (GPU 1; 31.75 GiB total capacity; 30.99 GiB already allocated; 118.19 MiB free; 30.99 GiB reserved in total by PyTorch) If reserved memory is >> allocated memory try setting max_split_size_mb to avoid fragmentation.  See documentation for Memory Management and PYTORCH_CUDA_ALLOC_CONF
```

**Comment by archieCanada** [comment]
Molly, thank you very much. I was able to run my code following the advice given in the post you specified.

**Comment by molly-smith** [comment]
@archieCanada, can you please explain why you reopened the issue?

**Comment by molly-smith** [comment]
Hi @archieCanada, sorry for the delay. I just tested bigscience/T0pp with two 32GB GPUs successfully so it seems this issue is resolved. If it still persists for you please reopen or submit a new issue. Thanks.
