### ISSUE TITLE
[BUG] GPT-j memory overflows sharply if you use kernel inject

### ISSUE THREAD

**Issue by zelcookie** [microsoft/DeepSpeed#2466]
**Describe the bug**
When I set `replace_method="auto", replace_with_kernel_inject=True,` I get `RuntimeError: CUDA out of memory.` on A100 80Gb Without it takes  less than 18 Gb. And if I set `replace_method=None, replace_with_kernel_inject=False` deepspeed didn't get any profit compare to raw transformers

**To Reproduce**
```
from transformers import AutoTokenizer, AutoModelForCausalLM
import torch
import deepspeed

params = {
 'top_p': 0.95,
 'temperature': 1.3,
 'num_beams': 3,
 'do_sample': True,
 'max_length': None,
 'max_new_tokens': 65,
 'early_stopping': True,
 'repetition_penalty': 2.5,
 'eos_token_id': 198,
 'pad_token_id': 198,
 'forced_eos_token_id': 198,
 'use_cache': True,
 'no_repeat_ngram_size': 5,
 'length_penalty': 100.0,
 'num_return_sequences': 5,
 'min_length': 30,
 }

model_name = 'EleutherAI/gpt-j-6B'
tokenizer = AutoTokenizer.from_pretrained(model_name)
model = AutoModelForCausalLM.from_pretrained(model_name)

ds_model = deepspeed.init_inference(
    model=model,     
    mp_size=1,       
    dtype=torch.float16, 
    replace_method="auto", 
    replace_with_kernel_inject=True,
#     replace_method=None,
#     replace_with_kernel_inject=False
)

text = "<|endoftext|>Anton and Aaron are talking.\n\nAnton: Hey\nAaron: Hello \nAnton: What's up? \nAaron: It's all good, thank you\nAnton: Do you like Harry Potter books? \nAaron: Uhm, I think it has become a solid part of modern culture, and to answer your question, I do like it, yes. \nAnton: Which character are you? \nAaron: Some people think I am more of a Ron Weasley type\nAnton: Are you?  \nAaron: I wish I could be like Dumbledore, I think he's kinda cool. \nAnton: Which faculty would you be on? Gryffindore?"

inputs = tokenizer(text, return_tensors="pt", max_length=200,truncation=True ).to('cuda:0')
with torch.inference_mode():
    outputs = ds_model.generate(
                **inputs,
                **params,

            )
```
```
[2022-11-02 13:29:05,955] [INFO] [logging.py:68:log_dist] [Rank -1] DeepSpeed info: version=0.7.4, git-hash=unknown, git-branch=unknown
[2022-11-02 13:29:05,957] [INFO] [logging.py:68:log_dist] [Rank -1] quantize_bits = 8 mlp_extra_grouping = False, quantize_groups = 1
Installed CUDA version 11.3 does not match the version torch was compiled with 11.6 but since the APIs are compatible, accepting this combination
Using /home/mikhail/.cache/torch_extensions/py39_cu116 as PyTorch extensions root...
Detected CUDA files, patching ldflags
Emitting ninja build file /home/mikhail/.cache/torch_extensions/py39_cu116/transformer_inference/build.ninja...
Building extension module transformer_inference...
Allowing ninja to set a default number of workers... (overridable by setting the environment variable MAX_JOBS=N)
ninja: no work to do.
Loading extension module transformer_inference...
Time to load transformer_inference op: 0.21149802207946777 seconds
[2022-11-02 13:29:09,678] [INFO] [logging.py:68:log_dist] [Rank -1] DeepSpeed-Inference config: {'layer_id': 0, 'hidden_size': 4096, 'intermediate_size': 16384, 'heads': 16, 'num_hidden_layers': -1, 'fp16': True, 'pre_layer_norm': True, 'local_rank': -1, 'stochastic_mode': False, 'epsilon': 1e-05, 'mp_size': 1, 'q_int8': False, 'scale_attention': True, 'triangular_masking': True, 'local_attention': False, 'window_size': 1, 'rotary_dim': 64, 'rotate_half': False, 'rotate_every_two': True, 'return_tuple': True, 'mlp_after_attn': False, 'mlp_act_func_type': <ActivationFuncType.GELU: 1>, 'specialized_mode': False, 'training_mp_size': 1, 'bigscience_bloom': False}
Free memory : 71586086912 (Bytes)  Total memory: 85007794176 (Bytes)  Setting maximum total tokens (input + output) to 752 
---------------------------------------------------------------------------
RuntimeError                              Traceback (most recent call last)
Cell In [1], line 42
     40 inputs = tokenizer(text, return_tensors="pt", max_length=200,truncation=True ).to('cuda:0')
     41 with torch.inference_mode():
---> 42     outputs = ds_model.generate(
     43                 **inputs,
     44                 **params,
     45 
     46             )

File ~/venv/lib/python3.9/site-packages/torch/autograd/grad_mode.py:27, in _DecoratorContextManager.__call__.<locals>.decorate_context(*args, **kwargs)
     24 @functools.wraps(func)
     25 def decorate_context(*args, **kwargs):
     26     with self.clone():
---> 27         return func(*args, **kwargs)

File ~/venv/lib/python3.9/site-packages/transformers/generation_utils.py:1500, in GenerationMixin.generate(self, inputs, max_length, min_length, do_sample, early_stopping, num_beams, temperature, top_k, top_p, typical_p, repetition_penalty, bad_words_ids, force_words_ids, bos_token_id, pad_token_id, eos_token_id, length_penalty, no_repeat_ngram_size, encoder_no_repeat_ngram_size, num_return_sequences, max_time, max_new_tokens, decoder_start_token_id, use_cache, num_beam_groups, diversity_penalty, prefix_allowed_tokens_fn, logits_processor, renormalize_logits, stopping_criteria, constraints, output_attentions, output_hidden_states, output_scores, return_dict_in_generate, forced_bos_token_id, forced_eos_token_id, remove_invalid_values, synced_gpus, exponential_decay_length_penalty, suppress_tokens, begin_suppress_tokens, forced_decoder_ids, **model_kwargs)
   1492     input_ids, model_kwargs = self._expand_inputs_for_generation(
   1493         input_ids,
   1494         expand_size=num_beams * num_return_sequences,
   1495         is_encoder_decoder=self.config.is_encoder_decoder,
   1496         **model_kwargs,
   1497     )
   1499     # 13. run beam sample
-> 1500     return self.beam_sample(
   1501         input_ids,
   1502         beam_scorer,
   1503         logits_processor=logits_processor,
   1504         logits_warper=logits_warper,
   1505         stopping_criteria=stopping_criteria,
   1506         pad_token_id=pad_token_id,
   1507         eos_token_id=eos_token_id,
   1508         output_scores=output_scores,
   1509         return_dict_in_generate=return_dict_in_generate,
   1510         synced_gpus=synced_gpus,
   1511         **model_kwargs,
   1512     )
   1514 elif is_group_beam_gen_mode:
   1515     if num_return_sequences > num_beams:

File ~/venv/lib/python3.9/site-packages/transformers/generation_utils.py:2612, in GenerationMixin.beam_sample(self, input_ids, beam_scorer, logits_processor, stopping_criteria, logits_warper, max_length, pad_token_id, eos_token_id, output_attentions, output_hidden_states, output_scores, return_dict_in_generate, synced_gpus, **model_kwargs)
   2608         break
   2610 model_inputs = self.prepare_inputs_for_generation(input_ids, **model_kwargs)
-> 2612 outputs = self(
   2613     **model_inputs,
   2614     return_dict=True,
   2615     output_attentions=output_attentions,
   2616     output_hidden_states=output_hidden_states,
   2617 )
   2619 if synced_gpus and this_peer_finished:
   2620     cur_len = cur_len + 1

File ~/venv/lib/python3.9/site-packages/torch/nn/modules/module.py:1130, in Module._call_impl(self, *input, **kwargs)
   1126 # If we don't have any hooks, we want to skip the rest of the logic in
   1127 # this function, and just call forward.
   1128 if not (self._backward_hooks or self._forward_hooks or self._forward_pre_hooks or _global_backward_hooks
   1129         or _global_forward_hooks or _global_forward_pre_hooks):
-> 1130     return forward_call(*input, **kwargs)
   1131 # Do not call functions when jit is used
   1132 full_backward_hooks, non_full_backward_hooks = [], []

File ~/venv/lib/python3.9/site-packages/transformers/models/gptj/modeling_gptj.py:844, in GPTJForCausalLM.forward(self, input_ids, past_key_values, attention_mask, token_type_ids, position_ids, head_mask, inputs_embeds, labels, use_cache, output_attentions, output_hidden_states, return_dict)
    839     hidden_states = hidden_states.to(self.lm_head.weight.device)
    841 # make sure sampling in fp16 works correctly and
    842 # compute loss in fp32 to match with mesh-tf version
    843 # https://github.com/EleutherAI/gpt-neo/blob/89ce74164da2fb16179106f54e2269b5da8db333/models/gpt2/gpt2.py#L179
--> 844 lm_logits = self.lm_head(hidden_states).to(torch.float32)
    846 loss = None
    847 if labels is not None:
    848     # Shift so that tokens < n predict n

RuntimeError: CUDA out of memory. Tried to allocate 434.00 MiB (GPU 0; 79.17 GiB total capacity; 11.50 GiB already allocated; 363.81 MiB free; 11.50 GiB reserved in total by PyTorch) If reserved memory is >> allocated memory try setting max_split_size_mb to avoid fragmentation.  See documentation for Memory Management and PYTORCH_CUDA_ALLOC_CONF
```

**ds_report output**
```
--------------------------------------------------
DeepSpeed C++/CUDA extension op report
--------------------------------------------------
NOTE: Ops not installed will be just-in-time (JIT) compiled at
      runtime if needed. Op compatibility means that your system
      meet the required dependencies to JIT install the op.
--------------------------------------------------
JIT compiled ops requires ninja
ninja .................. [OKAY]
--------------------------------------------------
op name ................ installed .. compatible
--------------------------------------------------
cpu_adam ............... [NO] ....... [OKAY]
cpu_adagrad ............ [NO] ....... [OKAY]
fused_adam ............. [NO] ....... [OKAY]
fused_lamb ............. [NO] ....... [OKAY]
 [WARNING]  using untested triton version (2.0.0), only 1.0.0 is known to be compatible
sparse_attn ............ [NO] ....... [NO]
transformer ............ [NO] ....... [OKAY]
stochastic_transformer . [NO] ....... [OKAY]
 [WARNING]  async_io requires the dev libaio .so object and headers but these were not found.
 [WARNING]  async_io: please install the libaio-dev package with apt
 [WARNING]  If libaio is already installed (perhaps from source), try setting the CFLAGS and LDFLAGS environment variables to where it can be found.
async_io ............... [NO] ....... [NO]
utils .................. [NO] ....... [OKAY]
quantizer .............. [NO] ....... [OKAY]
transformer_inference .. [NO] ....... [OKAY]
--------------------------------------------------
DeepSpeed general environment info:
torch install path ............... ['/home/mikhail/venv/lib/python3.9/site-packages/torch']
torch version .................... 1.12.1+cu116
torch cuda version ............... 11.6
torch hip version ................ None
nvcc version ..................... 11.3
deepspeed install path ........... ['/home/mikhail/venv/lib/python3.9/site-packages/deepspeed']
deepspeed info ................... 0.7.4, unknown, unknown
deepspeed wheel compiled w. ...... torch 1.12, cuda 11.6
```

**System info (please complete the following information):**
 - OS: Debian GNU/Linux 10 (buster) (GNU/Linux 4.19.0-21-cloud-amd64 x86_64\n)
 -  CUDA Version: 11.6
 - x1 A100 80Gb
 - DeepSpeed 0.7.4
 -  Hugging Face Transformers 4.23.1
 - Python 3.9

**Comment by cmikeh2** [comment]
Hi @zelcookie,

Thanks for reporting this. I was able to reproduce the issue with your script on our master branch. Would you mind trying https://github.com/microsoft/DeepSpeed/pull/2433 to see if it fixes your issue? In my environment this did solve the OOM issue. Thanks!

**Comment by zelcookie** [comment]
@cmikeh2 Yes this problem has been solved but I got new one with generation quality, created new issue https://github.com/microsoft/DeepSpeed/issues/2506
