### ISSUE TITLE
How to inference a M2M100 model?

### ISSUE THREAD

**Issue by Bachstelze** [microsoft/DeepSpeed#2558]
I try to inference "alirezamsh/small100" with deepspeed and run into this error:
```
The tokenizer class you load from this checkpoint is not the same type as the class this function is called from. It may result in unexpected tokenization. 
The tokenizer class you load from this checkpoint is 'M2M100Tokenizer'. 
The class this function is called from is 'SMALL100Tokenizer'.

[2022-11-30 11:37:25,654] [INFO] [logging.py:68:log_dist] [Rank -1] DeepSpeed info: version=0.7.5, git-hash=unknown, git-branch=unknown
[2022-11-30 11:37:25,656] [INFO] [logging.py:68:log_dist] [Rank -1] quantize_bits = 8 mlp_extra_grouping = False, quantize_groups = 1
[2022-11-30 11:37:25,667] [INFO] [comm.py:618:init_distributed] Not using the DeepSpeed or dist launchers, attempting to detect MPI environment...
[2022-11-30 11:37:26,257] [INFO] [comm.py:675:mpi_discovery] Discovered MPI settings of world_rank=0, local_rank=0, world_size=1, master_addr=172.28.0.2, master_port=29500
[2022-11-30 11:37:26,259] [INFO] [comm.py:635:init_distributed] Initializing TorchBackend in DeepSpeed with backend nccl

---------------------------------------------------------------------------

RuntimeError                              Traceback (most recent call last)

[<ipython-input-8-d5cafc16db18>](https://localhost:8080/#) in <module>
     13                                  checkpoint=None,
     14                                  replace_method='auto',
---> 15                                  replace_with_kernel_inject=True)
     16 model = ds_engine.module
     17 output = model('Input String')

5 frames

[/usr/local/lib/python3.7/dist-packages/torch/distributed/distributed_c10d.py](https://localhost:8080/#) in new_group(ranks, timeout, backend, pg_options)
   2951         if group_world_size > global_world_size:
   2952             raise RuntimeError(
-> 2953                 "the new group's world size should be less or "
   2954                 "equal to the world size set by "
   2955                 "init_process_group"

RuntimeError: the new group's world size should be less or equal to the world size set by init_process_group
```
with this script:
```
from transformers import M2M100ForConditionalGeneration
from small100.tokenization_small100 import SMALL100Tokenizer
import deepspeed
import torch

model = M2M100ForConditionalGeneration.from_pretrained("alirezamsh/small100")
tokenizer = SMALL100Tokenizer.from_pretrained("alirezamsh/small100")

# Initialize the DeepSpeed-Inference engine
ds_engine = deepspeed.init_inference(model,
                                 mp_size=2,
                                 dtype=torch.half,
                                 checkpoint=None,
                                 replace_method='auto',
                                 replace_with_kernel_inject=True)
model = ds_engine.module
output = model('Input String')
```
The package versions on colab are:
deepspeed==0.7.5
transformers==4.24.0
torch @ https://download.pytorch.org/whl/cu113/torch-1.12.1%2Bcu113-cp37-cp37m-linux_x86_64.whl
torchtext==0.13.1

**Comment by molly-smith** [comment]
Hi @Bachstelze, your world size is set to 1 but your mp_size is set to 2. You should update your mp_size to be the same as world_size, the number of GPUs you are using.

**Comment by molly-smith** [comment]
`from transformers import M2M100ForConditionalGeneration
from small100.tokenization_small100 import SMALL100Tokenizer
import deepspeed
import torch
import os

model = M2M100ForConditionalGeneration.from_pretrained("alirezamsh/small100")
tokenizer = SMALL100Tokenizer.from_pretrained("alirezamsh/small100")

world_size = int(os.getenv('WORLD_SIZE', '1'))

# Initialize the DeepSpeed-Inference engine
ds_engine = deepspeed.init_inference(model,
                                 mp_size=world_size,
                                 dtype=torch.half,
                                 checkpoint=None,
                                 replace_method='auto',
                                 replace_with_kernel_inject=True)
model = ds_engine.module
output = model('Input String')`

**Comment by molly-smith** [comment]
```
from transformers import M2M100ForConditionalGeneration
from small100.tokenization_small100 import SMALL100Tokenizer
import deepspeed
import torch
import os

model = M2M100ForConditionalGeneration.from_pretrained("alirezamsh/small100")
tokenizer = SMALL100Tokenizer.from_pretrained("alirezamsh/small100")

world_size = int(os.getenv('WORLD_SIZE', '1'))

# Initialize the DeepSpeed-Inference engine
ds_engine = deepspeed.init_inference(model,
                                 mp_size=world_size,
                                 dtype=torch.half,
                                 checkpoint=None,
                                 replace_method='auto',
                                 replace_with_kernel_inject=True)
model = ds_engine.module
output = model('Input String')
```

**Comment by Bachstelze** [comment]
Thanks a lot! That solved my problem!

**Comment by Mucalinda2436** [comment]
> ```
> from transformers import M2M100ForConditionalGeneration
> from small100.tokenization_small100 import SMALL100Tokenizer
> import deepspeed
> import torch
> import os
> 
> model = M2M100ForConditionalGeneration.from_pretrained("alirezamsh/small100")
> tokenizer = SMALL100Tokenizer.from_pretrained("alirezamsh/small100")
> 
> world_size = int(os.getenv('WORLD_SIZE', '1'))
> 
> # Initialize the DeepSpeed-Inference engine
> ds_engine = deepspeed.init_inference(model,
>                                  mp_size=world_size,
>                                  dtype=torch.half,
>                                  checkpoint=None,
>                                  replace_method='auto',
>                                  replace_with_kernel_inject=True)
> model = ds_engine.module
> output = model('Input String')
> ```

but does that means that i can only use 1 GPU to infer? What if i need to use two GPU to infer the model, how can i write the code?

**Comment by YuMJie** [comment]
> [Mucalinda2436](/Mucalinda2436)

did you solve this issue? : )

**Comment by 123qwe-ux** [comment]
> > ```
> > from transformers import M2M100ForConditionalGeneration
> > from small100.tokenization_small100 import SMALL100Tokenizer
> > import deepspeed
> > import torch
> > import os
> > 
> > model = M2M100ForConditionalGeneration.from_pretrained("alirezamsh/small100")
> > tokenizer = SMALL100Tokenizer.from_pretrained("alirezamsh/small100")
> > 
> > world_size = int(os.getenv('WORLD_SIZE', '1'))
> > 
> > # Initialize the DeepSpeed-Inference engine
> > ds_engine = deepspeed.init_inference(model,
> >                                  mp_size=world_size,
> >                                  dtype=torch.half,
> >                                  checkpoint=None,
> >                                  replace_method='auto',
> >                                  replace_with_kernel_inject=True)
> > model = ds_engine.module
> > output = model('Input String')
> > ```
> 
> 但这是否意味着我只能使用 1 个 GPU 来推断？如果我需要使用两个 GPU 来推断模型，我该如何编写代码？



> did you solve this issue?

did you solve this issue? I need your help.

**Comment by Bachstelze** [comment]
@123qwe-ux what is your concrete issue?
The code from @molly-smith solved my issue.

> but does that means that i can only use 1 GPU to infer? What if i need to use two GPU to infer the model, how can i write the code?

@Mucalinda2436 I had only one GPU, so i could only use one. I guess that it works with more GPUs, if you change the world size.
