### ISSUE TITLE
[BUG] RuntimeError: CUDA out of memory

### ISSUE THREAD

**Issue by hgtttttt** [microsoft/DeepSpeed#3320]
**Describe the bug**
I encountered a strange situation. When I try to finetune a 6B model using one machine with x8 A100s, I get an error:

RuntimeError: CUDA out of memory. Tried to allocate 96.00 MiB (GPU 0; 79.35 GiB  total capacity; 9.78 GiB already allocated; 30.19 MiB free; 9.78 GiB reserved in total by PyTorch) If reserved memory is >> allocated memory try setting  max_split_size_mb to avoid fragmentation.  See documentation for Memory 
Management and PYTORCH_CUDA_ALLOC_CONF

What is strange is that when I finetune this model using  x4 A100s in the same machine with the same config and data, there isn't any problem.

Could you please help me?

This is the config about deepspeed:

    conf = {"train_micro_batch_size_per_gpu": 4,
            "gradient_accumulation_steps": 2,
            "optimizer": {
                "type": "Adam",
                "params": {
                    "lr": 1e-5,
                    # "lr": 1e-6,
                    "betas": [
                        0.9,
                        0.95
                    ],
                    "eps": 1e-8,
                    "weight_decay": 5e-4
                }
            },
            # "fp16": {
            #     "enabled": False,
            # },
            # "bf16": {
            #     "enabled": True,
            # },
            "fp16": {
                "enabled": True
            },
            "zero_optimization": {
                "stage": 1,
                "offload_optimizer": {
                    "device": "cpu",
                    "pin_memory": True
                },
                "allgather_partitions": True,
                "allgather_bucket_size": 2e8,
                "overlap_comm": True,
                "reduce_scatter": True,
                "reduce_bucket_size": 2e8,
                "contiguous_gradients": True
            },
            "steps_per_print": 10
            }

**System info (please complete the following information):**
 - GPU count and types: one machine with x8 A100s
 - Python version: 3.7.16, Pytorch: 1.12.1, Deepspeed: 0.8.2

**Comment by zy-sunshine** [comment]
You can use nvidia-smi command to check the memory usage of your GPU actually, maybe another program use some GPU memory?

**Comment by hgtttttt** [comment]
> You can use nvidia-smi command to check the memory usage of your GPU actually, maybe another program use some GPU memory?

I check the memory, and no other program uses the same GPU. When I use x4 A100s, logs show that the train.py uses about 60G memory in every GPU, but when I use x8 A100s, logs show that the max usage of GPU memory is less than 1G. It seems that this error appears even before the model is loaded. Theoretically, using x8 A100s should have less usage of GPU memory than using x4 A100s, so I'm very confused about this error.

**Comment by jomayeri** [comment]
Hi @hgtttttt, could you provide a simple repro script so we can see how the model is being initialized an to test locally? Thanks.

**Comment by jomayeri** [comment]
@hgtttttt could you also provide the full log of when the error occurs so we may examine the stack trace. Thanks.

**Comment by jomayeri** [comment]
Hi @hgtttttt, thanks for the code but could you please provide one that is runnable via a simple copy and paste. Also it appears from the stacktrace that the failure comes before `deepspeed.initialize()` at the line `model.half().cuda()`. You don't need to manually convert the model to fp16 DeepSpeed will take care of that internally. Try removing that line and running.

**Comment by hgtttttt** [comment]
@jomayeri Yes it works! I deleted this line of code and the error disappeared. So maybe there are some conflicts when I manually convert the model to fp16, which only appears when I use x8 A100s.
All in all, I'm extremely grateful for your assistance!
