### ISSUE TITLE
[BUG][Hybrid Engine] Hybrid Engine Raise "CUBLAS_STATUS_EXECUTION_FAILED " for opt-350m

### ISSUE THREAD

**Issue by sxjscience** [microsoft/DeepSpeed#3554]
**Describe the bug**

When hybrid engine is turned on, running `facebook/opt-350m` will raise error.

**To Reproduce**
```bash
wget https://gist.githubusercontent.com/sxjscience/2a2fb9955aa089859f36f20e9861665f/raw/8596e69cabd2305787f13d0ccf16f01e10ce5e4d/opt_350m_bug_reproduce.py -O opt_350m_bug_reproduce.py

# Following gives error
CUDA_LAUNCH_BLOCKING=1 deepspeed --num_gpus 1 --master_port 29501 opt_350m_bug_reproduce.py

# No error
CUDA_LAUNCH_BLOCKING=1 deepspeed --num_gpus 1 --master_port 29501 opt_350m_bug_reproduce.py --disable_hybrid_engine

# No error
CUDA_LAUNCH_BLOCKING=1 deepspeed --num_gpus 1 --master_port 29501 opt_350m_bug_reproduce.py --model_name facebook/opt-1.3b
```

Error message:

```
    generate_ret_vals = self._generate(*inputs, **kwargs)
  File "/home/xxx/anaconda3/lib/python3.10/site-packages/torch/utils/_contextlib.py", line 115, in decorate_context
    return func(*args, **kwargs)
  File "/home/xxx/anaconda3/lib/python3.10/site-packages/transformers/generation/utils.py", line 1515, in generate
    return self.greedy_search(
  File "/home/xxx/anaconda3/lib/python3.10/site-packages/transformers/generation/utils.py", line 2332, in greedy_search
    outputs = self(
  File "/home/xxx/anaconda3/lib/python3.10/site-packages/torch/nn/modules/module.py", line 1501, in _call_impl
    return forward_call(*args, **kwargs)
  File "/home/xxx/anaconda3/lib/python3.10/site-packages/transformers/models/opt/modeling_opt.py", line 937, in forward
    outputs = self.model.decoder(
  File "/home/xxx/anaconda3/lib/python3.10/site-packages/torch/nn/modules/module.py", line 1501, in _call_impl
    return forward_call(*args, **kwargs)
  File "/home/xxx/anaconda3/lib/python3.10/site-packages/transformers/models/opt/modeling_opt.py", line 724, in forward
    hidden_states = self.project_out(hidden_states)
  File "/home/xxx/anaconda3/lib/python3.10/site-packages/torch/nn/modules/module.py", line 1501, in _call_impl
    return forward_call(*args, **kwargs)
  File "/home/xxx/Documents/xxx/DeepSpeed/deepspeed/module_inject/layers.py", line 50, in forward
    output = torch.matmul(input, self.weight.transpose(-1, -2))
RuntimeError: CUDA error: CUBLAS_STATUS_EXECUTION_FAILED when calling `cublasGemmEx( handle, opa, opb, m, n, k, &falpha, a, CUDA_R_16F, lda, b, CUDA_R_16F, ldb, &fbeta, c, CUDA_R_16F, ldc, CUDA_R_32F, CUBLAS_GEMM_DFALT_TENSOR_OP)`
```

**Expected behavior**
For all the other combinations "no-hybrid-engine + opt-350m", "hybrid-engine + opt-1.3b", it will correctly generate the outputs

```
Building extension module utils...
Allowing ninja to set a default number of workers... (overridable by setting the environment variable MAX_JOBS=N)
ninja: no work to do.
Loading extension module utils...
Time to load utils op: 0.04421091079711914 seconds
["DeepSpeed is a great company. I've been using them for a while now.\nI"]
[2023-05-16 14:41:29,788] [INFO] [launch.py:346:main] Process 178639 exits successfully.
```
**ds_report output**
Please run `ds_report` to give us details about your setup.

```
Setting ds_accelerator to cuda (auto detect)
Setting ds_accelerator to cuda (auto detect)
--------------------------------------------------
DeepSpeed C++/CUDA extension op report
--------------------------------------------------
NOTE: Ops not installed will be just-in-time (JIT) compiled at
      runtime if needed. Op compatibility means that your system
      meet the required dependencies to JIT install the op.
--------------------------------------------------
JIT compiled ops requires ninja
ninja .................. [OKAY]
--------------------------------------------------
op name ................ installed .. compatible
--------------------------------------------------
 [WARNING]  async_io requires the dev libaio .so object and headers but these were not found.
 [WARNING]  async_io: please install the libaio-dev package with apt
 [WARNING]  If libaio is already installed (perhaps from source), try setting the CFLAGS and LDFLAGS environment variables to where it can be found.
async_io ............... [NO] ....... [NO]
cpu_adagrad ............ [NO] ....... [OKAY]
cpu_adam ............... [NO] ....... [OKAY]
fused_adam ............. [NO] ....... [OKAY]
fused_lamb ............. [NO] ....... [OKAY]
quantizer .............. [NO] ....... [OKAY]
random_ltd ............. [NO] ....... [OKAY]
 [WARNING]  sparse_attn requires a torch version >= 1.5 and < 2.0 but detected 2.0
 [WARNING]  using untested triton version (2.0.0), only 1.0.0 is known to be compatible
sparse_attn ............ [NO] ....... [NO]
spatial_inference ...... [NO] ....... [OKAY]
transformer ............ [NO] ....... [OKAY]
stochastic_transformer . [NO] ....... [OKAY]
transformer_inference .. [NO] ....... [OKAY]
utils .................. [NO] ....... [OKAY]
--------------------------------------------------
DeepSpeed general environment info:
torch install path ............... ['/home/xxx/anaconda3/lib/python3.10/site-packages/torch']
torch version .................... 2.0.0+cu118
deepspeed install path ........... ['.../DeepSpeed/deepspeed']
deepspeed info ................... 0.9.3+c8d3f5eb, c8d3f5eb, master
torch cuda version ............... 11.8
torch hip version ................ None
nvcc version ..................... 11.8
deepspeed wheel compiled w. ...... torch 2.0, cuda 11.8
```

**Screenshots**

**System info (please complete the following information):**
 - OS: Ubuntu 22.04
 - GPU count and types 2x3090
 - (if applicable) what [DeepSpeed-MII](https://github.com/microsoft/deepspeed-mii) version are you using
 - (if applicable) Hugging Face Transformers/Accelerate/etc. versions
 - Python version: 3.10
 - Any other relevant info about your setup

**Docker context**
Are you using a specific docker image that you can share?

**Additional context**

**Comment by sxjscience** [comment]
After some investigation, I noticed that it may be related to misaligned CUDA address (may be due to `workspace + offset` calls?). If I force the token length to be a multiplication of 32, the error disappeared. If we revise the code https://gist.github.com/sxjscience/2a2fb9955aa089859f36f20e9861665f as follows, there will be no error

```python
# Ensure padding sequence length to multiplication of 32
tokens = tokenizer.batch_encode_plus(prompt, return_tensors="pt", padding="max_length", max_length=32)
```

Original was
```python
tokens = tokenizer.batch_encode_plus(prompt, return_tensors="pt", padding=True)
```
