### ISSUE TITLE
[QUESTION] Step3, fatal error: cuda_bf16.h: No such file or directory

### ISSUE THREAD

**Issue by 4daJKong** [microsoft/DeepSpeed#4097]
I trained actor model and critic model step by step and saved them in ./step1_supervised_finetuning/output and  ./step2_reward_model_finetuning/output separately

Then I continue to run the third step by 

`bash training_scripts/single_gpu/run_1.3b.sh  ./step1_supervised_finetuning/output  ./step2_reward_model_finetuning/output`

It shows a long error and I think the main error is on: ./inference_cublas_wrappers.h:12:10: fatal error: cuda_bf16.h: No such file or directory
 #include <cuda_bf16.h>
          ^~~~~~~~~~~~~
compilation terminated.
My cuda version is 10.2 and I tried to download` cuda_bf16.h/cuda_bf16.hpp` into /usr/local/cuda-10.2/targets/x86_64-linux/include but still shows` No declaration matches '__half ::__half(__nv_bfloat16)' `

I found the main error on the function `create_inference_containers` of  class` DeepSpeedHybridEngine` so I change it to class `DeepSpeedEngine` by removing --enable_hybrid_engine in run_1.3b.sh

However, it shows error: cuda out of memory, even though I change all train_batch to 1 and set os.environ["PYTORCH_CUDA_ALLOC_CONF"] = "max_split_size_mb:32"

**Comment by 4daJKong** [comment]
@loadams  Hi, sorry for reply late, now I have installed cuda 12.2, and downloading cudnn and tensorRT, and I plan to reinstall torch later, hope everything is ok. I will post message sooner and thanks for your help again.

**Comment by 4daJKong** [comment]
@loadams Thanks a lot, now when I use `nvcc -V` cmd, it shows the cuda version is 12.2 (I found my GPU driver only support 12.2, 12.0, 11.7, 11.4, 11.2, 11.0, 10.2, 10.1, 10.0) but I am not sure what is the most compatible version (cuda, tensorRT, torch, etc) for deepspeed chat application.  I only found a requirements.txt shows,
```
datasets>=2.8.0
sentencepiece>=0.1.97
protobuf==3.20.3
accelerate>=0.15.0
torch>=1.12.0
deepspeed>=0.9.0
git+https://github.com/huggingface/transformers
```
what about others, could you please give me some suggestions?

**Comment by 4daJKong** [comment]
@loadams  After I installed deepspeed environment and all packages, I still face some problems, when I run step 3, it mainly shows this error,
```
Allowing ninja to set a default number of workers... (overridable by setting the environment variable MAX_JOBS=N)
[1/2] /usr/local/cuda-10.2/bin/nvcc  -DTORCH_EXTENSION_NAME=fused_adam -DTORCH_API_INCLUDE_EXTENSION_H -DPYBIND11_COMPILER_TYPE=\"_gcc\" -DPYBIND11_STDLIB=\"_libstdcpp\" -DPYBIND11_BUILD_ABI=\"_cxxabi1011\" -I/home/coco/miniconda3/envs/deepspeed/lib/python3.8/site-packages/deepspeed/ops/csrc/includes -I/home/coco/miniconda3/envs/deepspeed/lib/python3.8/site-packages/deepspeed/ops/csrc/adam -isystem /home/coco/miniconda3/envs/deepspeed/lib/python3.8/site-packages/torch/include -isystem /home/coco/miniconda3/envs/deepspeed/lib/python3.8/site-packages/torch/include/torch/csrc/api/include -isystem /home/coco/miniconda3/envs/deepspeed/lib/python3.8/site-packages/torch/include/TH -isystem /home/coco/miniconda3/envs/deepspeed/lib/python3.8/site-packages/torch/include/THC -isystem /usr/local/cuda-10.2/include -isystem /home/coco/miniconda3/envs/deepspeed/include/python3.8 -D_GLIBCXX_USE_CXX11_ABI=0 -D__CUDA_NO_HALF_OPERATORS__ -D__CUDA_NO_HALF_CONVERSIONS__ -D__CUDA_NO_BFLOAT16_CONVERSIONS__ -D__CUDA_NO_HALF2_OPERATORS__ --expt-relaxed-constexpr -gencode=arch=compute_75,code=compute_75 -gencode=arch=compute_75,code=sm_75 --compiler-options '-fPIC' -O3 -DVERSION_GE_1_1 -DVERSION_GE_1_3 -DVERSION_GE_1_5 -lineinfo --use_fast_math -gencode=arch=compute_75,code=sm_75 -gencode=arch=compute_75,code=compute_75 -std=c++17 -c /home/coco/miniconda3/envs/deepspeed/lib/python3.8/site-packages/deepspeed/ops/csrc/adam/multi_tensor_adam.cu -o multi_tensor_adam.cuda.o 
FAILED: multi_tensor_adam.cuda.o 
/usr/local/cuda-10.2/bin/nvcc  -DTORCH_EXTENSION_NAME=fused_adam -DTORCH_API_INCLUDE_EXTENSION_H -DPYBIND11_COMPILER_TYPE=\"_gcc\" -DPYBIND11_STDLIB=\"_libstdcpp\" -DPYBIND11_BUILD_ABI=\"_cxxabi1011\" -I/home/coco/miniconda3/envs/deepspeed/lib/python3.8/site-packages/deepspeed/ops/csrc/includes -I/home/coco/miniconda3/envs/deepspeed/lib/python3.8/site-packages/deepspeed/ops/csrc/adam -isystem /home/coco/miniconda3/envs/deepspeed/lib/python3.8/site-packages/torch/include -isystem /home/coco/miniconda3/envs/deepspeed/lib/python3.8/site-packages/torch/include/torch/csrc/api/include -isystem /home/coco/miniconda3/envs/deepspeed/lib/python3.8/site-packages/torch/include/TH -isystem /home/coco/miniconda3/envs/deepspeed/lib/python3.8/site-packages/torch/include/THC -isystem /usr/local/cuda-10.2/include -isystem /home/coco/miniconda3/envs/deepspeed/include/python3.8 -D_GLIBCXX_USE_CXX11_ABI=0 -D__CUDA_NO_HALF_OPERATORS__ -D__CUDA_NO_HALF_CONVERSIONS__ -D__CUDA_NO_BFLOAT16_CONVERSIONS__ -D__CUDA_NO_HALF2_OPERATORS__ --expt-relaxed-constexpr -gencode=arch=compute_75,code=compute_75 -gencode=arch=compute_75,code=sm_75 --compiler-options '-fPIC' -O3 -DVERSION_GE_1_1 -DVERSION_GE_1_3 -DVERSION_GE_1_5 -lineinfo --use_fast_math -gencode=arch=compute_75,code=sm_75 -gencode=arch=compute_75,code=compute_75 -std=c++17 -c /home/coco/miniconda3/envs/deepspeed/lib/python3.8/site-packages/deepspeed/ops/csrc/adam/multi_tensor_adam.cu -o multi_tensor_adam.cuda.o 
nvcc fatal   : Value 'c++17' igs not defined for option 'std'
ninja: build stopped: subcommand failed.
```
I found that it is very similar with the issue 594 (https://github.com/microsoft/DeepSpeedExamples/issues/594)

I am confused with that, because although I have `/usr/local/cuda-10.2` folder, I have set all path to cuda 12.2
when I input nvcc -V,
```
nvcc: NVIDIA (R) Cuda compiler driver
Copyright (c) 2005-2023 NVIDIA Corporation
Built on Tue_Jul_11_02:20:44_PDT_2023
Cuda compilation tools, release 12.2, V12.2.128
Build cuda_12.2.r12.2/compiler.33053471_0
```
input echo $PATH,
```
/opt/rh/devtoolset-8/root/usr/bin:
/usr/local/cuda-12.2/bin:
/home/coco/.vscodeserver/bin/6c3e3dba23e8fadc360aed75ce363ba185c49984/bin/remotecli:
/usr/local/cuda-12.2/bin:
/usr/local/cuda-10.2/bin:
/usr/local/cuda-12.2/bin:
/home/coco/miniconda3/envs/deepspeed/bin:
/home/coco/miniconda3/condabin:
/usr/lib64/qt-3.3/bin:
/usr/local/bin:
/usr/bin:
/usr/local/sbin:
/usr/sbin:
/home/coco/.local/bin:
/home/coco/bin
```
I add some path in my bashrc file like,
# .bashrc

# Source global definitions
if [ -f /etc/bashrc ]; then
	. /etc/bashrc
fi

# Uncomment the following line if you don't like systemctl's auto-paging feature:
# export SYSTEMD_PAGER=

# User specific aliases and functions

# >>> conda initialize >>>
# !! Contents within this block are managed by 'conda init' !!
__conda_setup="$('/home/coco/miniconda3/bin/conda' 'shell.bash' 'hook' 2> /dev/null)"
if [ $? -eq 0 ]; then
    eval "$__conda_setup"
else
    if [ -f "/home/lizongyue/miniconda3/etc/profile.d/conda.sh" ]; then
        . "/home/lizongyue/miniconda3/etc/profile.d/conda.sh"
    else
        export PATH="/home/lizongyue/miniconda3/bin:$PATH"
    fi
fi
unset __conda_setup
# <<< conda initialize <<<
export PATH=/usr/local/cuda-12.2/bin:$PATH
export LD_LIBRARY_PATH=/usr/local/cuda-12.2/lib64:$LD_LIBRARY_PATH
export CPATH=/usr/local/cuda-12.2/targets/x86_64-linux/include:$CPATH

**Comment by 4daJKong** [comment]
> /opt/rh/devtoolset-8/root/usr/bin:
> /usr/local/cuda-12.2/bin:
> /home/coco/.vscodeserver/bin/6c3e3dba23e8fadc360aed75ce363ba185c49984/bin/remotecli:
> /usr/local/cuda-12.2/bin:
> /usr/local/cuda-10.2/bin:
> /usr/local/cuda-12.2/bin:
> /home/coco/miniconda3/envs/deepspeed/bin:
> /home/coco/miniconda3/condabin:
> /usr/lib64/qt-3.3/bin:
> /usr/local/bin:
> /usr/bin:
> /usr/local/sbin:
> /usr/sbin:
> /home/coco/.local/bin:
> /home/coco/bin

Now I `sudo vim /etc/profile`
change cuda-10.2 to cuda-12.2
then, `source /etc/profile`
It can solved above problem, but shows new problem,
```
FAILED: layer_norm.cuda.o 
/usr/local/cuda-12.2/bin/nvcc  -DTORCH_EXTENSION_NAME=transformer_inference -DTORCH_API_INCLUDE_EXTENSION_H -DPYBIND11_COMPILER_TYPE=\"_gcc\" -DPYBIND11_STDLIB=\"_libstdcpp\" -DPYBIND11_BUILD_ABI=\"_cxxabi1011\" -I/home/coco/miniconda3/envs/deepspeed/lib/python3.8/site-packages/deepspeed/ops/csrc/transformer/inference/includes -I/home/coco/miniconda3/envs/deepspeed/lib/python3.8/site-packages/deepspeed/ops/csrc/includes -isystem /home/coco/miniconda3/envs/deepspeed/lib/python3.8/site-packages/torch/include -isystem /home/coco/miniconda3/envs/deepspeed/lib/python3.8/site-packages/torch/include/torch/csrc/api/include -isystem /home/coco/miniconda3/envs/deepspeed/lib/python3.8/site-packages/torch/include/TH -isystem /home/coco/miniconda3/envs/deepspeed/lib/python3.8/site-packages/torch/include/THC -isystem /usr/local/cuda-12.2/include -isystem /home/coco/miniconda3/envs/deepspeed/include/python3.8 -D_GLIBCXX_USE_CXX11_ABI=0 -D__CUDA_NO_HALF_OPERATORS__ -D__CUDA_NO_HALF_CONVERSIONS__ -D__CUDA_NO_BFLOAT16_CONVERSIONS__ -D__CUDA_NO_HALF2_OPERATORS__ --expt-relaxed-constexpr -gencode=arch=compute_75,code=compute_75 -gencode=arch=compute_75,code=sm_75 --compiler-options '-fPIC' -std=c++17 -c /home/coco/miniconda3/envs/deepspeed/lib/python3.8/site-packages/deepspeed/ops/csrc/transformer/inference/csrc/layer_norm.cu -o layer_norm.cuda.o 
/home/coco/miniconda3/envs/deepspeed/lib/python3.8/site-packages/deepspeed/ops/csrc/includes/reduction_utils.h(171): error: no operator "+" matches these operands
            operand types are: const __half + const __half
      return lhs + rhs;
```

**Comment by 4daJKong** [comment]
@loadams Good news, it can worked in cuda 11.7(still have some problems on cuda 12.2) However, even though I default batch_size as 1, it is still out of memory (my GPU is nvidia T4 with 15360Mib) That is confused

**Comment by loadams** [comment]
So with 11.7 you see the out of memory issues and on 12.2 you see the various compilation issues?  Is there one that's preferable to solve?  

Can you share both errors you are seeing?

**Comment by loadams** [comment]
Hi @4daJKong - can you share your DS config and the device that you are running on?

**Comment by 4daJKong** [comment]
Hi,  @loadams  thanks for your reply again, I attached below,
```
[2023-08-24 09:01:28,137] [INFO] [runner.py:540:main] cmd = /home/coco/miniconda3/envs/deepspeed/bin/python -u -m deepspeed.launcher.launch 
--world_info=eyJsb4NhbGhvc3QiOiBbMF18 
--master_addr=127.0.0.1 
--master_port=12345 
--enable_each_rank_log=None main.py 
--actor_model_name_or_path /home/coco/DeepSpeed/DeepSpeedExamples/applications/DeepSpeed-Chat/training/step1_supervised_finetuning/output 
--critic_model_name_or_path /home/coco/DeepSpeed/DeepSpeedExamples/applications/DeepSpeed-Chat/training/step2_reward_model_finetuning/output 
--actor_zero_stage 0 
--critic_zero_stage 0 
--num_padding_at_beginning 1 
--gradient_accumulation_steps 1 
--deepspeed --actor_lora_dim 128
--per_device_train_batch_size 1
--per_device_mini_train_batch_size 1
--enable_hybrid_engine 
--actor_gradient_checkpointing 
--disable_actor_dropout 
--release_inference_cache 
--offload_reference_model 
--output_dir ./output
```
in step3,  when running `bash training_scripts/single_gpu/run_1.3b.sh`  and more details on training.log
[training.log](https://github.com/microsoft/DeepSpeed/files/12424450/training.log)

**Comment by loadams** [comment]
Hi @4daJKong - to save memory, you would want to consider a number of things, such as increasing the Zero stage/offload you are using.  Since the 14GB of memory your GPU has is fairly low, so I'd increase to Zero stage 3 or try a smaller actor or critic model such as the facebook/opt-125m that our DS Chat Step 3 PyTest runs (more overall info [here](https://github.com/microsoft/DeepSpeedExamples/blob/master/applications/DeepSpeed-Chat/training/step3_rlhf_finetuning/training_scripts/opt/single_node/sweep/README.md#usage)).

**Comment by 4daJKong** [comment]
@loadams Thank you so much, I followed parameters you provided and it can work now! I guess the main reason is on the actor model, because the system need freeze actor model as ref modell at the same time. so it cost lots of memo. All in all, it is truly to consider many things

**Comment by loadams** [comment]
@4daJKong - yes, it consumes a lot of GPU memory, but glad you were able to get things working.  I'll close this issue for now, if you have other questions/issues, please re-open or open a new issue and link this one and we can take a look.
