### ISSUE TITLE
[BUG] Deadlock in distribution with multiple 4090

### ISSUE THREAD

**Issue by volcverse** [microsoft/DeepSpeed#4433]
**Describe the bug**
I'm trying to train a model with multiple 4090 gpus, but it always gets stuck and no report is shown. But when training with 3090 everything is fine. I strongly suspect that a deadlock occurs. 

A simplest python code is attached.

```
from torch.optim import AdamW
from diffusers import StableDiffusionPipeline
import os
import torch.distributed as dist
import torch
import deepspeed

from datetime import timedelta
import torchvision

master_addr = os.environ.get("MASTER_ADDR", 'localhost')
master_port = os.environ.get("MASTER_PORT", 12345)
master_uri = f"tcp://{master_addr}:{master_port}" #if master_addr else 'localhost'
world_size = int(os.environ['OMPI_COMM_WORLD_SIZE'])
world_rank = int(os.environ['OMPI_COMM_WORLD_RANK'])
local_rank = int(os.environ['OMPI_COMM_WORLD_LOCAL_RANK'])


torch.cuda.set_device(local_rank)
dist.init_process_group(
    backend='nccl',
    init_method=master_uri,
    world_size=world_size,
    rank=world_rank,
    timeout=timedelta(hours=5),  # 5 hrs
)
torch.cuda.synchronize()

config = {'flops_profiler': {'detailed': True, 'enabled': False, 'module_depth': -1, 'profile_step': 1, 'top_modules': 3}, 'fp16': {'enabled': True}, 'gradient_accumulation_steps': 1, 'tensorboard': {'enabled': True, 'job_name': 'tensorboard_log', 'output_path': './'}, 'train_micro_batch_size_per_gpu': 16, 'zero_allow_untested_optimizer': True, 'zero_force_ds_cpu_optimizer': False, 'zero_optimization': {'allgather_bucket_size': 500000000.0, 'contiguous_gradients': True, 'offload_optimizer': {'device': 'cpu', 'pin_memory': True}, 'overlap_comm': True, 'reduce_bucket_size': 500000000.0, 'reduce_scatter': True, 'round_robin_gradients': True, 'stage': 2}}

model = torchvision.models.vgg16(pretrained=False)
model.to('cuda')
optimizer = AdamW(model.parameters(), lr=1e-3, betas=(0.9, 0.98), weight_decay=1e-3)

model, optimizer,_,_ = deepspeed.initialize(
    config_params=config,
    model=model,
    optimizer=optimizer,
)
```

Any response will be greatly appreciated!!

**To Reproduce**

copy the provided python code into test.py

Run the provided python file with `CUDA_VISIBLE_DEVICES=0,1 AZFUSE_USE_FUSE=0 QD_USE_LINEIDX_8B=0 NCCL_ASYNC_ERROR_HANDLING=0 mpirun -np 2 python test.py`

**Expected behavior**
Run the code successfully without getting stuck.

**ds_report output**

```

[2023-10-01 21:04:04,088] [INFO] [real_accelerator.py:158:get_accelerator] Setting ds_accelerator to cuda (auto detect)
--------------------------------------------------
DeepSpeed C++/CUDA extension op report
--------------------------------------------------
NOTE: Ops not installed will be just-in-time (JIT) compiled at
      runtime if needed. Op compatibility means that your system
      meet the required dependencies to JIT install the op.
--------------------------------------------------
JIT compiled ops requires ninja
ninja .................. [OKAY]
--------------------------------------------------
op name ................ installed .. compatible
--------------------------------------------------
 [WARNING]  async_io requires the dev libaio .so object and headers but these were not found.
 [WARNING]  async_io: please install the libaio-dev package with apt
 [WARNING]  If libaio is already installed (perhaps from source), try setting the CFLAGS and LDFLAGS environment variables to where it can be found.
async_io ............... [NO] ....... [NO]
fused_adam ............. [NO] ....... [OKAY]
cpu_adam ............... [NO] ....... [OKAY]
cpu_adagrad ............ [NO] ....... [OKAY]
fused_lamb ............. [NO] ....... [OKAY]
quantizer .............. [NO] ....... [OKAY]
random_ltd ............. [NO] ....... [OKAY]
 [WARNING]  sparse_attn requires a torch version >= 1.5 and < 2.0 but detected 2.0
 [WARNING]  using untested triton version (2.0.0), only 1.0.0 is known to be compatible
sparse_attn ............ [NO] ....... [NO]
spatial_inference ...... [NO] ....... [OKAY]
transformer ............ [NO] ....... [OKAY]
stochastic_transformer . [NO] ....... [OKAY]
transformer_inference .. [NO] ....... [OKAY]
--------------------------------------------------
DeepSpeed general environment info:
torch install path ............... ['/miniconda3/envs/disco/lib/python3.10/site-packages/torch']
torch version .................... 2.0.1+cu118
deepspeed install path ........... ['/miniconda3/envs/disco/lib/python3.10/site-packages/deepspeed']
deepspeed info ................... 0.10.3, unknown, unknown
torch cuda version ............... 11.8
torch hip version ................ None
nvcc version ..................... 11.8
deepspeed wheel compiled w. ...... torch 2.0, cuda 11.8
shared memory (/dev/shm) size .... 251.83 GB

```

**Screenshots**

**System info (please complete the following information):**
 - OS: Ubuntu 22.04
 - GPU count and types: 1 machine with x8 4090
 - Python version: 3.10
 - Any other relevant info about your setup

**Launcher context**
`CUDA_VISIBLE_DEVICES=0,1 AZFUSE_USE_FUSE=0 QD_USE_LINEIDX_8B=0 NCCL_ASYNC_ERROR_HANDLING=0 mpirun -np 2 `

**Docker context**
Are you using a specific docker image that you can share?
No

**Additional context**

**Comment by volcverse** [comment]
I just found I don't have an global nvcc installed. Would this be the crux?

**Comment by Rbrq03** [comment]
Any update on this problem? Further, I believe that this issue is not only associated with DeepSpeed, but with distribute training on 4090.

**Comment by tjruwase** [comment]
@volcverse, @Rbrq03 apologies for the delayed response on this. Unfortunately, repro'ing this hang will be difficult since it seems to be hardware specific. Can you try debugging on your side by using `py-spy` to inspect the stack trace and identify the hang location. See the link below for guide on using `py-spy`
https://github.com/stas00/ml-engineering/blob/master/debug/torch-distributed-hanging-solutions.md

**Comment by volcverse** [comment]
@Rbrq03 @tjruwase 

Thanks for the response.

NCCL_P2P_DISABLE=1 works for me.
It seems that 4090 doesn't support p2p, so disable it everything will be fine.

**Comment by Rbrq03** [comment]
@tjruwase @volcverse  
Thanks for your kind response and providing the tool for debugging this issue. I do believe NCCL_P2P_DISABLE=1 works in some cases in my experience. Unfortunately, this command fails in other cases. I will try to use the tool.

**Comment by tjruwase** [comment]
@volcverse and @Rbrq03 thanks for your responses. I am glad that a workaround is available for some cases. I also agree that this issue is not due to DeepSpeed. So, I will close this ticket for now. Please feel free to update or re-open if needed. Thanks!
