### ISSUE TITLE
[BUG] CUDA out of memory when adding a new module

### ISSUE THREAD

**Issue by Riraifu** [microsoft/DeepSpeed#4829]
**Describe the bug**
I try to use deepspeed ZeRO-3 with huggingface Trainer.  I want to add a new module to gpt-j-6b，but OOM when training with 4 RTX 4090 GPU. But if I only finetune gpt-j-6b without adding any module, it works well.
I don't know how to fix it, can you help me? Thanks!   I can't find any similar code in Google.

here is an easy sample 
```
class NewModuleWithGPTJ(GPTJPreTrainedModel):
    def __init__(self, config,): 
        super().__init__(config)  
        self.new_module = NewModule(config.n_embd, config.mid_dim, config.n_block) # only 2 nn.Linear()  with just a little parameters.  
        self.llm = AutoModelForCausalLM.from_config(config)
        self.embd_layer = self.llm.get_input_embeddings()

        # Model parallel
        self.model_parallel = False
        self.device_map = None
        self.gradient_checkpointing = False

    def load_llm(self, args):
        self.llm = AutoModelForCausalLM.from_pretrained(args.model_name_or_path)

    def forward(self,
        input_ids=None,    
        prompt_ids=None,       
        attention_mask=None,
        labels=None,         
        use_cache=None,
        output_hidden_states=None,  
        return_dict=None,
        ):
        out = self.embd_layer(prompt_ids)  
        out= self.new_module(out)
        past_key_values= self.llm(inputs_embeds=out, return_dict=True).past_key_values
        return self.llm(input_ids=input_ids,   
            attention_mask=attention_mask,
            labels=labels,                    
            past_key_values=past_key_values,         
            use_cache=use_cache,
            output_hidden_states=output_hidden_states, 
            return_dict=return_dict)
```

OOM is happen in  “ out= self.llm(inputs_embeds=out, return_dict=True)” this line. Can you help me? Thanks!

**Comment by Riraifu** [comment]
My ds_config.json
```
{   
    "fp16": {
        "enabled": "auto", 
        "loss_scale": 0,
        "loss_scale_window": 1000,
        "initial_scale_power": 32,
        "hysteresis": 2,
        "min_loss_scale": 1
    },

    "zero_optimization": {
        "stage": 3,
        "offload_optimizer": {
            "device": "cpu",
            "pin_memory": true
        },
        "offload_param": {
            "device": "cpu",
            "pin_memory": true
        },
        "overlap_comm": true,
        "contiguous_gradients": true,
        "sub_group_size": 1e9,
        "reduce_bucket_size": "auto",
        "stage3_prefetch_bucket_size": "auto",
        "stage3_param_persistence_threshold": "auto",
        "stage3_max_live_parameters": 1e9,
        "stage3_max_reuse_distance": 1e9,
        "stage3_gather_16bit_weights_on_model_save": true
    },

    "gradient_clipping": 1.0,  

    "gradient_accumulation_steps": 1,
    "steps_per_print": 1,
    "train_batch_size": "auto",
    "train_micro_batch_size_per_gpu": "auto",

    "wall_clock_breakdown": false
}
```

**Comment by Riraifu** [comment]
My error message
```
Traceback (most recent call last):
  File "/mnt/SSD_4TB/user/code/PrefixEdit/my_gpt/train.py", line 95, in <module>
    main()
  File "/mnt/SSD_4TB/user/code/PrefixEdit/my_gpt/train.py", line 86, in main
    trainer.train()
  File "/home/user/miniconda3/envs/gptj/lib/python3.9/site-packages/transformers/trainer.py", line 1555, in train
    return inner_training_loop(
  File "/home/user/miniconda3/envs/gptj/lib/python3.9/site-packages/transformers/trainer.py", line 1860, in _inner_training_loop
    tr_loss_step = self.training_step(model, inputs)
  File "/home/user/miniconda3/envs/gptj/lib/python3.9/site-packages/transformers/trainer.py", line 2725, in training_step
    loss = self.compute_loss(model, inputs)
  File "/home/user/miniconda3/envs/gptj/lib/python3.9/site-packages/transformers/trainer.py", line 2748, in compute_loss
    outputs = model(**inputs)
  File "/home/user/miniconda3/envs/gptj/lib/python3.9/site-packages/torch/nn/modules/module.py", line 1501, in _call_impl
    return forward_call(*args, **kwargs)
  File "/home/user/miniconda3/envs/gptj/lib/python3.9/site-packages/deepspeed/utils/nvtx.py", line 15, in wrapped_fn
    ret_val = func(*args, **kwargs)
  File "/home/user/miniconda3/envs/gptj/lib/python3.9/site-packages/deepspeed/runtime/engine.py", line 1822, in forward
    loss = self.module(*inputs, **kwargs)
  File "/home/user/miniconda3/envs/gptj/lib/python3.9/site-packages/torch/nn/modules/module.py", line 1538, in _call_impl
    result = forward_call(*args, **kwargs)
  File "/mnt/SSD_4TB/user/code/PrefixEdit/my_gpt/prefix_edit.py", line 174, in forward
    out= self.llm(inputs_embeds=out, return_dict=True)
  File "/home/user/miniconda3/envs/gptj/lib/python3.9/site-packages/torch/nn/modules/module.py", line 1538, in _call_impl
    result = forward_call(*args, **kwargs)
  File "/home/user/miniconda3/envs/gptj/lib/python3.9/site-packages/transformers/models/gptj/modeling_gptj.py", line 853, in forward
    transformer_outputs = self.transformer(
  File "/home/user/miniconda3/envs/gptj/lib/python3.9/site-packages/torch/nn/modules/module.py", line 1538, in _call_impl
    result = forward_call(*args, **kwargs)
  File "/home/user/miniconda3/envs/gptj/lib/python3.9/site-packages/transformers/models/gptj/modeling_gptj.py", line 679, in forward
    outputs = block(
  File "/home/user/miniconda3/envs/gptj/lib/python3.9/site-packages/torch/nn/modules/module.py", line 1538, in _call_impl
    result = forward_call(*args, **kwargs)
  File "/home/user/miniconda3/envs/gptj/lib/python3.9/site-packages/transformers/models/gptj/modeling_gptj.py", line 323, in forward
    feed_forward_hidden_states = self.mlp(hidden_states)
  File "/home/user/miniconda3/envs/gptj/lib/python3.9/site-packages/torch/nn/modules/module.py", line 1538, in _call_impl
    result = forward_call(*args, **kwargs)
  File "/home/user/miniconda3/envs/gptj/lib/python3.9/site-packages/transformers/models/gptj/modeling_gptj.py", line 286, in forward
    hidden_states = self.fc_out(hidden_states)
  File "/home/user/miniconda3/envs/gptj/lib/python3.9/site-packages/torch/nn/modules/module.py", line 1527, in _call_impl
    result = hook(self, args)
  File "/home/user/miniconda3/envs/gptj/lib/python3.9/site-packages/deepspeed/utils/nvtx.py", line 15, in wrapped_fn
    ret_val = func(*args, **kwargs)
  File "/home/user/miniconda3/envs/gptj/lib/python3.9/site-packages/deepspeed/runtime/zero/parameter_offload.py", line 392, in _pre_forward_module_hook
    self.pre_sub_module_forward_function(module)
  File "/home/user/miniconda3/envs/gptj/lib/python3.9/site-packages/deepspeed/runtime/zero/parameter_offload.py", line 505, in pre_sub_module_forward_function
    param_coordinator.fetch_sub_module(sub_module, forward=prev_grad_state)
  File "/home/user/miniconda3/envs/gptj/lib/python3.9/site-packages/deepspeed/utils/nvtx.py", line 15, in wrapped_fn
    ret_val = func(*args, **kwargs)
  File "/home/user/miniconda3/envs/gptj/lib/python3.9/site-packages/torch/utils/_contextlib.py", line 115, in decorate_context
    return func(*args, **kwargs)
  File "/home/user/miniconda3/envs/gptj/lib/python3.9/site-packages/deepspeed/runtime/zero/partitioned_param_coordinator.py", line 379, in fetch_sub_module
    self.__all_gather_params(params_to_prefetch, forward)
  File "/home/user/miniconda3/envs/gptj/lib/python3.9/site-packages/deepspeed/utils/nvtx.py", line 15, in wrapped_fn
    ret_val = func(*args, **kwargs)
  File "/home/user/miniconda3/envs/gptj/lib/python3.9/site-packages/deepspeed/runtime/zero/partitioned_param_coordinator.py", line 428, in __all_gather_params
    self.__all_gather_params_(nonquantized_params, forward, quantize=self.zero_quantized_weights)
  File "/home/user/miniconda3/envs/gptj/lib/python3.9/site-packages/deepspeed/runtime/zero/partitioned_param_coordinator.py", line 446, in __all_gather_params_
    handle = partitioned_params[0].all_gather_coalesced(partitioned_params,
  File "/home/user/miniconda3/envs/gptj/lib/python3.9/site-packages/deepspeed/utils/nvtx.py", line 15, in wrapped_fn
    ret_val = func(*args, **kwargs)
  File "/home/user/miniconda3/envs/gptj/lib/python3.9/site-packages/deepspeed/runtime/zero/partition_parameters.py", line 1156, in all_gather_coalesced
    param_buffer = torch.empty(
torch.cuda.OutOfMemoryError: CUDA out of memory. Tried to allocate 256.00 MiB (GPU 2; 23.69 GiB total capacity; 21.30 GiB already allocated; 232.06 MiB free; 22.35 GiB reserved in total by PyTorch) If reserved memory is >> allocated memory try setting max_split_size_mb to avoid fragmentation.  See documentation for Memory Management and PYTORCH_CUDA_ALLOC_CONF
[2023-12-16 21:29:48,400] [INFO] [launch.py:315:sigkill_handler] Killing subprocess 22363
[2023-12-16 21:29:50,660] [INFO] [launch.py:315:sigkill_handler] Killing subprocess 22364
[2023-12-16 21:29:52,966] [INFO] [launch.py:315:sigkill_handler] Killing subprocess 22365
[2023-12-16 21:29:52,966] [INFO] [launch.py:315:sigkill_handler] Killing subprocess 22366
[2023-12-16 21:29:55,258] [ERROR] [launch.py:321:sigkill_handler] ['/home/user/miniconda3/envs/gptj/bin/python', '-u', 'train.py', '--local_rank=3', '--data', 'zsre', '--model', 'gpt-j-6b', '--prefixnet', 'prefixedit'] exits with return code = 1
```

**Comment by Riraifu** [comment]
I have found the solution. Because I serially called GPT-J twice in a forward propagation. Then, when calculating the gradient, DeepSpeed treats it as the computational cost of two 6B models, which is why I OOM. My solution is to merge the two serial runs of GPT-J into one run.
