### ISSUE TITLE
[BUG] FlopsProfiler.start_profile() hangs when using FSDP

### ISSUE THREAD

**Issue by mingtan2** [microsoft/DeepSpeed#5251]
**Describe the bug**
When following [this tutorial](https://www.deepspeed.ai/tutorials/flops-profiler/#example-training-workflow) to add FlopsProfiler to FSDP training pipeline, I found training got stuck at `start_profile()`. However, when using DDP, it works well. To be more specific, I am using PyTorch Lightning FSDP, and add FlopsProfiler into [on_train_batch_start](https://lightning.ai/docs/pytorch/stable/common/lightning_module.html#on-train-batch-start). Any help is appreciated! Thanks!

**To Reproduce**
```
class FlopsProfiler(Callback):
    def on_train_batch_start(self, trainer, pl_module, batch, batch_idx):
        self.prof = FlopsProfiler(pl_module.eps_model)
        self.prof.start_profile()

    def on_before_zero_grad(self, trainer, pl_module, optimizer):
        self.prof.stop_profile()
        self.prof.print_model_profile(profile_step=1, module_depth=0, detailed=False)
        self.prof.end_profile()
```

**Expected behavior**
Training gets stuck at [this line](https://github.com/microsoft/DeepSpeed/blob/master/deepspeed/profiling/flops_profiler/profiler.py#L81) inside `self.prof.start_profile()`.

**ds_report output**
```
[2024-03-10 13:45:21,656] [INFO] [real_accelerator.py:161:get_accelerator] Setting ds_accelerator to cuda (auto detect)
--------------------------------------------------
DeepSpeed C++/CUDA extension op report
--------------------------------------------------
NOTE: Ops not installed will be just-in-time (JIT) compiled at
      runtime if needed. Op compatibility means that your system
      meet the required dependencies to JIT install the op.
--------------------------------------------------
JIT compiled ops requires ninja
ninja .................. [OKAY]
--------------------------------------------------
op name ................ installed .. compatible
--------------------------------------------------
 [WARNING]  async_io requires the dev libaio .so object and headers but these were not found.
 [WARNING]  async_io: please install the libaio-dev package with apt
 [WARNING]  If libaio is already installed (perhaps from source), try setting the CFLAGS and LDFLAGS environment variables to where it can be found.
async_io ............... [NO] ....... [NO]
fused_adam ............. [NO] ....... [OKAY]
cpu_adam ............... [NO] ....... [OKAY]
cpu_adagrad ............ [NO] ....... [OKAY]
cpu_lion ............... [NO] ....... [OKAY]
 [WARNING]  Please specify the CUTLASS repo directory as environment variable $CUTLASS_PATH
evoformer_attn ......... [NO] ....... [NO]
fused_lamb ............. [NO] ....... [OKAY]
fused_lion ............. [NO] ....... [OKAY]
inference_core_ops ..... [NO] ....... [OKAY]
cutlass_ops ............ [NO] ....... [OKAY]
quantizer .............. [NO] ....... [OKAY]
ragged_device_ops ...... [NO] ....... [OKAY]
ragged_ops ............. [NO] ....... [OKAY]
random_ltd ............. [NO] ....... [OKAY]
 [WARNING]  sparse_attn requires a torch version >= 1.5 and < 2.0 but detected 2.1
 [WARNING]  using untested triton version (2.1.0), only 1.0.0 is known to be compatible
sparse_attn ............ [NO] ....... [NO]
spatial_inference ...... [NO] ....... [OKAY]
transformer ............ [NO] ....... [OKAY]
stochastic_transformer . [NO] ....... [OKAY]
transformer_inference .. [NO] ....... [OKAY]
--------------------------------------------------
DeepSpeed general environment info:
torch install path ............... ['/opt/venv/lib/python3.10/site-packages/torch']
torch version .................... 2.1.0
deepspeed install path ........... ['/opt/venv/lib/python3.10/site-packages/deepspeed']
deepspeed info ................... 0.12.6, unknown, unknown
torch cuda version ............... 12.2
torch hip version ................ None
nvcc version ..................... 12.2
deepspeed wheel compiled w. ...... torch 2.1, cuda 12.2
shared memory (/dev/shm) size .... 560.91 GB
```

**Screenshots**

**System info (please complete the following information):**
 - OS: [e.g. Ubuntu 18.04]
 - GPU count and types [e.g. two machines with x8 A100s each]
 - Interconnects (if applicable) [e.g., two machines connected with 100 Gbps IB]
 - Python version
 - Any other relevant info about your setup

**Launcher context**
Are you launching your experiment with the `deepspeed` launcher, MPI, or something else?

**Docker context**
Are you using a specific docker image that you can share?

**Additional context**

**Comment by ZejiaZheng** [comment]
Seeing the same issue in my training jobs as well.

**Comment by ZejiaZheng** [comment]
I resolved my issue. The problem for me is that I am only calling certain flops counter functions on rank 0. FlopsProfiler internally relies on `apply` and for fsdp `apply` summons all params first so needs to be called in all ranks.
