### ISSUE TITLE
[BUG]Deepspeed OOM out of CPU memory on A100 80Gx4. The more GPU use the more CPU memory ds occupy.

### ISSUE THREAD

**Issue by 66RING** [microsoft/DeepSpeed#5290]
**Describe the bug**
SFT llama2-70B on A100 80Gx4 1 machine with deepspeed stage 3. Out of CPU memory before it out of GPU memory.

**Log output**

```
              total        used        free      shared  buff/cache   available
Mem:          1.0Ti        38Gi       966Gi       278Mi       2.8Gi       966Gi
Swap:            0B          0B          0B
[2024-03-17 10:08:24,208] [INFO] [real_accelerator.py:191:get_accelerator] Setting ds_accelerator to cuda (auto detect)
[2024-03-17 10:08:26,219] [WARNING] [runner.py:202:fetch_hostfile] Unable to find hostfile, will proceed with training with local resources only.
[2024-03-17 10:08:26,248] [INFO] [runner.py:568:main] cmd = /opt/conda/bin/python -u -m deepspeed.launcher.launch --world_info=eyJsb2NhbGhvc3QiOiBbMCwgMSwgMiwgM119 --master_addr=127.0.0.1 --master_port=29500 --enable_each_rank_log=None main.py --train_data_path /root/datasets/pile/train_00_long_10w.jsonl --eval_data_path /root/datasets/pile/val_long.jsonl --data_split 2,4,4 --model_name_or_path /root/models/Llama-2-70b-chat-hf --sequence_parallel_size 1 --print_loss --dtype bf16 --model_max_position_embeddings 4096 --max_seq_len 4096 --eval_max_len 4096 --checkpoint_output_path ./all_trains/checkpoint --checkpoint_every 1000 --max_train_steps 100 --per_device_train_batch_size 1 --per_device_eval_batch_size 1 --learning_rate 9.65e-6 --weight_decay 0. --num_train_epochs 1 --gradient_accumulation_steps 1 --num_warmup_steps 0 --seed 1234 --gradient_checkpointing --zero_stage 3 --deepspeed --output_dir ./all_trains/100s --lr_scheduler_type cosine --rope_scaling_factor 32 --rope_scaling_type yarn
[2024-03-17 10:08:28,455] [INFO] [real_accelerator.py:191:get_accelerator] Setting ds_accelerator to cuda (auto detect)
[2024-03-17 10:08:30,306] [INFO] [launch.py:138:main] 0 NCCL_VERSION=2.11.4
[2024-03-17 10:08:30,307] [INFO] [launch.py:138:main] 0 CONTAINER_NCCL_INFO=/etc/nccl.conf
[2024-03-17 10:08:30,307] [INFO] [launch.py:145:main] WORLD INFO DICT: {'localhost': [0, 1, 2, 3]}
[2024-03-17 10:08:30,307] [INFO] [launch.py:151:main] nnodes=1, num_local_procs=4, node_rank=0
[2024-03-17 10:08:30,307] [INFO] [launch.py:162:main] global_rank_mapping=defaultdict(<class 'list'>, {'localhost': [0, 1, 2, 3]})
[2024-03-17 10:08:30,307] [INFO] [launch.py:163:main] dist_world_size=4
[2024-03-17 10:08:30,307] [INFO] [launch.py:165:main] Setting CUDA_VISIBLE_DEVICES=0,1,2,3
              total        used        free      shared  buff/cache   available
Mem:          1.0Ti        40Gi       964Gi       278Mi       2.8Gi       964Gi
Swap:            0B          0B          0B
[2024-03-17 10:08:33,018] [INFO] [real_accelerator.py:191:get_accelerator] Setting ds_accelerator to cuda (auto detect)
[2024-03-17 10:08:33,019] [INFO] [real_accelerator.py:191:get_accelerator] Setting ds_accelerator to cuda (auto detect)
[2024-03-17 10:08:33,064] [INFO] [real_accelerator.py:191:get_accelerator] Setting ds_accelerator to cuda (auto detect)
[2024-03-17 10:08:33,646] [INFO] [real_accelerator.py:191:get_accelerator] Setting ds_accelerator to cuda (auto detect)
/opt/conda/lib/python3.8/site-packages/transformers/deepspeed.py:23: FutureWarning: transformers.deepspeed module is deprecated and will be removed in a future version. Please import deepspeed modules directly from transformers.integrations
  warnings.warn(
/opt/conda/lib/python3.8/site-packages/transformers/deepspeed.py:23: FutureWarning: transformers.deepspeed module is deprecated and will be removed in a future version. Please import deepspeed modules directly from transformers.integrations
  warnings.warn(
[2024-03-17 10:08:35,363] [INFO] [comm.py:637:init_distributed] cdb=None
[2024-03-17 10:08:35,394] [INFO] [comm.py:637:init_distributed] cdb=None
[2024-03-17 10:08:35,394] [INFO] [comm.py:668:init_distributed] Initializing TorchBackend in DeepSpeed with backend nccl
/opt/conda/lib/python3.8/site-packages/transformers/deepspeed.py:23: FutureWarning: transformers.deepspeed module is deprecated and will be removed in a future version. Please import deepspeed modules directly from transformers.integrations
  warnings.warn(
[2024-03-17 10:08:35,445] [INFO] [comm.py:637:init_distributed] cdb=None
/opt/conda/lib/python3.8/site-packages/transformers/deepspeed.py:23: FutureWarning: transformers.deepspeed module is deprecated and will be removed in a future version. Please import deepspeed modules directly from transformers.integrations
  warnings.warn(
[2024-03-17 10:08:36,215] [INFO] [comm.py:637:init_distributed] cdb=None
......
[745]               total        used        free      shared  buff/cache   available
[746] Mem:          1.0Ti       991Gi       9.8Gi       470Mi       6.3Gi        13Gi
[747] Swap:            0B          0B          0B
...
[775] [2024-03-17 10:01:57,339] [INFO] [launch.py:316:sigkill_handler] Killing subprocess 70
[776] [2024-03-17 10:01:57,340] [INFO] [launch.py:316:sigkill_handler] Killing subprocess 71
...
```

and it use about 1TB of CPU memory.

```
[745]               total        used        free      shared  buff/cache   available
[746] Mem:          1.0Ti       991Gi       9.8Gi       470Mi       6.3Gi        13Gi
[747] Swap:            0B          0B          0B
```

**To Reproduce**

```bash
#!/bin/bash
# Copyright (c) Microsoft Corporation.
# SPDX-License-Identifier: Apache-2.0

# DeepSpeed Team
OUTPUT=$1
ZERO_STAGE=$2
if [ "$OUTPUT" == "" ]; then
    OUTPUT=./output_step1_llama2_7b
fi
if [ "$ZERO_STAGE" == "" ]; then
    ZERO_STAGE=3
fi
mkdir -p $OUTPUT

deepspeed main.py \
   --data_path Dahoas/rm-static Dahoas/full-hh-rlhf Dahoas/synthetic-instruct-gptj-pairwise yitingxie/rlhf-reward-datasets \
   --data_split 2,4,4 \
   --model_name_or_path meta-llama/Llama-2-70b-chat-hf \
   --per_device_train_batch_size 4 \
   --per_device_eval_batch_size 4 \
   --max_seq_len 512 \
   --learning_rate 9.65e-6 \
   --weight_decay 0. \
   --num_train_epochs 4  \
   --gradient_accumulation_steps 1 \
   --lr_scheduler_type cosine \
   --num_warmup_steps 0 \
   --seed 1234 \
   --gradient_checkpointing \
   --zero_stage $ZERO_STAGE \
   --deepspeed \
   --output_dir $OUTPUT
```
- submit the script above on cluster with 1 GPU attach.  **GPU OOM before CPU OOM**
- submit the script above on cluster with 4 GPU attach.  **CPU OOM before GPU OOM**

**Expected behavior**

same CPU memory occupy no matter 1 GPU or N GPU.

**ds_report output**
Please run `ds_report` to give us details about your setup.

```
--------------------------------------------------
DeepSpeed C++/CUDA extension op report
--------------------------------------------------
NOTE: Ops not installed will be just-in-time (JIT) compiled at
      runtime if needed. Op compatibility means that your system
      meet the required dependencies to JIT install the op.
--------------------------------------------------
JIT compiled ops requires ninja
ninja .................. [92m[OKAY][0m
--------------------------------------------------
op name ................ installed .. compatible
--------------------------------------------------
[93m [WARNING] [0m async_io requires the dev libaio .so object and headers but these were not found.
[93m [WARNING] [0m async_io: please install the libaio-dev package with apt
[93m [WARNING] [0m If libaio is already installed (perhaps from source), try setting the CFLAGS and LDFLAGS environment variables to where it can be found.
async_io ............... [93m[NO][0m ....... [93m[NO][0m
fused_adam ............. [93m[NO][0m ....... [92m[OKAY][0m
cpu_adam ............... [93m[NO][0m ....... [92m[OKAY][0m
cpu_adagrad ............ [93m[NO][0m ....... [92m[OKAY][0m
cpu_lion ............... [93m[NO][0m ....... [92m[OKAY][0m
[93m [WARNING] [0m Please specify the CUTLASS repo directory as environment variable $CUTLASS_PATH
evoformer_attn ......... [93m[NO][0m ....... [93m[NO][0m
fused_lamb ............. [93m[NO][0m ....... [92m[OKAY][0m
fused_lion ............. [93m[NO][0m ....... [92m[OKAY][0m
inference_core_ops ..... [93m[NO][0m ....... [92m[OKAY][0m
cutlass_ops ............ [93m[NO][0m ....... [92m[OKAY][0m
transformer_inference .. [93m[NO][0m ....... [92m[OKAY][0m
quantizer .............. [93m[NO][0m ....... [92m[OKAY][0m
ragged_device_ops ...... [93m[NO][0m ....... [92m[OKAY][0m
ragged_ops ............. [93m[NO][0m ....... [92m[OKAY][0m
random_ltd ............. [93m[NO][0m ....... [92m[OKAY][0m
[93m [WARNING] [0m sparse_attn requires a torch version >= 1.5 and < 2.0 but detected 2.0
[93m [WARNING] [0m using untested triton version (2.0.0), only 1.0.0 is known to be compatible
sparse_attn ............ [93m[NO][0m ....... [93m[NO][0m
spatial_inference ...... [93m[NO][0m ....... [92m[OKAY][0m
transformer ............ [93m[NO][0m ....... [92m[OKAY][0m
stochastic_transformer . [93m[NO][0m ....... [92m[OKAY][0m
--------------------------------------------------
DeepSpeed general environment info:
torch install path ............... ['/opt/conda/lib/python3.8/site-packages/torch']
torch version .................... 2.0.1+cu117
deepspeed install path ........... ['/opt/conda/lib/python3.8/site-packages/deepspeed']
deepspeed info ................... 0.14.0, unknown, unknown
torch cuda version ............... 11.7
torch hip version ................ None
nvcc version ..................... 11.6
deepspeed wheel compiled w. ...... torch 2.0, cuda 11.7
shared memory (/dev/shm) size .... 503.77 GB
```

**System info (please complete the following information):**
 - OS: Ubuntu 20.04
 - GPU count and types one machines with x4 A100s each
 - (if applicable) what [DeepSpeed-MII](https://github.com/microsoft/deepspeed-mii) version are you using: 0.14.0
 - (if applicable) Hugging Face Transformers/Accelerate/etc. versions
 - Python version: 
 - Any other relevant info about your setup

**Docker context**
Are you using a specific docker image that you can share?

**Additional context**

**Comment by shh2000** [comment]
similar question. here's some findings:

1. deepspeed's doc claimed in ZeRO-O3 with ZeRO.init context, params is copied(for DP) and transfered to GPU layer by layer, while O2 is not. 
2. i use 13B, A100 80G\*8, 1TB CPU memory to test. when O2, it use about 500 GB memory. 13B\*4Byte/param\*DP8=416GB, reasonable.
3. when using 500GB CPU memory(reduce 50% memory), CPU OOM
4. changing to O3, still CPU OOM.

so maybe we use O3 zero.init incorrectly, or deepspeed has a bug around here.

to your scenario, 70\*4\*4=1120GB>1TB, CPU OOM. maybe you can try load half layer(40 layer instead of 80 layer)? it likely to use 560+ GB memory, which does not cause CPU OOM

however, even half layers does not OOM, there's still the bug: **when loading and copying weights layer by layer, does deepspeed release the memory of former layers in O3?**

**Comment by shh2000** [comment]
> similar question. here's some findings:
> 
> 1. deepspeed's doc claimed in ZeRO-O3 with ZeRO.init context, params is copied(for DP) and transfered to GPU layer by layer, while O2 is not.
> 2. i use 13B, A100 80G*8, 1TB CPU memory to test. when O2, it use about 500 GB memory. 13B*4Byte/param*DP8=416GB, reasonable.
> 3. when using 500GB CPU memory(reduce 50% memory), CPU OOM
> 4. changing to O3, still CPU OOM.
> 
> so maybe we use O3 zero.init incorrectly, or deepspeed has a bug around here.
> 
> to your scenario, 70*4*4=1120GB>1TB, CPU OOM. maybe you can try load half layer(40 layer instead of 80 layer)? it likely to use 560+ GB memory, which does not cause CPU OOM
> 
> however, even half layers does not OOM, there's still the bug: **when loading and copying weights layer by layer, does deepspeed release the memory of former layers in O3?**

ref: https://deepspeed.readthedocs.io/en/latest/memory.html , grep "And often, it’s not even possible to buy GPUs with a lot of RAM (112GB GPU anybody?) since they simply don’t yet exist."

**Comment by 66RING** [comment]
> similar question. here's some findings:
> 
> 1. deepspeed's doc claimed in ZeRO-O3 with ZeRO.init context, params is copied(for DP) and transfered to GPU layer by layer, while O2 is not.
> 2. i use 13B, A100 80G*8, 1TB CPU memory to test. when O2, it use about 500 GB memory. 13B*4Byte/param*DP8=416GB, reasonable.
> 3. when using 500GB CPU memory(reduce 50% memory), CPU OOM
> 4. changing to O3, still CPU OOM.
> 
> so maybe we use O3 zero.init incorrectly, or deepspeed has a bug around here.
> 
> to your scenario, 70*4*4=1120GB>1TB, CPU OOM. maybe you can try load half layer(40 layer instead of 80 layer)? it likely to use 560+ GB memory, which does not cause CPU OOM
> 
> however, even half layers does not OOM, there's still the bug: **when loading and copying weights layer by layer, does deepspeed release the memory of former layers in O3?**

@shh2000 hi I have some new [findings](https://huggingface.co/docs/transformers/v4.36.1/en/main_classes/deepspeed#constructing-massive-models). and it works. You need to use `deepspeed.zero.init` to handle lager model. like

```python
        with deepspeed.zero.Init():
            model = AutoModelForCausalLM.from_config(config, trust_remote_code=True)

```

**Comment by 66RING** [comment]
And **directly load model to GPU works fine**. Use the `device_map` parameter like

```python
AutoModelForCausalLM.from_config(config, device_map="auto", trust_remote_code=True)
```
