### ISSUE TITLE
Issues using deepspeed transformer kernel

### ISSUE THREAD

**Issue by sriramiscool** [microsoft/DeepSpeed#589]
Hello, 
I have been training models using deepspeed to train bert models.
The code I use is adapted from bing bert example. 
I use --deepspeed_transformer_kernel=True when training and after training load the same model and perform prediction.

I am facing 4 issues when performing prediction using trained model:

Some minor changes made to the model and forward function:
    def forward(self, input_ids, valid_length=None,  masked_lm_labels=None,  embedding_mode=True):

1) When I load a deepspeed model without kernel into a model with transformer kernel (I verified that the weights loaded are exact by double transformation) the embedding generated by model with transformer kernel and without transformer kernels are very different.

2) When using model with transformer kernel the embeddings generated by 2 inputs, input_ids1.shape[1] = 16 and input_ids2.shape[1] = 128, and valid_length = [10], and input_ids1[:, :10] == input_ids2[:, :10] the embeddings generated are not the same they may vary at the first decimal itself.

3) For some awkward number for input_ids.shape[1] like 9: the embedding generated are all NANs.

4) When input_ids.shape[1] < 5 :  the program crashes with cuda error (does not display the error most of the time).

NOTE:
These issues do not exist if I use a model without deepspeed kernel.

Please let me know if this is expected and if so why and if not how can it be potentially fixed. Thanks

-----------------------------------------------------
**Below is code snippet (not complete) and the output:**
-----------------------------------------------------

def main():
    
    start = time.time()
    args = construct_arguments()
    #INITIALIZE MODEL WITH DEEPSPEED TRANFORMER KERNEL
    model_with_ds_tr_kernel, _ = prepare_model_optimizer(args)
    args.saved_embedding_path = os.path.join(args.output_dir, "embeddings",
            args.embedding_type)
    os.makedirs(args.saved_embedding_path, exist_ok=True)
    args.logger.info(f"Created directory to save embeddings: {args.saved_embedding_path}")

    if None in [args.load_training_checkpoint, args.load_checkpoint_id]:
        args.logger.info("load_training_checkpoint and load_checkpoint_id is missing.")
        sys.exit()
    #LOAD A SAVED MODEL
    global_step, global_data_samples, last_global_step_from_restore = load_checkpoint(args, model_with_ds_tr_kernel)

    #LOAD SAME MODEL BUT WITHOUT TRANSFORMER KERNEL
    from m5_transformers.models.bert import BertForPreTrainingPreLN
    model_no_ds_tr_kernel = BertForPreTrainingPreLN.from_pretrained("../conversion/dsmNoTK_500M_1024_spm")
    model_no_ds_tr_kernel.to("cuda")

    model_no_ds_tr_kernel.eval()
    model_with_ds_tr_kernel.eval()

    print("-----------------------------------ISSUE 1-------------------------------------------------")
    print("EMBEDDINGS DIFFERENT FOR MODEL WITH AND WITHOUT TRANSFORMER KERNEL")
    seq_len = 7
    ipid1 = torch.arange(512).view([1,512])
    ipid1 += 1000
    ipid1[:,seq_len:] = 3
    ipid1 = ipid1.to("cuda")
    valid_len = torch.tensor([seq_len], dtype=torch.long)
    valid_len = valid_len.to("cuda")
    with torch.no_grad():
        s1,p1 = model_with_ds_tr_kernel.network(ipid1, valid_len, embedding_mode=True)
        s2,p2 = model_no_ds_tr_kernel(ipid1, valid_len, embedding_mode=True)
    s1 = s1.cpu().numpy()[:,:seq_len]
    s2 = s2.cpu().numpy()[:,:seq_len]
    print("EMBEDDINGS GENERATED SAME: {}".format(np.allclose(s1,s2, atol=1e-4)))
    print("EMBEDDINGS ABSOLUTE MEAN ERROR: {}".format(np.abs(s1-s2).mean()))

    print("-----------------------------------ISSUE 2-------------------------------------------------")
    print("EMBEDDINGS FOR MODEL WITH TRANSFORMER KERNEL: 2 INPUTS DIFFERENT SIZE BATCH BUT SAME DATA")
    ipid2 = torch.arange(16).view([1,16])
    ipid2 += 1000
    ipid2[:,seq_len:] = 3
    ipid2 = ipid2.to("cuda")
    valid_len = torch.tensor([seq_len], dtype=torch.long)
    valid_len = valid_len.to("cuda")
    with torch.no_grad():
        s1,p1 = model_with_ds_tr_kernel.network(ipid1, valid_len, embedding_mode=True)
        s2,p2 = model_with_ds_tr_kernel.network(ipid2, valid_len, embedding_mode=True)
    s1 = s1.cpu().numpy()[:,:seq_len]
    s2 = s2.cpu().numpy()[:,:seq_len]
    print("EMBEDDINGS GENERATED SAME: {}".format(np.allclose(s1,s2, atol=1e-4)))
    print("EMBEDDINGS ABSOLUTE MEAN ERROR: {}".format(np.abs(s1-s2).mean()))

    print("-----------------------------------ISSUE 3-------------------------------------------------")
    print("EMBEDDINGS FOR MODEL WITH TRANSFORMER KERNEL: INPUTS WITH ODD BATCH LENGTH")
    ipid1 = torch.arange(9).view([1,9])
    ipid1 += 1000
    ipid1[:,seq_len:] = 3
    ipid1 = ipid1.to("cuda")
    valid_len = torch.tensor([seq_len], dtype=torch.long)
    valid_len = valid_len.to("cuda")
    with torch.no_grad():
        s1,p1 = model_with_ds_tr_kernel.network(ipid1, valid_len, embedding_mode=True)
    s1 = s1.cpu().numpy()[:,:seq_len]
    print("EMBEDDINGS GENERATED : {}".format(s1))

    print("-----------------------------------ISSUE 4-------------------------------------------------")
    print("EMBEDDINGS FOR MODEL WITH TRANSFORMER KERNEL: INPUTS WITH VERY SMALL BATCH LENGTH")
    seq_len = 2
    ipid1 = torch.arange(3).view([1,3])
    ipid1 += 1000
    ipid1[:,seq_len:] = 3
    ipid1 = ipid1.to("cuda")
    valid_len = torch.tensor([seq_len], dtype=torch.long)
    valid_len = valid_len.to("cuda")
    print("SYSTEM HAS CRASHED IF NOTHING IS PRINTED AFTER THIS...")
    with torch.no_grad():
        s1,p1 = model_with_ds_tr_kernel.network(ipid1, valid_len, embedding_mode=True)
    s1 = s1.cpu().numpy()[:,:seq_len]
    print("EMBEDDINGS GENERATED : {}".format(s1))

    elapsed = time.time() - start
    logger = args.logger
    logger.info(f"Elapsed time: {elapsed} seconds")

if __name__ == "__main__":
    main()

**OUTPUT:**
-----------------------------------ISSUE 1-------------------------------------------------
EMBEDDINGS DIFFERENT FOR MODEL WITH AND WITHOUT TRANSFORMER KERNEL
EMBEDDINGS GENERATED SAME: False
EMBEDDINGS ABSOLUTE MEAN ERROR: 0.9891793131828308
-----------------------------------ISSUE 2-------------------------------------------------
EMBEDDINGS FOR MODEL WITH TRANSFORMER KERNEL: 2 INPUTS DIFFERENT SIZE BATCH BUT SAME DATA
EMBEDDINGS GENERATED SAME: False
EMBEDDINGS ABSOLUTE MEAN ERROR: 0.010894775390625
-----------------------------------ISSUE 3-------------------------------------------------
EMBEDDINGS FOR MODEL WITH TRANSFORMER KERNEL: INPUTS WITH ODD BATCH LENGTH
EMBEDDINGS GENERATED : [[[nan nan nan ... nan nan nan]
  [nan nan nan ... nan nan nan]
  [nan nan nan ... nan nan nan]
  ...
  [nan nan nan ... nan nan nan]
  [nan nan nan ... nan nan nan]
  [nan nan nan ... nan nan nan]]]
-----------------------------------ISSUE 4-------------------------------------------------
EMBEDDINGS FOR MODEL WITH TRANSFORMER KERNEL: INPUTS WITH VERY SMALL BATCH LENGTH
SYSTEM HAS CRASHED IF NOTHING IS PRINTED AFTER THIS...

**Comment by RezaYazdaniAminabadi** [comment]
Hi @sriramiscool 

Thanks for pointing out these issues. 
We are aware of some of these issues and are constantly working on fixing them asap. For the last two issues you mentioned, I pushed a PR, https://github.com/microsoft/DeepSpeed/pull/587. Could you please check it the issues are resolved?
I also think this PR would solve your first issue. But, please let me know if it does not and I further investigate this.
I am not sure if I understand the second issue. Are you saying that the data only exists in [:, :10] and the rest is zero? Can you please explain this further? 

Thanks.
Reza

**Comment by szhengac** [comment]
@RezaYazdaniAminabadi Yes. We mean the results become very different when we add more paddings. We expected a small difference due to masked softmax, but the difference is actually non-negligible.

**Comment by RezaYazdaniAminabadi** [comment]
Can you try something here? Pad the mask to be a high negative value (like -10000) for the part of the input that is padded, and let's see if the results are still too much different. This will reduce the effect of this padded part when going through the softmax by making them a high negative value, which result in near-zero softmax output.

**Comment by RezaYazdaniAminabadi** [comment]
Also, let's use random values on the padded input instead of zero (this should not impact the result).
Thanks,
Reza

**Comment by szhengac** [comment]
> Can you try something here? Pad the mask to be a high negative value (like -10000) for the part of the input that is padded, and let's see if the results are still too much different. This will reduce the effect of this padded part when going through the softmax by making them a high negative value, which result in near-zero softmax output.

We did this in the model.

**Comment by szhengac** [comment]
We converted 1 to 0 and 0 to -10000 in the mask in the model.

**Comment by RezaYazdaniAminabadi** [comment]
I see, thanks for pointing this.
Would you mind double-checking this with the new PR (https://github.com/microsoft/DeepSpeed/pull/587)? 
For the padding, I have seen similar issue and there seems to be a problem when all the padded data are zeros or ones (similar). I could solve that by changing the padding data to random values. I wonder if the same behavior exists in your testing.
Looking forward to seeing your result.
Thanks,
Reza

**Comment by sriramiscool** [comment]
Thank you for pointing to the PR, we will try it out and let you know soon.
And we did try random padding tokens as well, the result is still the same.

Thank you,
Sriram

**Comment by sriramiscool** [comment]
Hello,
I tried the PR.
Looks like it fixed the Issue 3 and Issue 4 but the Issue 1 and 2 still seem exist.

Below is the output for the same code as earlier using the PR you pointed me to. Please let me know what can be done next.
Thanks.

-----------------------------------ISSUE 1-------------------------------------------------
EMBEDDINGS DIFFERENT FOR MODEL WITH AND WITHOUT TRANSFORMER KERNEL
EMBEDDINGS GENERATED SAME: False
EMBEDDINGS ABSOLUTE MEAN ERROR: 0.9900880455970764
-----------------------------------ISSUE 2-------------------------------------------------
EMBEDDINGS FOR MODEL WITH TRANSFORMER KERNEL: 2 INPUTS DIFFERENT SIZE BATCH BUT SAME DATA
EMBEDDINGS GENERATED SAME: False
EMBEDDINGS ABSOLUTE MEAN ERROR: 0.0124969482421875
-----------------------------------ISSUE 3-------------------------------------------------
EMBEDDINGS FOR MODEL WITH TRANSFORMER KERNEL: INPUTS WITH ODD BATCH LENGTH
EMBEDDINGS GENERATED : [[[ -3.377   -1.132    3.041  ...  -3.508   -3.05    -4.23  ]
  [ -4.402    1.008    1.122  ...  -1.098   -0.9053  -1.595 ]
  [ -2.691    2.217    1.026  ...   7.35     4.28    -3.467 ]
  ...
  [ -0.654   -1.821    2.586  ...   3.568    6.945   -0.9917]
  [ -2.203   -3.877   -4.36   ... -19.33    -0.8467  -0.373 ]
  [  5.758   -4.156    5.67   ...  -6.32   -12.195    0.2412]]]
-----------------------------------ISSUE 4-------------------------------------------------
EMBEDDINGS FOR MODEL WITH TRANSFORMER KERNEL: INPUTS WITH VERY SMALL BATCH LENGTH
SYSTEM HAS CRASHED IF NOTHING IS PRINTED AFTER THIS...
EMBEDDINGS GENERATED : [[[-2.16   -1.155   3.951  ... -3.059  -2.559  -2.781 ]
  [-2.053   1.162   2.062  ... -1.6045 -2.066  -1.168 ]]]

**Comment by sriramiscool** [comment]
Also found some interesting pattern with issue 2 actually.
By varying lengths we observe that is input1.shape[1] = x and 
input1.shape[1]-(16-input1.shape[1]%16) <= input2.shape[1] <= input1.shape[1]+(input1.shape[1]%16)
Then the embeddings are the same with no diff. 
Further, for input2.shape[1] \in range (129, 160) or range(257, 336) the different in embeddings is super large and for others is the absolute mean difference is in 0.01 range.

Below is the code snippet and result.
THanks

    print("-----------------------------------ISSUE 2-------------------------------------------------")
    print("EMBEDDINGS FOR MODEL WITH TRANSFORMER KERNEL: 2 INPUTS DIFFERENT SIZE BATCH BUT SAME DATA")
    seq_len = 9
    ipid2 = torch.arange(128).view([1,128])
    ipid2 += 1000
    ipid2[:,seq_len:] = torch.randint(10,32000,(128-seq_len,))
    ipid2 = ipid2.to("cuda")
    for cnrt in range(9,512):
        ipid1 = torch.arange(cnrt).view([1,cnrt])
        ipid1 += 1000
        ipid1[:,seq_len:] = torch.randint(10,32000,(cnrt-seq_len,))
        ipid1 = ipid1.to("cuda")
        valid_len = torch.tensor([seq_len], dtype=torch.long)
        valid_len = valid_len.to("cuda")
        with torch.no_grad():
            s1,p1 = model_with_ds_tr_kernel.network(ipid1, valid_len, embedding_mode=True)
            s2,p2 = model_with_ds_tr_kernel.network(ipid2, valid_len, embedding_mode=True)
        s1 = s1.cpu().numpy()[:,:seq_len]
        s2 = s2.cpu().numpy()[:,:seq_len]
        print("EMBEDDINGS GENERATED SAME FOR PADDED SEQ LENS 128 and {}: {}".format(cnrt, np.allclose(s1,s2, atol=1e-4)))
        print("EMBEDDINGS ABSOLUTE MEAN ERROR: {}".format(np.abs(s1-s2).mean()))

**OUTPUT**:
.......
EMBEDDINGS ABSOLUTE MEAN ERROR: 0.01132965087890625
EMBEDDINGS GENERATED SAME FOR PADDED SEQ LENS 128 and 108: False
EMBEDDINGS ABSOLUTE MEAN ERROR: 0.01132965087890625
EMBEDDINGS GENERATED SAME FOR PADDED SEQ LENS 128 and 109: False
EMBEDDINGS ABSOLUTE MEAN ERROR: 0.01132965087890625
EMBEDDINGS GENERATED SAME FOR PADDED SEQ LENS 128 and 110: False
EMBEDDINGS ABSOLUTE MEAN ERROR: 0.01132965087890625
EMBEDDINGS GENERATED SAME FOR PADDED SEQ LENS 128 and 111: False
EMBEDDINGS ABSOLUTE MEAN ERROR: 0.01132965087890625
EMBEDDINGS GENERATED SAME FOR PADDED SEQ LENS 128 and 112: False
EMBEDDINGS ABSOLUTE MEAN ERROR: 0.01132965087890625
EMBEDDINGS GENERATED SAME FOR PADDED SEQ LENS 128 and 113: True
EMBEDDINGS ABSOLUTE MEAN ERROR: 0.0
EMBEDDINGS GENERATED SAME FOR PADDED SEQ LENS 128 and 114: True
EMBEDDINGS ABSOLUTE MEAN ERROR: 0.0
EMBEDDINGS GENERATED SAME FOR PADDED SEQ LENS 128 and 115: True
EMBEDDINGS ABSOLUTE MEAN ERROR: 0.0
EMBEDDINGS GENERATED SAME FOR PADDED SEQ LENS 128 and 116: True
EMBEDDINGS ABSOLUTE MEAN ERROR: 0.0
EMBEDDINGS GENERATED SAME FOR PADDED SEQ LENS 128 and 117: True
EMBEDDINGS ABSOLUTE MEAN ERROR: 0.0
EMBEDDINGS GENERATED SAME FOR PADDED SEQ LENS 128 and 118: True
EMBEDDINGS ABSOLUTE MEAN ERROR: 0.0
EMBEDDINGS GENERATED SAME FOR PADDED SEQ LENS 128 and 119: True
EMBEDDINGS ABSOLUTE MEAN ERROR: 0.0
EMBEDDINGS GENERATED SAME FOR PADDED SEQ LENS 128 and 120: True
EMBEDDINGS ABSOLUTE MEAN ERROR: 0.0
EMBEDDINGS GENERATED SAME FOR PADDED SEQ LENS 128 and 121: True
EMBEDDINGS ABSOLUTE MEAN ERROR: 0.0
EMBEDDINGS GENERATED SAME FOR PADDED SEQ LENS 128 and 122: True
EMBEDDINGS ABSOLUTE MEAN ERROR: 0.0
EMBEDDINGS GENERATED SAME FOR PADDED SEQ LENS 128 and 123: True
EMBEDDINGS ABSOLUTE MEAN ERROR: 0.0
EMBEDDINGS GENERATED SAME FOR PADDED SEQ LENS 128 and 124: True
EMBEDDINGS ABSOLUTE MEAN ERROR: 0.0
EMBEDDINGS GENERATED SAME FOR PADDED SEQ LENS 128 and 125: True
EMBEDDINGS ABSOLUTE MEAN ERROR: 0.0
EMBEDDINGS GENERATED SAME FOR PADDED SEQ LENS 128 and 126: True
EMBEDDINGS ABSOLUTE MEAN ERROR: 0.0
EMBEDDINGS GENERATED SAME FOR PADDED SEQ LENS 128 and 127: True
EMBEDDINGS ABSOLUTE MEAN ERROR: 0.0
EMBEDDINGS GENERATED SAME FOR PADDED SEQ LENS 128 and 128: True
EMBEDDINGS ABSOLUTE MEAN ERROR: 0.0
EMBEDDINGS GENERATED SAME FOR PADDED SEQ LENS 128 and 129: False
EMBEDDINGS ABSOLUTE MEAN ERROR: 6.85546875
EMBEDDINGS GENERATED SAME FOR PADDED SEQ LENS 128 and 130: False
EMBEDDINGS ABSOLUTE MEAN ERROR: 7.1875
EMBEDDINGS GENERATED SAME FOR PADDED SEQ LENS 128 and 131: False
EMBEDDINGS ABSOLUTE MEAN ERROR: 7.359375
EMBEDDINGS GENERATED SAME FOR PADDED SEQ LENS 128 and 132: False
EMBEDDINGS ABSOLUTE MEAN ERROR: 6.7890625
EMBEDDINGS GENERATED SAME FOR PADDED SEQ LENS 128 and 133: False
EMBEDDINGS ABSOLUTE MEAN ERROR: 7.8828125
EMBEDDINGS GENERATED SAME FOR PADDED SEQ LENS 128 and 134: False
EMBEDDINGS ABSOLUTE MEAN ERROR: 7.36328125
EMBEDDINGS GENERATED SAME FOR PADDED SEQ LENS 128 and 135: False
EMBEDDINGS ABSOLUTE MEAN ERROR: 7.67578125
..........
..........
EMBEDDINGS GENERATED SAME FOR PADDED SEQ LENS 128 and 158: False
EMBEDDINGS ABSOLUTE MEAN ERROR: 6.34375
EMBEDDINGS GENERATED SAME FOR PADDED SEQ LENS 128 and 159: False
EMBEDDINGS ABSOLUTE MEAN ERROR: 5.78515625
EMBEDDINGS GENERATED SAME FOR PADDED SEQ LENS 128 and 160: False
EMBEDDINGS ABSOLUTE MEAN ERROR: 4.57421875
EMBEDDINGS GENERATED SAME FOR PADDED SEQ LENS 128 and 161: False
EMBEDDINGS ABSOLUTE MEAN ERROR: 0.0118865966796875
EMBEDDINGS GENERATED SAME FOR PADDED SEQ LENS 128 and 162: False
EMBEDDINGS ABSOLUTE MEAN ERROR: 0.0118865966796875
EMBEDDINGS GENERATED SAME FOR PADDED SEQ LENS 128 and 163: False
EMBEDDINGS ABSOLUTE MEAN ERROR: 0.0118865966796875
EMBEDDINGS GENERATED SAME FOR PADDED SEQ LENS 128 and 164: False
EMBEDDINGS ABSOLUTE MEAN ERROR: 0.0118865966796875
EMBEDDINGS GENERATED SAME FOR PADDED SEQ LENS 128 and 165: False
EMBEDDINGS ABSOLUTE MEAN ERROR: 0.0118865966796875
EMBEDDINGS GENERATED SAME FOR PADDED SEQ LENS 128 and 166: False
EMBEDDINGS ABSOLUTE MEAN ERROR: 0.0118865966796875
EMBEDDINGS GENERATED SAME FOR PADDED SEQ LENS 128 and 167: False
EMBEDDINGS ABSOLUTE MEAN ERROR: 0.0118865966796875
EMBEDDINGS GENERATED SAME FOR PADDED SEQ LENS 128 and 168: False
EMBEDDINGS ABSOLUTE MEAN ERROR: 0.0118865966796875
EMBEDDINGS GENERATED SAME FOR PADDED SEQ LENS 128 and 169: False
EMBEDDINGS ABSOLUTE MEAN ERROR: 0.0118865966796875
EMBEDDINGS GENERATED SAME FOR PADDED SEQ LENS 128 and 170: False
............
............
EMBEDDINGS GENERATED SAME FOR PADDED SEQ LENS 128 and 253: False
EMBEDDINGS ABSOLUTE MEAN ERROR: 0.011138916015625
EMBEDDINGS GENERATED SAME FOR PADDED SEQ LENS 128 and 254: False
EMBEDDINGS ABSOLUTE MEAN ERROR: 0.011138916015625
EMBEDDINGS GENERATED SAME FOR PADDED SEQ LENS 128 and 255: False
EMBEDDINGS ABSOLUTE MEAN ERROR: 0.011138916015625
EMBEDDINGS GENERATED SAME FOR PADDED SEQ LENS 128 and 256: False
EMBEDDINGS ABSOLUTE MEAN ERROR: 0.011138916015625
EMBEDDINGS GENERATED SAME FOR PADDED SEQ LENS 128 and 257: False
EMBEDDINGS ABSOLUTE MEAN ERROR: 6.61328125
EMBEDDINGS GENERATED SAME FOR PADDED SEQ LENS 128 and 258: False
EMBEDDINGS ABSOLUTE MEAN ERROR: 7.0859375
EMBEDDINGS GENERATED SAME FOR PADDED SEQ LENS 128 and 259: False
EMBEDDINGS ABSOLUTE MEAN ERROR: 7.296875
EMBEDDINGS GENERATED SAME FOR PADDED SEQ LENS 128 and 260: False
EMBEDDINGS ABSOLUTE MEAN ERROR: 7.16796875
EMBEDDINGS GENERATED SAME FOR PADDED SEQ LENS 128 and 261: False
EMBEDDINGS ABSOLUTE MEAN ERROR: 7.06640625
EMBEDDINGS GENERATED SAME FOR PADDED SEQ LENS 128 and 262: False
EMBEDDINGS ABSOLUTE MEAN ERROR: 7.5625
EMBEDDINGS GENERATED SAME FOR PADDED SEQ LENS 128 and 263: False
EMBEDDINGS ABSOLUTE MEAN ERROR: 7.78515625
EMBEDDINGS GENERATED SAME FOR PADDED SEQ LENS 128 and 264: False
EMBEDDINGS ABSOLUTE MEAN ERROR: 7.13671875
....................
....................
EMBEDDINGS GENERATED SAME FOR PADDED SEQ LENS 128 and 332: False
EMBEDDINGS ABSOLUTE MEAN ERROR: 7.33203125
EMBEDDINGS GENERATED SAME FOR PADDED SEQ LENS 128 and 333: False
EMBEDDINGS ABSOLUTE MEAN ERROR: 7.0546875
EMBEDDINGS GENERATED SAME FOR PADDED SEQ LENS 128 and 334: False
EMBEDDINGS ABSOLUTE MEAN ERROR: 6.6328125
EMBEDDINGS GENERATED SAME FOR PADDED SEQ LENS 128 and 335: False
EMBEDDINGS ABSOLUTE MEAN ERROR: 7.046875
EMBEDDINGS GENERATED SAME FOR PADDED SEQ LENS 128 and 336: False
EMBEDDINGS ABSOLUTE MEAN ERROR: 4.5546875
EMBEDDINGS GENERATED SAME FOR PADDED SEQ LENS 128 and 337: False
EMBEDDINGS ABSOLUTE MEAN ERROR: 0.01085662841796875
EMBEDDINGS GENERATED SAME FOR PADDED SEQ LENS 128 and 338: False
EMBEDDINGS ABSOLUTE MEAN ERROR: 0.01085662841796875
EMBEDDINGS GENERATED SAME FOR PADDED SEQ LENS 128 and 339: False
EMBEDDINGS ABSOLUTE MEAN ERROR: 0.01085662841796875
EMBEDDINGS GENERATED SAME FOR PADDED SEQ LENS 128 and 340: False
EMBEDDINGS ABSOLUTE MEAN ERROR: 0.01085662841796875
EMBEDDINGS GENERATED SAME FOR PADDED SEQ LENS 128 and 341: False
EMBEDDINGS ABSOLUTE MEAN ERROR: 0.01085662841796875
EMBEDDINGS GENERATED SAME FOR PADDED SEQ LENS 128 and 342: False
EMBEDDINGS ABSOLUTE MEAN ERROR: 0.01085662841796875
............................
............................
EMBEDDINGS GENERATED SAME FOR PADDED SEQ LENS 128 and 511: False
EMBEDDINGS ABSOLUTE MEAN ERROR: 0.0116729736328125

**Comment by RezaYazdaniAminabadi** [comment]
Hi @sriramiscool 

Thanks for checking this. And this behavior is for sure strange.
I have updated the branch more today. Could you give it another try?
Also, if you can let me know of the model configuration that you are testing and what sequence-length you are using and which part is padded, I can solve this faster.
Thanks,
Reza

**Comment by sriramiscool** [comment]
Sure, I can do that. Thanks.

And other details:
Model max sequence length: 512
At the time of input in the code I pasted earlier: 
    seq_len = 9
    ipid2 = torch.arange(128).view([1,128])
input 2 array length is 128 but the valid sequence length is 9, rest of the tokens are random tokens (as you suggested earlier).
input 1 array length I varried from 9 to 512.

The configurations used:
DEEPSPEED CONFIG:
{
  "train_batch_size": 16384,
  "train_micro_batch_size_per_gpu": 128,
  "steps_per_print": 1000,
  "prescale_gradients": false,
  "zero_optimization": {
    "stage": 2
  },
  "zero_allow_untested_optimizer": true,
  "optimizer": {
    "type": "LANS",
    "params": {
      "lr": 0.0001,
      "weight_decay": 0.01,
      "bias_correction": true,
      "eps": 0.000001
    }
  },
  "gradient_clipping": 1,
  "wall_clock_breakdown": false,
  "fp16": {
    "enabled": true,
    "loss_scale": 0,
    "initial_scale_power": 20,
    "loss_scale_window": 1000
  }
}

model config:
{
  "name": "bert_500M_1024",
  "bert_token_file": "bert_asin.model",
  "bert_model_config": {
    "vocab_size_or_config_json_file": 32003,
    "hidden_size": 1024,
    "num_hidden_layers": 38,
    "num_attention_heads": 16,
    "intermediate_size": 4096,
    "hidden_act": "gelu",
    "hidden_dropout_prob": 0.1,
    "attention_probs_dropout_prob": 0.1,
    "max_position_embeddings": 512,
    "initializer_range": 0.02
  },
  "data": {
    "mixed_seq_datasets": {
      "512": {
        ...
        }
    }
  },
  "mixed_seq_training": {
    "128": {
      "warmup_proportion": 0.05,
      "const_proportion": 0.25,
      "learning_rate": 0.003,
      "num_workers": 2,
      "total_training_steps": 112500
    },
    "512": {
      "warmup_proportion": 0.025,
      "const_proportion": 0.125,
      "learning_rate": 0.003,
      "num_workers": 2,
      "total_training_steps": 12500
    }
  }
}

Other command line parameters:
CUDA_VISIBLE_DEVICES=0 deepspeed deepspeed_predict_test.py \
--cf model_config.json \
--max_seq_length 512 \
--output_dir $OUTPUT_DIR \
--deepspeed \
--deepspeed_transformer_kernel \
--job_name $JOB_NAME \
--deepspeed_config deepspeed_config.json \
--load_training_checkpoint chkpt_folder \
--load_checkpoint_id model1 \
--attention_dropout_checkpoint \
--log_file ${JOB_NAME}.log

**Comment by sriramiscool** [comment]
Hello,
I tried the latest commit and looks like the super large difference I was seeing like these:
"
EMBEDDINGS GENERATED SAME FOR PADDED SEQ LENS 128 and 262: False
EMBEDDINGS ABSOLUTE MEAN ERROR: 7.5625
EMBEDDINGS GENERATED SAME FOR PADDED SEQ LENS 128 and 263: False
EMBEDDINGS ABSOLUTE MEAN ERROR: 7.78515625
EMBEDDINGS GENERATED SAME FOR PADDED SEQ LENS 128 and 264: False
EMBEDDINGS ABSOLUTE MEAN ERROR: 7.13671875
"

are gone. And all differences are of order 0.01. And the issue 1 still persists.

THanks

**Comment by RezaYazdaniAminabadi** [comment]
Okay, cool. So, there is only one issue remaining. I will work on it and let you know.

Thanks
Reza

**Comment by sriramiscool** [comment]
I guess. But, would be nice if in  issue 2 the difference is of the order
0.0001 which is what I see in model without deepspeed kernel.

And thanks a lot. :)

**Comment by sriramiscool** [comment]
Hello @RezaYazdaniAminabadi ,
Wondering if there are any updates.

Thanks,
Sriram

**Comment by RezaYazdaniAminabadi** [comment]
Hey @sriramiscool 
I got distracted by some other work. I will come back to this very soon.

Thanks,
Reza

**Comment by sriramiscool** [comment]
thanks a lot 👍

**Comment by RezaYazdaniAminabadi** [comment]
Hi @sriramiscool 

I still cannot repro your first issue! I am not sure what model checkpoint you are using to load the weights of transformer kernel. We have done this previously for the huggingface models, and it gave us the same result. You can find the way we convert the model [here](https://github.com/microsoft/DeepSpeedExamples/blob/master/BingBertSquad/convert_bert_ckpt_to_deepspeed.py).
Can you please provide me some script for the way you are loading weights from the model into the transformer kernel? 

Thanks.
Reza

**Comment by sriramiscool** [comment]
Hi @RezaYazdaniAminabadi 
Thanks for getting back, I have created a small standalone script to test just issue 1.
Strangely I am getting a different issue here.
I am attaching the files (changing type from py to txt) here and pasting the output here.

BertLayer: [bert_layers.txt](https://github.com/microsoft/DeepSpeed/files/5699901/bert_layers.txt)
TestRun code: [deepspeed_transformer_test.txt](https://github.com/microsoft/DeepSpeed/files/5699902/deepspeed_transformer_test.txt)


Quick logic of the code and summary:
We create 2 layers : one DeepspeedTransformerLayer (DST) and another BertLayer (BL)
Next, create an embedding layer to generate random embedding as input to these layers.
Next, pass random vector to the embedding layer to generate embedding
Finally, pass the embeddings and masks (zero tensor) to both the layers.
Strangely the output of DST has NANs and BL is fine.
Not sure why I am seeing NANs, will be great if you can help be fix this too. Thanks

Output:
DeepSpeed Transformer config is  {'layer_id': 0, 'batch_size': 128, 'hidden_size': 1024, 'intermediate_size': 4096, 'heads': 16, 'attn_dropout_ratio': 0.1, 'hidden_dropout_ratio': 0.1, 'num_hidden_layers': 1, 'initializer_range': 0.02, 'fp16': True, 'pre_layer_norm': True, 'local_rank': -1, 'seed': 42, 'normalize_invertible': False, 'gelu_checkpoint': False, 'adjust_init_range': True, 'test_gemm': False, 'training': True, 'is_grad_enabled': True, 'attn_dropout_checkpoint': False, 'stochastic_mode': False}
Using ~/.cache/torch_extensions as PyTorch extensions root...
Detected CUDA files, patching ldflags
Emitting ninja build file ~/.cache/torch_extensions/transformer/build.ninja...
Building extension module transformer...
Allowing ninja to set a default number of workers... (overridable by setting the environment variable MAX_JOBS=N)
ninja: no work to do.
Loading extension module transformer...
Time to load transformer op: 0.1545085906982422 seconds
layer #0 is created with date type [half].
Embeddings generated using deepspeed model with transformer kernel:
tensor([[[nan, nan, nan,  ..., nan, nan, nan],
         [nan, nan, nan,  ..., nan, nan, nan],
         [nan, nan, nan,  ..., nan, nan, nan],
         ...,
         [0., 0., 0.,  ..., 0., 0., 0.],
         [0., 0., 0.,  ..., 0., 0., 0.],
         [0., 0., 0.,  ..., 0., 0., 0.]]], device='cuda:0')
Embeddings generated using bert transformer:
tensor([[[-1.1806,  1.5912, -1.6555,  ..., -0.4264, -0.5958, -1.7613],
         [-0.5481, -0.8406,  1.0613,  ..., -2.9294,  0.6937, -1.9304],
         [-0.4797, -1.3884,  0.0496,  ..., -0.7242,  1.3464, -0.1275],
         ...,
         [ 0.4223,  0.3089,  1.7952,  ...,  0.2685, -1.9444, -0.5416],
         [-0.1111,  0.1745, -0.6499,  ..., -0.9291,  1.0662, -1.0272],
         [-1.8118,  1.5704,  0.4855,  ..., -0.1584, -0.9928, -1.0782]]],
       device='cuda:0')
MAE between two embeddings: nan


Thanks,
Sriram

**Comment by RezaYazdaniAminabadi** [comment]
Hi @sriramiscool 

Thanks for providing the scripts. 
I have tried this with one of our test units, trying to do the same thing you have done in your test-bench and I could repro the same issue. The important problem I see is that you want to send fp32 values to the kernel whereas configuring it as fp16. I think PyTorch does the conversion itself, however, we have not such checking when passing the inputs to the kernel. I assume the main problem of seeing NaNs is reading fp16 values of the fp32 input-matrix. 
I have done some changes to the __run_forward__ function in tests/unit/test_cuda_forward.py file at this [branch](https://github.com/microsoft/DeepSpeed/tree/reyazda/testing_embedding). The error that I see between deepspeed-kernel (y) and pytorch (x) is about 0.001.

![image](https://user-images.githubusercontent.com/44502768/102557733-b618c400-4080-11eb-8eeb-e38a2f4271c7.png)

Please run this test on your side to verify this.

Thanks,
Reza

**Comment by sriramiscool** [comment]
Thank you! That makes sense. I am able to get the same result as you for the code you provided also when I added .half I am able to get an error of 0.0001 in my test code too 👍 
I still have issue with my earlier code I posted. I will try to debug more on that and see if we can get same difference there as well and let you know.

Thanks,
Sriram

**Comment by sriramiscool** [comment]
Hi @RezaYazdaniAminabadi,
Ran the previous code I shared with you with output_all_encoded_layers=True and I think the reason for high discrepancy there is because of accumulation of errors.
Below is the output of difference at every encoded layer.:

EMBEDDINGS DIFFERENT FOR MODEL WITH AND WITHOUT TRANSFORMER KERNEL
EMBEDDINGS GENERATED SAME: False
EMBEDDINGS ABSOLUTE MEAN ERROR encoder 0 : 0.0062408447265625
EMBEDDINGS GENERATED SAME: False
EMBEDDINGS ABSOLUTE MEAN ERROR encoder 1 : 0.0093231201171875
EMBEDDINGS GENERATED SAME: False
EMBEDDINGS ABSOLUTE MEAN ERROR encoder 2 : 0.01204681396484375
EMBEDDINGS GENERATED SAME: False
EMBEDDINGS ABSOLUTE MEAN ERROR encoder 3 : 0.015289306640625
EMBEDDINGS GENERATED SAME: False
EMBEDDINGS ABSOLUTE MEAN ERROR encoder 4 : 0.5078125
EMBEDDINGS GENERATED SAME: False
EMBEDDINGS ABSOLUTE MEAN ERROR encoder 5 : 0.96142578125
EMBEDDINGS GENERATED SAME: False
EMBEDDINGS ABSOLUTE MEAN ERROR encoder 6 : 1.298828125
EMBEDDINGS GENERATED SAME: False
EMBEDDINGS ABSOLUTE MEAN ERROR encoder 7 : 1.5703125
EMBEDDINGS GENERATED SAME: False
EMBEDDINGS ABSOLUTE MEAN ERROR encoder 8 : 1.8701171875
EMBEDDINGS GENERATED SAME: False
EMBEDDINGS ABSOLUTE MEAN ERROR encoder 9 : 2.052734375
EMBEDDINGS GENERATED SAME: False
EMBEDDINGS ABSOLUTE MEAN ERROR encoder 10 : 2.34765625
EMBEDDINGS GENERATED SAME: False
EMBEDDINGS ABSOLUTE MEAN ERROR encoder 11 : 2.658203125
EMBEDDINGS GENERATED SAME: False
EMBEDDINGS ABSOLUTE MEAN ERROR encoder 12 : 3.1171875
EMBEDDINGS GENERATED SAME: False
EMBEDDINGS ABSOLUTE MEAN ERROR encoder 13 : 3.599609375
EMBEDDINGS GENERATED SAME: False
EMBEDDINGS ABSOLUTE MEAN ERROR encoder 14 : 4.11328125
EMBEDDINGS GENERATED SAME: False
EMBEDDINGS ABSOLUTE MEAN ERROR encoder 15 : 4.41796875
EMBEDDINGS GENERATED SAME: False
EMBEDDINGS ABSOLUTE MEAN ERROR encoder 16 : 4.78125
EMBEDDINGS GENERATED SAME: False
EMBEDDINGS ABSOLUTE MEAN ERROR encoder 17 : 5.1640625
EMBEDDINGS GENERATED SAME: False
EMBEDDINGS ABSOLUTE MEAN ERROR encoder 18 : 5.39453125
EMBEDDINGS GENERATED SAME: False
EMBEDDINGS ABSOLUTE MEAN ERROR encoder 19 : 5.94140625
EMBEDDINGS GENERATED SAME: False
EMBEDDINGS ABSOLUTE MEAN ERROR encoder 20 : 6.23046875
EMBEDDINGS GENERATED SAME: False
EMBEDDINGS ABSOLUTE MEAN ERROR encoder 21 : 6.52734375
EMBEDDINGS GENERATED SAME: False
EMBEDDINGS ABSOLUTE MEAN ERROR encoder 22 : 6.8515625
EMBEDDINGS GENERATED SAME: False
EMBEDDINGS ABSOLUTE MEAN ERROR encoder 23 : 7.14453125
EMBEDDINGS GENERATED SAME: False
EMBEDDINGS ABSOLUTE MEAN ERROR encoder 24 : 7.33203125
EMBEDDINGS GENERATED SAME: False
EMBEDDINGS ABSOLUTE MEAN ERROR encoder 25 : 7.703125
EMBEDDINGS GENERATED SAME: False
EMBEDDINGS ABSOLUTE MEAN ERROR encoder 26 : 7.89453125
EMBEDDINGS GENERATED SAME: False
EMBEDDINGS ABSOLUTE MEAN ERROR encoder 27 : 8.2109375
EMBEDDINGS GENERATED SAME: False
EMBEDDINGS ABSOLUTE MEAN ERROR encoder 28 : 8.3515625
EMBEDDINGS GENERATED SAME: False
EMBEDDINGS ABSOLUTE MEAN ERROR encoder 29 : 8.4921875
EMBEDDINGS GENERATED SAME: False
EMBEDDINGS ABSOLUTE MEAN ERROR encoder 30 : 8.671875
EMBEDDINGS GENERATED SAME: False
EMBEDDINGS ABSOLUTE MEAN ERROR encoder 31 : 8.8984375
EMBEDDINGS GENERATED SAME: False
EMBEDDINGS ABSOLUTE MEAN ERROR encoder 32 : 9.078125
EMBEDDINGS GENERATED SAME: False
EMBEDDINGS ABSOLUTE MEAN ERROR encoder 33 : 9.15625
EMBEDDINGS GENERATED SAME: False
EMBEDDINGS ABSOLUTE MEAN ERROR encoder 34 : 9.265625
EMBEDDINGS GENERATED SAME: False
EMBEDDINGS ABSOLUTE MEAN ERROR encoder 35 : 9.328125
EMBEDDINGS GENERATED SAME: False
EMBEDDINGS ABSOLUTE MEAN ERROR encoder 36 : 9.3359375
EMBEDDINGS GENERATED SAME: False
EMBEDDINGS ABSOLUTE MEAN ERROR encoder 37 : 9.390625

**Comment by szhengac** [comment]
Hi @RezaYazdaniAminabadi, it seems there is still NAN issue if i use arbitrary hidden_size during the training. For example, in my previous run for a 1.5B model, I used the following model config:
```
    "bert_model_config": {
        "vocab_size_or_config_json_file": 32003,
        "hidden_size": 1536,
        "num_hidden_layers": 52,
        "num_attention_heads": 24,
        "intermediate_size": 6144,
        "hidden_act": "gelu",
        "hidden_dropout_prob": 0.1,
        "attention_probs_dropout_prob": 0.1,
        "max_position_embeddings": 512,
        "initializer_range": 0.02
    }
```
The training looks good. But after I incorporated #587 and changed it to 
```
    "bert_model_config": {
        "vocab_size_or_config_json_file": 32003,
        "hidden_size": 1600,
        "num_hidden_layers": 48,
        "num_attention_heads": 25,
        "intermediate_size": 6400,
        "hidden_act": "gelu",
        "hidden_dropout_prob": 0.1,
        "attention_probs_dropout_prob": 0.1,
        "max_position_embeddings": 512,
        "initializer_range": 0.02
    }
```
I received NAN issue again. These two configs both lead to a 1.5B model. I also tried an experiment with the former config and #587, the training looks ok.

**Comment by RezaYazdaniAminabadi** [comment]
Hi @szhengac 

Thanks for reporting this. That branch that you mentioned has already merged into the master branch. I have tried you configuration (hidden: 1600, heads: 25), using the __test_cuda_backward.py__, and the gradients and forward results seem to be healthy and match the baseline with PyTorch. Here is the difference I see for the difference between these two (which is in the order of 0.001):
![image](https://user-images.githubusercontent.com/44502768/102727023-f756e100-42d7-11eb-8f66-e607c47209f0.png)

Can you please check in the latest branch of deepspeed, and try this again?
Thanks,
Reza

**Comment by szhengac** [comment]
Hi @RezaYazdaniAminabadi. I am using the deepspeed master, and the latest commit I have is 7435b2f10af773b0204e77c3549b2b7df9a7a65b on Dec 17. I think my branch is already up to date? I also successfully ran a larger model with the following config

```
        "hidden_size": 2560,
        "num_hidden_layers": 127,
        "num_attention_heads": 40,
        "intermediate_size": 10240,
```

What I saw is that 1536 and 2560 are both applicable hidden size before arbitrary `hidden_size` commit.

**Comment by RezaYazdaniAminabadi** [comment]
Hi,

Sorry, I am a bit confused here. Are you saying that the new commit is making the training with hidden dimensions 1536/2560 produce NaN or undesired results?

Thanks,
Reza

**Comment by RezaYazdaniAminabadi** [comment]
I think they both should still work now. I am surprised if they produce different results! Also, can you please verify the issue with hidden dimension 1600 is resolved?
Thanks,
Reza

**Comment by szhengac** [comment]
@RezaYazdaniAminabadi, sorry for not making it clear. I already used the latest master branch that has https://github.com/microsoft/DeepSpeed/commit/7435b2f10af773b0204e77c3549b2b7df9a7a65b for the experiments. The training looks ok for both the 1536 and 2560 hidden sizes before and after https://github.com/microsoft/DeepSpeed/commit/7435b2f10af773b0204e77c3549b2b7df9a7a65b. But when I switched to 1600, I received NAN in the beginning.

**Comment by RezaYazdaniAminabadi** [comment]
I see. Is it possible to send me an script to reproduce this. Because I am not able to repro this with my test units. 
Thanks,
Reza

**Comment by szhengac** [comment]
I will see if I can make a minimal reproducible script. On the other hand, our training script is adapted from https://github.com/microsoft/DeepSpeedExamples/tree/78d69cb2f89a27b1e9b072df8c3e47d00c024fdc/bing_bert. Would it be possible for you to try bing_bert with 1600 hidden_size?

**Comment by RezaYazdaniAminabadi** [comment]
sure, will do. 
Thanks,
Reza

**Comment by szhengac** [comment]
Thanks. I will see if I can get NAN with other different configurations.

**Comment by szhengac** [comment]
Hi @RezaYazdaniAminabadi, I have tried the following different configurations:
```
1. hidden_size 1600, num_layers=4, num_attention_heads=25, intermediate_size=6400: NAN
2. hidden_size 1600, num_layers=4, num_attention_heads=20, intermediate_size=6400: NAN
3. hidden_size 1600, num_layers=4, num_attention_heads=2, intermediate_size=6400: NAN
4. hidden_size 1536, num_layers=4, num_attention_heads=2, intermediate_size=6400: No issue
5. hidden_size 800, num_layers=4, num_attention_heads=2, intermediate_size=3200: No issue
6. hidden_size 800, num_layers=4, num_attention_heads=2, intermediate_size=6400: No issue
7. hidden_size 1600, num_layers=1, num_attention_heads=2, intermediate_size=6400: NAN
8. hidden_size 1600, num_layers=1, num_attention_heads=1, intermediate_size=6400: NAN
9. hidden_size 160, num_layers=1, num_attention_heads=1, intermediate_size=640: NAN
10. hidden_size 16, num_layers=1, num_attention_heads=1, intermediate_size=64: RuntimeError: CUDA error: invalid configuration argument
```
Both `hidden_size=1536` and `hidden_size=800` work fine, while `hidden_size=1600` and `hidden_size=160` result in NAN. `hidden_size=16` leads to another issue.

**Comment by RezaYazdaniAminabadi** [comment]
Hi @szhengac, 

I have tried running the bing-bert example with hidden size 1600 and batch-size 64. I have not seen the NaN issue thought. By the way, there are some overflows at the beginning that will reduce the loss scale to 4K. 
![image](https://user-images.githubusercontent.com/44502768/102833541-3b181c00-43a6-11eb-9918-45b7da96341f.png)
Here is the loss curve I got without changing the training hyper-parameters:
![image](https://user-images.githubusercontent.com/44502768/102833646-86322f00-43a6-11eb-8c4d-abd4002386e7.png)
I will also run with PyTorch kernels to verify the loss curve.
Could you please try running the same test and see if you get the same results?

Thanks,
Reza

**Comment by szhengac** [comment]
@RezaYazdaniAminabadi, you mean your result was obtained without using the transformer cuda kernel? In my experiment, I use dynamic batch, where the sequence length is not fixed and it depends on the longest sequence in the batch. And, I pad the sequence such that final length is a multiple of 8.

**Comment by RezaYazdaniAminabadi** [comment]
I have run with the deepspeed transformer cuda kernel:
![image](https://user-images.githubusercontent.com/44502768/102833996-90a0f880-43a7-11eb-901f-c327ecee74e6.png)
Please remove the padding and let the transformer API takes care of that. I am also not passing the sequence-length, so it can change dynamically. For the batch size, please specify the maximum batch size that your application can have. If you are running on V100 (32 GB), 64 is the maximum batch size you can have if the sequence-length is lower than 128.
Here is the sample of how I pass in the parameters for the kernel in my recent run with hidden size 1600: https://github.com/microsoft/DeepSpeedExamples/blob/master/bing_bert/nvidia/modelingpreln.py#L575-L592
Thanks,
Reza

**Comment by szhengac** [comment]
I am using 128 A100 GPUs with micro-batch-size=64 and maximum sequence length 128. After I changed it to static batch size with fixed sequence length 128, I can still see the NAN for hidden_size=1600. I am using exactly the same code as in https://github.com/microsoft/DeepSpeedExamples/blob/master/bing_bert/nvidia/modelingpreln.py#L575-L592.

**Comment by RezaYazdaniAminabadi** [comment]
This is pretty strange. Can you please send me your script so that I can try it on my end!?
Thanks,
Reza

**Comment by RezaYazdaniAminabadi** [comment]
There is also another possibility that this issue only appears on A100! Unfortunately, I have limited access to this machine right now! So, it would be helpful if you can see whether the issue exists on V100 too. If that's the case, I need to debug this by the script that you provide me.
Thanks,
Reza

**Comment by szhengac** [comment]
@RezaYazdaniAminabadi, thanks for your suggestions. I need to think about how to make some tweaks, as it is in the internal repo.

**Comment by RezaYazdaniAminabadi** [comment]
Sure, I understand it. 
If you think this is helpful, we can have an offline chat and find the source the problem. The issue is that I cannot reproduce the same NaN problem on my side, otherwise I would be happy to help solve it.

By the way, I have run the same experiments you've mentioned earlier, and I have seen the same problem with hidden_size 16. However, I can run the rest of the configurations with no problem.

Thanks,
Reza

**Comment by szhengac** [comment]
@RezaYazdaniAminabadi, sounds good to me. We can have an offline chat.

And, I just tried the experiment on P3, I still receive NAN issue. And, I found the loss of the first iteration is normal and its grad is NAN:

12/22/2020 06:52:41 - INFO - utils.logger -   bert_progress: step=1, loss=10.6953125, lr=0.0, sample_count=4096
12/22/2020 06:52:42 - INFO - utils.logger -   bert_progress: step=2, loss=nan, lr=0.0, sample_count=8192

I use Adam optimizer with zero lr. It seems it is also related to the input.

**Comment by szhengac** [comment]
When I changed the input_ids, attention_mask, and mlm_labels to all zeros, I can receive:

12/22/2020 07:29:14 - INFO - utils.logger -   bert_progress: step=1, loss=11.265625, lr=0.0, sample_count=32
12/22/2020 07:29:15 - INFO - utils.logger -   bert_progress: step=2, loss=nan, lr=0.0, sample_count=64
12/22/2020 07:29:15 - INFO - utils.logger -   bert_progress: step=3, loss=nan, lr=0.0, sample_count=96

Here, I only use one GPU with global_batch_size=micro_batch_size=32.

**Comment by RezaYazdaniAminabadi** [comment]
Thanks @szhengac for the detailed information.
I will try more tests and let you know whether I can repro this on my side.

**Comment by szhengac** [comment]
@RezaYazdaniAminabadi I also tried modifying your unittest cases in `test_cuda_backward.py`. I got the following:

```
(3,160,128,2,24,False,True, 0.2)

E           AssertionError: 
E           Not equal to tolerance rtol=1e-07, atol=6.1788
E           Index: 3
E           Mismatched elements: 128 / 160 (80%)
E           Max absolute difference: 79.4
E           Max relative difference: 130.1
E            x: array([   1.992 ,  -37.6   ,   70.5   ,   95.1   ,   19.5   ,  -42.5   ,
E                    32.94  ,   39.84  ,  -30.89  ,  -29.73  ,   74.7   ,   -0.8247,
E                   -50.22  ,  -16.9   ,  103.75  ,   31.67  ,    4.566 ,  -17.62  ,...
E            y: array([  17.7   ,   41.78  ,   65.6   ,   44.22  ,    9.01  ,  -74.75  ,
E                    24.8   ,   12.945 ,  -52.03  ,    0.2544,   54.78  ,    6.74  ,
E                   -42.47  ,  -34.44  ,   32.9   ,    1.252 ,  -24.47  ,   -7.484 ,...
```

and 

```
(64,160,128,2,24,False,True, 0.2)

E           AssertionError: 
E           Not equal to tolerance rtol=1e-07, atol=28.9088
E           Index: 3
E           Mismatched elements: 153 / 160 (95.6%)
E           Max absolute difference: 1270.
E           Max relative difference: 51.97
E            x: array([ -63.8   , -165.5   ,   32.84  ,   63.47  ,   40.03  ,  146.    ,
E                   -86.    ,  188.2   , -123.44  ,   38.12  , -215.8   ,  -87.25  ,
E                  -102.7   ,  202.    ,   96.44  ,   76.56  ,  322.2   ,  111.56  ,...
E            y: array([ -298.8  ,   571.5  ,  -385.5  ,  -166.9  ,   -50.47 ,  -451.   ,
E                   -586.5  ,  -308.8  ,  -617.   ,   591.5  ,  -205.4  ,  -349.2  ,
E                   -181.4  ,  -343.   ,  -696.5  ,   -75.2  ,  -141.4  ,   -42.47 ,...
```

and

```
(64,1600,128,2,24,False,True, 0.2)

!!!! kernel execution error. (m: 1600, n: 1600, k: 8192, error: 13) 
!!!! kernel execution error. (m: 1600, n: 8192, k: 1600, error: 13) 
!!!! kernel execution error. (m: 1600, n: 1600, k: 8192, error: 13) 
!!!! kernel execution error. (m: 1600, n: 8192, k: 1600, error: 13) 
!!!! kernel execution error. (m: 1600, n: 1600, k: 8192, error: 13) 
!!!! kernel execution error. (m: 1600, n: 8192, k: 1600, error: 13) 
!!!! kernel execution error. (m: 800, n: 128, k: 128, error: 13) 
!!!! kernel execution error. (m: 128, n: 128, k: 800, error: 13) 
!!!! kernel execution error. (m: 800, n: 128, k: 128, error: 13) 
!!!! kernel execution error. (m: 800, n: 128, k: 128, error: 13) 
!!!! kernel execution error. (m: 1600, n: 4800, k: 8192, error: 13) 
!!!! kernel execution error. (m: 1600, n: 8192, k: 4800, error: 13) 
========================================================================================= short test summary info ==========================================================================================
FAILED test_cuda_backward.py::test_backward[64-1600-128-2-24-False-True-0.2] - RuntimeError: CUDA error: an illegal memory access was encountered
```

**Comment by RezaYazdaniAminabadi** [comment]
Hi @szhengac 

Thanks for trying these configurations. 
Yes, you are right. I see the difference too. However, for the last one, it does not crash in my case, but it produces nan!
I will check where the issue is and get back to you soon. 

Thanks,
Reza

**Comment by RezaYazdaniAminabadi** [comment]
@szhengac, can you tell me for which parameter's gradient you see the difference when running the first test? It can be printed during the checking if you use -sv flags for the pytest.
Thanks,
Reza

**Comment by RezaYazdaniAminabadi** [comment]
Never mind, I found it! It is for the output_gemm bias.

**Comment by RezaYazdaniAminabadi** [comment]
Hi @szhengac

I have found the source of the problem, which is still related to the layer-norm kernels! I have pushed my changes to this [PR](https://github.com/microsoft/DeepSpeed/tree/reyazda/test-hidden-dimension). I am seeing that the backward_test passes with the first two tests that you've mentioned earlier.
It also has similar results in the last case with 1600 hidden-dimension (with 4 values having 0.04 difference):

![image](https://user-images.githubusercontent.com/44502768/102945764-93691f80-4473-11eb-8b32-6d802b4237d3.png)

One important thing about this __backward_test__ script is that you need to reduce the batch size to fit 2 similar models, one using PyTorch kernel and one deepspeed-transformer, so that we can compare the results. Otherwise, it will crash the same way you reported. Thus, I had to reduce the batch size to 16, so that it can run for both. 
One side not is that Pytorch runs OOM for batch 64 on my machine whereas deepspeed_kernels can run fine.

I have added a few test-cases [here](https://github.com/microsoft/DeepSpeed/compare/reyazda/test-hidden-dimension#diff-5254a6e8ace44e76fa5d734ec6939e7e885fe0099295fa587e3d7ad5cac21381R266-R275). Please run them on your side and let me know if they pass. If you see some tests crashes, please run them alone!

Hope this also fixes the problem of seeing the nans, too! :-)

Thanks,
Reza

**Comment by szhengac** [comment]
@RezaYazdaniAminabadi Thanks for the quick fix. I will give it a try. As I am using V100 for the testing, I think I shouldn't have memory issue as I only use a few number of layers?

**Comment by szhengac** [comment]
@RezaYazdaniAminabadi I still receive `RuntimeError: CUDA error: an illegal memory access was encountered` for the following two tests:

test_backward[32-800-128-2-4-True-True-0.2] and test_backward[64-1600-128-25-4-True-True-0.2]

I monitor the GPU memory during the testing, it is far away from hitting on the limit.

**Comment by RezaYazdaniAminabadi** [comment]
How about if you run those last two separately!? I have seen also the same problem, but when I ran them alone they pass fine! I am not exactly sure what the problem is. Will investigate this further.
Thanks,
Reza

**Comment by szhengac** [comment]
I just removed some tests that can pass, and I do not see that CUDA error anymore. It seems to me that the kernel may have some storage issue. But I get error for test_backward[64-1600-128-25-4-False-True-0.2]

```
E           AssertionError: 
E           Not equal to tolerance rtol=1e-07, atol=1
E           Index: 1
E           Mismatched elements: 246 / 1600 (15.4%)
E           Max absolute difference: 32.
E           Max relative difference: 0.000966
E            x: array([40300., 19180., 15816., ..., 19340., 12216., 15420.], dtype=float16)
E            y: array([40300., 19180., 15816., ..., 19340., 12220., 15420.], dtype=float16)
```

**Comment by RezaYazdaniAminabadi** [comment]
I think this might be because we are registering the backward hooks to get the gradients from PyTorch and compare them, which causes memory bloat. However if we only run the kernels, this problem won't exist. I have verified this with the DeepSpeed-Examples and running the training tests.
Regarding the last test, I would not worry too much, as the relative difference is too low. However, if you think this is problematic, I can fix that too.

**Comment by szhengac** [comment]
I wonder why getting gradients from pytorch hook and compare it to the kernel's could cause memory bloat?

"Regarding the last test, I would not worry too much, as the relative difference is too low. However, if you think this is problematic, I can fix that too." If that error could be further reduced, that would be great. As we need to convert the transformer cuda kernel model to model based on pytorch kernel for inference, smaller difference reduces the risk.

**Comment by RezaYazdaniAminabadi** [comment]
I was previously having this problem that the hooks registered won't be released immediately. However, I did check this again, but that was not the issue. So, I take my previous comment back! :-)
However, I think I have found the source of the issue for testing all the configurations together, which I suspect is due to the many allocations/deallocations happening because of changing the dimensions. [This](https://github.com/microsoft/DeepSpeed/blob/reyazda/test-hidden-dimension/csrc/includes/context.h#L69-L74) is the part that takes care of this, and since the context class is static, there is only one instance of it for all our tests and that's why the allocation and deallocations need to happen. In order to show if this really is the problem and solve the issue, I did reorder my tests as follows, so that less deallocations happen:
(64,1600,128,25,4,True,True, 0.2),
                             (32,1600,128,25,4,False,True, 0.2),
                             (32,1600,128,20,4,False,True, 0.2),
                             (32,800,128,2,4,False,True, 0.2),
                             (32,800,128,2,4,True,True, 0.2),
                             (3,160,128,2,24,False,True, 0.2),
                             (64,160,128,2,24,False,True, 0.2),
                             (3,160,128,2,24,True,True, 0.2),
                             (64,160,128,2,24,True,True, 0.2),
and, all the tests can pass together now!

**Comment by szhengac** [comment]
But that part of the code only reallocates the memory when the current memory block is not large enough for holding the new input. And, in real case, we may need to use dynamic mini-batch, so it is very likely that the input batches have varying shape.

**Comment by RezaYazdaniAminabadi** [comment]
True, and that's why we use the max_batch_size to initialize the workspace with! However, I am thinking of moving this part to PyTorch, so that all memory management is handled through it.

**Comment by szhengac** [comment]
That’s a good idea. But it is still strange as we generally get cuda
illegal access error when we are making an out-of-bound memory access (size
is wrong or too many launched blocks so that thread is out-of-bound?).

**Comment by RezaYazdaniAminabadi** [comment]
Hi @szhengac 

 Sorry, I am not sure if I understand your question here! These are some reasons of seeing this error but not all of them. If you are still referring to the error happened during the test, I have checked that the workspace memory could not be allocated, and normally this error is silent and your program still continues on, and when reaching to some kernels that need to access this memory, it throws an illegal memory access, since there is no memory allocated!

Reza

**Comment by szhengac** [comment]
Thanks for the explanation. It is very helpful. Do you have idea why the workspace memory is not allocated?

**Comment by RezaYazdaniAminabadi** [comment]
no problem! I have an idea why this happens, but I am not entirely sure. I am ganna run more tests and let you know once I am certain.
Thanks,
Reza

**Comment by szhengac** [comment]
Hi @RezaYazdaniAminabadi, happy new year! I would like to know if we have any update on this issue? Thanks.

**Comment by RezaYazdaniAminabadi** [comment]
Hi @szhengac 

Happy new year! 
Sorry for the delay. I had involved in something else, but I will get back to this soon. 
By the way, for some of these issues we can better discuss it if we can meet offline. Would it be okay if I schedule a team meeting for next week?
Thanks,
Reza

**Comment by szhengac** [comment]
@RezaYazdaniAminabadi Sounds good to me.

**Comment by szhengac** [comment]
@RezaYazdaniAminabadi Sorry to bother you again. I wonder if there is any update on this issue or about the offline discussion? Thanks.

**Comment by RezaYazdaniAminabadi** [comment]
Hi @szhengac 

No, no bother at all, sorry for the delay in getting back on this thread! I have found some sources of where the issue you were referring to may stem from. I will push some changes to the kernels and let you know to test it. 
Apologies for not sending the meeting request, I got involved into some other projects. Let me first add these changes and then if it did not resolve your issue, we can discuss this further offline. How does that sound?
Thanks,
Reza

**Comment by szhengac** [comment]
@RezaYazdaniAminabadi Thanks! Sounds good to me.

**Comment by szhengac** [comment]
@RezaYazdaniAminabadi It seems that `test_cuda_backward.py` in the more recent master branch is broken. Without changing anything, I received: `RuntimeError: a view of a leaf Variable that requires grad is being used in an in-place operation.`

**Comment by RezaYazdaniAminabadi** [comment]
Hi @szhengac 

Thanks for reporting this. Is this some issue you see with PyTorch 1.7 and cuda 11!?
I am also fixing some bugs that I see the transformer kernel may have by some hidden dimensions. I have already made some changes to fix one issue with the bias-add. I am also keep searching other kernels for some other corner cases and will update you soon.
Thanks for your patience!
Reza

**Comment by szhengac** [comment]
@RezaYazdaniAminabadi I used CUDA 11.0 and compiled pytorch with commit ae5c2febb912066f1a8dec8b54451c09195b2c6d from source

**Comment by szhengac** [comment]
@RezaYazdaniAminabadi Hi Reza, do you have any progress regarding this issue? Thanks.

**Comment by RezaYazdaniAminabadi** [comment]
Hi @szhengac 

Yes, I think I got it solved with some of the dimensions we discussed. I have pushed my changes here in [this branch](https://github.com/microsoft/DeepSpeed/tree/transformer-kernel/all-hidden-dimensions). Could you please give it a try?

Thanks,
Reza

**Comment by szhengac** [comment]
@RezaYazdaniAminabadi Sure. I will give it a try.

**Comment by szhengac** [comment]
@RezaYazdaniAminabadi I get the following error when I tried unittest test_cuda_backward.py:

```
    def __init__(self, config, initial_weights=None, initial_biases=None):
        super(DeepSpeedTransformerLayer, self).__init__()
    
        self.config = config
        self.config.layer_id = DeepSpeedTransformerLayer.layer_id
        DeepSpeedTransformerLayer.layer_id = DeepSpeedTransformerLayer.layer_id + 1
    
        print("DeepSpeed Transformer config is ", self.config.__dict__)
    
        if self.config.local_rank >= 0:
            torch.cuda.set_device(self.config.local_rank)
    
        if initial_weights is None and initial_biases is None:
            self.attn_qkvw = nn.Parameter(
                torch.Tensor(self.config.hidden_size * 3,
                             self.config.hidden_size))
            self.attn_qkvb = nn.Parameter(torch.Tensor(self.config.hidden_size * 3))
            self.attn_ow = nn.Parameter(
                torch.Tensor(self.config.hidden_size,
                             self.config.hidden_size))
            self.attn_ob = nn.Parameter(torch.Tensor(self.config.hidden_size))
            self.attn_nw = nn.Parameter(torch.Tensor(self.config.hidden_size))
            self.attn_nb = nn.Parameter(torch.Tensor(self.config.hidden_size))
            self.inter_w = nn.Parameter(
                torch.Tensor(self.config.intermediate_size,
                             self.config.hidden_size))
            self.inter_b = nn.Parameter(torch.Tensor(self.config.intermediate_size))
            self.output_w = nn.Parameter(
                torch.Tensor(self.config.hidden_size,
                             self.config.intermediate_size))
            self.output_b = nn.Parameter(torch.Tensor(self.config.hidden_size))
            self.norm_w = nn.Parameter(torch.Tensor(self.config.hidden_size))
            self.norm_b = nn.Parameter(torch.Tensor(self.config.hidden_size))
            self.init_transformer_weights(self.config.adjust_init_range)
        else:
            # For testing only.
            self.attn_qkvw = nn.Parameter(
                torch.Tensor(self.config.hidden_size * 3,
                             self.config.hidden_size))
            for i in range(3):
                self.attn_qkvw[i * self.config.hidden_size:(i + 1) * self.config.hidden_size] = \
>                   torch.empty_like(initial_weights[i]).copy_(initial_weights[i])
E               RuntimeError: a view of a leaf Variable that requires grad is being used in an in-place operation.

/usr/local/lib64/python3.7/site-packages/deepspeed/ops/transformer/transformer.py:526: RuntimeError
```

**Comment by RezaYazdaniAminabadi** [comment]
Interesting! So, the new version of PyTorch does not allow us to copy the weights like this anymore! This part is needed for the test script since we need to make sure both baseline and deepspeed gets the same weights.
Let me try to see if I can replace this with some other functions.
Thanks,
Reza

**Comment by RezaYazdaniAminabadi** [comment]
Meanwhile, can you try this on an older version of PyTorch?
Thanks

**Comment by szhengac** [comment]
@RezaYazdaniAminabadi With Pytorch 1.7.0, I got:

```
E           
E             #endif /* defined(__CUDACC__) */
E           #endif /* defined(__cplusplus) */
E           #undef __HALF_TO_US
E           #undef __HALF_TO_CUS
E           
E           typedef __half half;
E           
E           extern "C" __global__
E           void func_5(half* t0, half* t1, half* aten_mul_flat, half* aten_add_flat, half* aten_div_flat, half* aten_mul_flat_1) {
E           {
E             float v = __half2float(t0[(512 * blockIdx.x + threadIdx.x) % 1600]);
E             float v_1 = __half2float(t1[512 * blockIdx.x + threadIdx.x]);
E             aten_div_flat[512 * blockIdx.x + threadIdx.x] = __float2half((v + v_1) / 1.414209961891174f);
E             float aten_mul_flat_ = __half2float(aten_mul_flat_1[512 * blockIdx.x + threadIdx.x]);
E             aten_mul_flat__1 = __float2half((__half2float(t0[(512 * blockIdx.x + threadIdx.x) % 1600]) + __half2float(t1[512 * blockIdx.x + threadIdx.x])) * 0.5f);
E             aten_mul_flat_1[512 * blockIdx.x + threadIdx.x] = aten_mul_flat_;
E             float v_2 = __half2float(t0[(512 * blockIdx.x + threadIdx.x) % 1600]);
E             float v_3 = __half2float(t1[512 * blockIdx.x + threadIdx.x]);
E             aten_add_flat[512 * blockIdx.x + threadIdx.x] = __float2half((erff((v_2 + v_3) / 1.414209961891174f)) + 1.f);
E             float v_4 = __half2float(t0[(512 * blockIdx.x + threadIdx.x) % 1600]);
E             float v_5 = __half2float(t1[512 * blockIdx.x + threadIdx.x]);
E             float v_6 = __half2float(t0[(512 * blockIdx.x + threadIdx.x) % 1600]);
E             float v_7 = __half2float(t1[512 * blockIdx.x + threadIdx.x]);
E             aten_mul_flat[512 * blockIdx.x + threadIdx.x] = __float2half(((v_4 + v_5) * 0.5f) * ((erff((v_6 + v_7) / 1.414209961891174f)) + 1.f));
E           }
E           }

modelingpreln.py:235: RuntimeError

========================================================================================= short test summary info =========================================================================================
FAILED test_cuda_backward.py::test_backward[8-1600-128-25-3-True-True-0.05] - RuntimeError: default_program(57): error: identifier "aten_mul_flat__1" is undefined
FAILED test_cuda_backward.py::test_backward[8-160-128-2-3-True-True-0.1] - RuntimeError: default_program(57): error: identifier "aten_mul_flat__1" is undefined
FAILED test_cuda_backward.py::test_backward[8-1600-128-2-3-True-True-0.05] - RuntimeError: default_program(57): error: identifier "aten_mul_flat__1" is undefined
FAILED test_cuda_backward.py::test_backward[3-1024-119-16-24-True-False-0.05] - RuntimeError: default_program(57): error: identifier "aten_mul_flat__1" is undefined
FAILED test_cuda_backward.py::test_backward[3-1024-115-16-24-True-True-0.05] - RuntimeError: default_program(57): error: identifier "aten_mul_flat__1" is undefined
```

**Comment by RezaYazdaniAminabadi** [comment]
Hi @szhengac 

Sorry, I got a bit busy with other matters, but I think this is still coming from PyTorch. I am not sure what bug it has with these newer version, but I have tried the unit tests with torch1.6 and all passed. I understand you will need to run this on newer GPU architecture, so you will need newer version of torch (such as 1.8) and I hope I can solve those issues soon. I wonder if you could see if this works on Torch 1.6 on your side.
Thanks,
Reza

**Comment by szhengac** [comment]
@RezaYazdaniAminabadi Sorry for getting back to you late. Our platform currently does not have <=cu10.1, but I may not have time to recompile everything for cu10.1. I see that this issue is closed. It has been fixed with >=pytorch1.7.0?

**Comment by RezaYazdaniAminabadi** [comment]
Hi @szhengac,

There is still problem with higher versions of PyTorch. We can find a way to support this on Torch1.8. Please feel free to open a different issue with this regard, since this issue is getting quite old and I think this is not anymore an issue with DeepSpeed Transformer kernels.

Thanks,
Reza

**Comment by dancingpipi** [comment]
@RezaYazdaniAminabadi Can you help with this issue: https://github.com/microsoft/DeepSpeed/issues/1967
