### ISSUE TITLE
NCCL unhandled system error at initialization

### ISSUE THREAD

**Issue by TevenLeScao** [microsoft/DeepSpeed#716]
Hello,

I am trying to use deepspeed on a GCP machine after the same set-up (CUDA 10.2, deepspeed from pip, torch 1.7.1) worked just fine on my local station. However, my script (the HF Trainer with deepspeed integration) hits a NCCL snag in `deepspeed.init_distributed` and crashes. Here's the traceback with `NCCL_DEBUG=INFO`:

```
[2021-01-31 22:58:36,369] [WARNING] [runner.py:117:fetch_hostfile] Unable to find hostfile, will proceed with training with local resources only.
[2021-01-31 22:59:01,144] [INFO] [runner.py:358:main] cmd = /home/teven/virtualenvs/hf_dev/bin/python3 -u -m deepspeed.launcher.launch --world_info=eyJsb2NhbGhvc3QiOiBbMF19 --master_addr=127.0.0.1 --master_port=29500 run_clm_scaling.py --model_type gpt2 --tokenizer_name gpt2 --dataset_name wikitext --dataset_config_name wikitext-2-raw-v1 --do_train --do_eval --output_dir /tmp/test-clm --deepspeed ds_config.json --n_layer 2 --n_embd 256 --n_head 8 --warmup_steps 100
[2021-01-31 22:59:01,747] [INFO] [launch.py:71:main] 0 NCCL_DEBUG INFO
[2021-01-31 22:59:01,747] [INFO] [launch.py:78:main] WORLD INFO DICT: {'localhost': [0]}
[2021-01-31 22:59:01,747] [INFO] [launch.py:87:main] nnodes=1, num_local_procs=1, node_rank=0
[2021-01-31 22:59:01,747] [INFO] [launch.py:99:main] global_rank_mapping=defaultdict(<class 'list'>, {'localhost': [0]})
[2021-01-31 22:59:01,747] [INFO] [launch.py:100:main] dist_world_size=1
[2021-01-31 22:59:01,747] [INFO] [launch.py:103:main] Setting CUDA_VISIBLE_DEVICES=0
[2021-01-31 22:59:02,985] [INFO] [distributed.py:47:init_distributed] Initializing torch distributed with backend: nccl
teven-big:3374:3374 [0] NCCL INFO Bootstrap : Using [0]ens12:10.164.0.48<0>
teven-big:3374:3374 [0] NCCL INFO NET/Plugin : No plugin found (libnccl-net.so), using internal implementation

teven-big:3374:3374 [0] misc/ibvwrap.cc:63 NCCL WARN Failed to open libibverbs.so[.1]
teven-big:3374:3374 [0] NCCL INFO NET/Socket : Using [0]ens12:10.164.0.48<0>
teven-big:3374:3374 [0] NCCL INFO Using network Socket
NCCL version 2.7.8+cuda10.2

teven-big:3374:3415 [0] misc/nvmlwrap.cc:115 NCCL WARN nvmlInit() failed: Driver/library version mismatch
teven-big:3374:3415 [0] NCCL INFO graph/xml.cc:662 -> 2
teven-big:3374:3415 [0] NCCL INFO graph/topo.cc:523 -> 2
teven-big:3374:3415 [0] NCCL INFO init.cc:581 -> 2
teven-big:3374:3415 [0] NCCL INFO init.cc:840 -> 2
teven-big:3374:3415 [0] NCCL INFO group.cc:73 -> 2 [Async thread]
Traceback (most recent call last):
  File "run_clm_scaling.py", line 400, in <module>
    main()
  File "run_clm_scaling.py", line 166, in main
    model_args, data_args, training_args, config_args = parser.parse_args_into_dataclasses()
  File "/home/teven/transformers/src/transformers/hf_argparser.py", line 180, in parse_args_into_dataclasses
    obj = dtype(**inputs)
  File "<string>", line 59, in __init__
  File "/home/teven/transformers/src/transformers/training_args.py", line 476, in __post_init__
    if is_torch_available() and self.device.type != "cuda" and self.fp16:
  File "/home/teven/transformers/src/transformers/file_utils.py", line 1330, in wrapper
    return func(*args, **kwargs)
  File "/home/teven/transformers/src/transformers/training_args.py", line 581, in device
    return self._setup_devices
  File "/home/teven/transformers/src/transformers/file_utils.py", line 1320, in __get__
    cached = self.fget(obj)
  File "/home/teven/transformers/src/transformers/file_utils.py", line 1330, in wrapper
    return func(*args, **kwargs)
  File "/home/teven/transformers/src/transformers/training_args.py", line 549, in _setup_devices
    deepspeed.init_distributed()
  File "/home/teven/DeepSpeed/deepspeed/utils/distributed.py", line 51, in init_distributed
    init_method=init_method)
  File "/home/teven/virtualenvs/hf_dev/lib/python3.6/site-packages/torch/distributed/distributed_c10d.py", line 455, in init_process_group
    barrier()
  File "/home/teven/virtualenvs/hf_dev/lib/python3.6/site-packages/torch/distributed/distributed_c10d.py", line 1960, in barrier
    work = _default_pg.barrier()
RuntimeError: NCCL error in: /pytorch/torch/lib/c10d/ProcessGroupNCCL.cpp:784, unhandled system error, NCCL version 2.7.8
```

Of special interest to me are the lines:

`teven-big:3374:3374 [0] misc/ibvwrap.cc:63 NCCL WARN Failed to open libibverbs.so[.1]`

and

`teven-big:3374:3415 [0] misc/nvmlwrap.cc:115 NCCL WARN nvmlInit() failed: Driver/library version mismatch`

but since they're only warnings (and there's several!) I am not sure whether they point in the right direction.

**Comment by TevenLeScao** [comment]
For reference, here's what running with `NCCL_DEBUG=INFO` gives on my local machine, with a functional script:

```
[2021-01-31 23:07:46,345] [WARNING] [runner.py:117:fetch_hostfile] Unable to find hostfile, will proceed with training with local resources only.
[2021-01-31 23:07:46,368] [INFO] [runner.py:355:main] cmd = /home/teven/virtualenvs/dev_transformers/bin/python3 -u -m deepspeed.launcher.launch --world_info=eyJsb2NhbGhvc3QiOiBbMF19 --master_addr=127.0.0.1 --master_port=29500 run_clm_scaling.py --model_type gpt2 --tokenizer_name gpt2 --dataset_name wikitext --dataset_config_name wikitext-2-raw-v1 --do_train --do_eval --output_dir /tmp/test-clm --deepspeed ds_config.json --n_layer 2 --n_embd 256 --n_head 8 --warmup_steps 100
[2021-01-31 23:07:46,791] [INFO] [launch.py:71:main] 0 NCCL_DEBUG INFO
[2021-01-31 23:07:46,791] [INFO] [launch.py:78:main] WORLD INFO DICT: {'localhost': [0]}
[2021-01-31 23:07:46,791] [INFO] [launch.py:87:main] nnodes=1, num_local_procs=1, node_rank=0
[2021-01-31 23:07:46,791] [INFO] [launch.py:99:main] global_rank_mapping=defaultdict(<class 'list'>, {'localhost': [0]})
[2021-01-31 23:07:46,791] [INFO] [launch.py:100:main] dist_world_size=1
[2021-01-31 23:07:46,791] [INFO] [launch.py:103:main] Setting CUDA_VISIBLE_DEVICES=0
[2021-01-31 23:07:47,683] [INFO] [distributed.py:40:init_distributed] Initializing torch distributed with backend: nccl
drawbar:20780:20780 [0] NCCL INFO Bootstrap : Using [0]wlo1:192.168.43.126<0>
drawbar:20780:20780 [0] NCCL INFO NET/Plugin : No plugin found (libnccl-net.so), using internal implementation
drawbar:20780:20780 [0] NCCL INFO NET/IB : No device found.
drawbar:20780:20780 [0] NCCL INFO NET/Socket : Using [0]wlo1:192.168.43.126<0>
drawbar:20780:20780 [0] NCCL INFO Using network Socket
NCCL version 2.7.8+cuda10.2
drawbar:20780:20805 [0] NCCL INFO Channel 00/32 :    0
drawbar:20780:20805 [0] NCCL INFO Channel 01/32 :    0
drawbar:20780:20805 [0] NCCL INFO Channel 02/32 :    0
drawbar:20780:20805 [0] NCCL INFO Channel 03/32 :    0
drawbar:20780:20805 [0] NCCL INFO Channel 04/32 :    0
drawbar:20780:20805 [0] NCCL INFO Channel 05/32 :    0
drawbar:20780:20805 [0] NCCL INFO Channel 06/32 :    0
drawbar:20780:20805 [0] NCCL INFO Channel 07/32 :    0
drawbar:20780:20805 [0] NCCL INFO Channel 08/32 :    0
drawbar:20780:20805 [0] NCCL INFO Channel 09/32 :    0
drawbar:20780:20805 [0] NCCL INFO Channel 10/32 :    0
drawbar:20780:20805 [0] NCCL INFO Channel 11/32 :    0
drawbar:20780:20805 [0] NCCL INFO Channel 12/32 :    0
drawbar:20780:20805 [0] NCCL INFO Channel 13/32 :    0
drawbar:20780:20805 [0] NCCL INFO Channel 14/32 :    0
drawbar:20780:20805 [0] NCCL INFO Channel 15/32 :    0
drawbar:20780:20805 [0] NCCL INFO Channel 16/32 :    0
drawbar:20780:20805 [0] NCCL INFO Channel 17/32 :    0
drawbar:20780:20805 [0] NCCL INFO Channel 18/32 :    0
drawbar:20780:20805 [0] NCCL INFO Channel 19/32 :    0
drawbar:20780:20805 [0] NCCL INFO Channel 20/32 :    0
drawbar:20780:20805 [0] NCCL INFO Channel 21/32 :    0
drawbar:20780:20805 [0] NCCL INFO Channel 22/32 :    0
drawbar:20780:20805 [0] NCCL INFO Channel 23/32 :    0
drawbar:20780:20805 [0] NCCL INFO Channel 24/32 :    0
drawbar:20780:20805 [0] NCCL INFO Channel 25/32 :    0
drawbar:20780:20805 [0] NCCL INFO Channel 26/32 :    0
drawbar:20780:20805 [0] NCCL INFO Channel 27/32 :    0
drawbar:20780:20805 [0] NCCL INFO Channel 28/32 :    0
drawbar:20780:20805 [0] NCCL INFO Channel 29/32 :    0
drawbar:20780:20805 [0] NCCL INFO Channel 30/32 :    0
drawbar:20780:20805 [0] NCCL INFO Channel 31/32 :    0
drawbar:20780:20805 [0] NCCL INFO Trees [0] -1/-1/-1->0->-1|-1->0->-1/-1/-1 [1] -1/-1/-1->0->-1|-1->0->-1/-1/-1 [2] -1/-1/-1->0->-1|-1->0->-1/-1/-1 [3] -1/-1/-1->0->-1|-1->0->-1/-1/-1 [4] -1/-1/-1->0->-1|-1->0->-1/-1/-1 [5] -1/-1/-1->0->-1|-1->0->-1/-1/-1 [6] -1/-1/-1->0->-1|-1->0->-1/-1/-1 [7] -1/-1/-1->0->-1|-1->0->-1/-1/-1 [8] -1/-1/-1->0->-1|-1->0->-1/-1/-1 [9] -1/-1/-1->0->-1|-1->0->-1/-1/-1 [10] -1/-1/-1->0->-1|-1->0->-1/-1/-1 [11] -1/-1/-1->0->-1|-1->0->-1/-1/-1 [12] -1/-1/-1->0->-1|-1->0->-1/-1/-1 [13] -1/-1/-1->0->-1|-1->0->-1/-1/-1 [14] -1/-1/-1->0->-1|-1->0->-1/-1/-1 [15] -1/-1/-1->0->-1|-1->0->-1/-1/-1 [16] -1/-1/-1->0->-1|-1->0->-1/-1/-1 [17] -1/-1/-1->0->-1|-1->0->-1/-1/-1 [18] -1/-1/-1->0->-1|-1->0->-1/-1/-1 [19] -1/-1/-1->0->-1|-1->0->-1/-1/-1 [20] -1/-1/-1->0->-1|-1->0->-1/-1/-1 [21] -1/-1/-1->0->-1|-1->0->-1/-1/-1 [22] -1/-1/-1->0->-1|-1->0->-1/-1/-1 [23] -1/-1/-1->0->-1|-1->0->-1/-1/-1 [24] -1/-1/-1->0->-1|-1->0->-1/-1/-1 [25] -1/-1/-1->0->-1|-1->0->-1/-1/-1 [26] -1/-1/-1->0->-1|-1->0->-1/
drawbar:20780:20805 [0] NCCL INFO 32 coll channels, 32 p2p channels, 32 p2p channels per peer
drawbar:20780:20805 [0] NCCL INFO comm 0x7f2998001060 rank 0 nranks 1 cudaDev 0 busId 1000 - Init COMPLETE
01/31/2021 23:07:49 - WARNING - __main__ -   Process rank: 0, device: cuda:0, n_gpu: 1distributed training: True, 16-bits training: False
```

**Comment by TevenLeScao** [comment]
Re-installed CUDA, and it's working now, closing this, sorry for the unrelated issue!
