### ISSUE TITLE
NCCL issues on single node

### ISSUE THREAD

**Issue by collinarnett** [microsoft/DeepSpeed#736]
Hello, I'm trying to use DeepSpeed on a VastAI instance with 2x 3090 but I'm getting the following error with NCCL:
```
2021-02-08 22:59:17,860] [WARNING] [runner.py:117:fetch_hostfile] Unable to find hostfile, will proceed with training with local resources only.
[2021-02-08 22:59:17,910] [INFO] [runner.py:355:main] cmd = /opt/conda/bin/python -u -m deepspeed.launcher.launch --world_info=eyJsb2NhbGhvc3QiOiBbMCwgMV19 --master_addr=127.0.0.1 --master_port=29500 ./trainer.py
[2021-02-08 22:59:18,790] [INFO] [launch.py:71:main] 0 NCCL_IB_DISABLE 1
[2021-02-08 22:59:18,790] [INFO] [launch.py:71:main] 0 NCCL_DEBUG info
[2021-02-08 22:59:18,790] [INFO] [launch.py:71:main] 0 NCCL_SOCKET_IFNAME lo
[2021-02-08 22:59:18,790] [INFO] [launch.py:78:main] WORLD INFO DICT: {'localhost': [0, 1]}
[2021-02-08 22:59:18,790] [INFO] [launch.py:87:main] nnodes=1, num_local_procs=2, node_rank=0
[2021-02-08 22:59:18,790] [INFO] [launch.py:99:main] global_rank_mapping=defaultdict(<class 'list'>, {'localhost': [0, 1]})
[2021-02-08 22:59:18,790] [INFO] [launch.py:100:main] dist_world_size=2
[2021-02-08 22:59:18,790] [INFO] [launch.py:103:main] Setting CUDA_VISIBLE_DEVICES=0,1
Special tokens have been added in the vocabulary, make sure the associated word embedding are fine-tuned or trained.
Special tokens have been added in the vocabulary, make sure the associated word embedding are fine-tuned or trained.
Loading cached split indices for dataset at tokenized_stories/cache-c445c6e9b0614129.arrow and tokenized_stories/cache-046b4417a885620e.arrow
Loading cached split indices for dataset at tokenized_stories/cache-c445c6e9b0614129.arrow and tokenized_stories/cache-046b4417a885620e.arrow
[2021-02-08 23:00:50,288] [INFO] [logging.py:60:log_dist] [Rank -1] DeepSpeed info: version=0.3.10, git-hash=unknown, git-branch=unknown
[2021-02-08 23:00:50,288] [INFO] [distributed.py:40:init_distributed] Initializing torch distributed with backend: nccl
[2021-02-08 23:00:50,701] [INFO] [logging.py:60:log_dist] [Rank -1] DeepSpeed info: version=0.3.10, git-hash=unknown, git-branch=unknown
[2021-02-08 23:00:50,701] [INFO] [distributed.py:40:init_distributed] Initializing torch distributed with backend: nccl
5525f7acde8f:5585:5585 [0] NCCL INFO Bootstrap : Using [0]lo:127.0.0.1<0>
5525f7acde8f:5585:5585 [0] NCCL INFO NET/Plugin : No plugin found (libnccl-net.so), using internal implementation
5525f7acde8f:5585:5585 [0] NCCL INFO NCCL_IB_DISABLE set by environment to 1.
5525f7acde8f:5585:5585 [0] NCCL INFO NET/Socket : Using [0]lo:127.0.0.1<0>
5525f7acde8f:5585:5585 [0] NCCL INFO Using network Socket
NCCL version 2.7.8+cuda11.0
5525f7acde8f:5586:5586 [1] NCCL INFO Bootstrap : Using [0]lo:127.0.0.1<0>
5525f7acde8f:5586:5586 [1] NCCL INFO NET/Plugin : No plugin found (libnccl-net.so), using internal implementation
5525f7acde8f:5586:5586 [1] NCCL INFO NCCL_IB_DISABLE set by environment to 1.
5525f7acde8f:5586:5586 [1] NCCL INFO NET/Socket : Using [0]lo:127.0.0.1<0>
5525f7acde8f:5586:5586 [1] NCCL INFO Using network Socket
5525f7acde8f:5585:5638 [0] NCCL INFO Channel 00/02 :    0   1
5525f7acde8f:5585:5638 [0] NCCL INFO Channel 01/02 :    0   1
5525f7acde8f:5585:5638 [0] NCCL INFO threadThresholds 8/8/64 | 16/8/64 | 8/8/64
5525f7acde8f:5585:5638 [0] NCCL INFO Trees [0] 1/-1/-1->0->-1|-1->0->1/-1/-1 [1] 1/-1/-1->0->-1|-1->0->1/-1/-1
5525f7acde8f:5585:5638 [0] NCCL INFO Setting affinity for GPU 0 to 0f,ffffffff
5525f7acde8f:5586:5640 [1] NCCL INFO threadThresholds 8/8/64 | 16/8/64 | 8/8/64
5525f7acde8f:5586:5640 [1] NCCL INFO Trees [0] -1/-1/-1->1->0|0->1->-1/-1/-1 [1] -1/-1/-1->1->0|0->1->-1/-1/-1
5525f7acde8f:5586:5640 [1] NCCL INFO Setting affinity for GPU 1 to 0f,ffffffff
5525f7acde8f:5586:5640 [1] NCCL INFO Could not enable P2P between dev 1(=1a000) and dev 0(=19000)
5525f7acde8f:5585:5638 [0] NCCL INFO Could not enable P2P between dev 0(=19000) and dev 1(=1a000)
5525f7acde8f:5586:5640 [1] NCCL INFO Could not enable P2P between dev 1(=1a000) and dev 0(=19000)
5525f7acde8f:5585:5638 [0] NCCL INFO Could not enable P2P between dev 0(=19000) and dev 1(=1a000)
5525f7acde8f:5586:5640 [1] NCCL INFO Channel 00 : 1[1a000] -> 0[19000] via direct shared memory
5525f7acde8f:5585:5638 [0] NCCL INFO Channel 00 : 0[19000] -> 1[1a000] via direct shared memory
5525f7acde8f:5585:5638 [0] NCCL INFO Could not enable P2P between dev 0(=19000) and dev 1(=1a000)
5525f7acde8f:5586:5640 [1] NCCL INFO Could not enable P2P between dev 1(=1a000) and dev 0(=19000)
5525f7acde8f:5585:5638 [0] NCCL INFO Could not enable P2P between dev 0(=19000) and dev 1(=1a000)
5525f7acde8f:5585:5638 [0] NCCL INFO Channel 01 : 0[19000] -> 1[1a000] via direct shared memory
5525f7acde8f:5586:5640 [1] NCCL INFO Could not enable P2P between dev 1(=1a000) and dev 0(=19000)
5525f7acde8f:5586:5640 [1] NCCL INFO Channel 01 : 1[1a000] -> 0[19000] via direct shared memory
5525f7acde8f:5585:5638 [0] NCCL INFO 2 coll channels, 2 p2p channels, 2 p2p channels per peer
5525f7acde8f:5585:5638 [0] NCCL INFO comm 0x7f8234001060 rank 0 nranks 2 cudaDev 0 busId 19000 - Init COMPLETE
5525f7acde8f:5585:5585 [0] NCCL INFO Launch mode Parallel
5525f7acde8f:5586:5640 [1] NCCL INFO 2 coll channels, 2 p2p channels, 2 p2p channels per peer
5525f7acde8f:5586:5640 [1] NCCL INFO comm 0x7f7688001060 rank 1 nranks 2 cudaDev 1 busId 1a000 - Init COMPLETE
[2021-02-08 23:00:53,589] [INFO] [engine.py:72:_initialize_parameter_parallel_groups] data_parallel_size: 2, parameter_parallel_size: 2
[2021-02-08 23:00:53,592] [INFO] [engine.py:72:_initialize_parameter_parallel_groups] data_parallel_size: 2, parameter_parallel_size: 2

5525f7acde8f:5586:5647 [0] init.cc:573 NCCL WARN Duplicate GPU detected : rank 1 and rank 0 both on CUDA device 19000

5525f7acde8f:5585:5646 [0] init.cc:573 NCCL WARN Duplicate GPU detected : rank 0 and rank 1 both on CUDA device 19000
5525f7acde8f:5586:5647 [0] NCCL INFO init.cc:840 -> 5
5525f7acde8f:5585:5646 [0] NCCL INFO init.cc:840 -> 5
5525f7acde8f:5586:5647 [0] NCCL INFO group.cc:73 -> 5 [Async thread]
5525f7acde8f:5585:5646 [0] NCCL INFO group.cc:73 -> 5 [Async thread]
Traceback (most recent call last):
  File "./trainer.py", line 33, in <module>
Traceback (most recent call last):
  File "./trainer.py", line 33, in <module>
    trainer.train()
  File "/opt/conda/lib/python3.7/site-packages/transformers/trainer.py", line 725, in train
    trainer.train()
  File "/opt/conda/lib/python3.7/site-packages/transformers/trainer.py", line 725, in train
    model, optimizer, lr_scheduler = init_deepspeed(self, num_training_steps=max_steps)
  File "/opt/conda/lib/python3.7/site-packages/transformers/integrations.py", line 384, in init_deepspeed
    model, optimizer, lr_scheduler = init_deepspeed(self, num_training_steps=max_steps)
  File "/opt/conda/lib/python3.7/site-packages/transformers/integrations.py", line 384, in init_deepspeed
    config_params=config,
  File "/opt/conda/lib/python3.7/site-packages/deepspeed/__init__.py", line 119, in initialize
    config_params=config_params)
  File "/opt/conda/lib/python3.7/site-packages/deepspeed/runtime/engine.py", line 150, in __init__
    config_params=config,
  File "/opt/conda/lib/python3.7/site-packages/deepspeed/__init__.py", line 119, in initialize
    self._configure_distributed_model(model)
  File "/opt/conda/lib/python3.7/site-packages/deepspeed/runtime/engine.py", line 504, in _configure_distributed_model
    config_params=config_params)
  File "/opt/conda/lib/python3.7/site-packages/deepspeed/runtime/engine.py", line 150, in __init__
    self._broadcast_model()
  File "/opt/conda/lib/python3.7/site-packages/deepspeed/runtime/engine.py", line 482, in _broadcast_model
    self._configure_distributed_model(model)
  File "/opt/conda/lib/python3.7/site-packages/deepspeed/runtime/engine.py", line 504, in _configure_distributed_model
    group=self.data_parallel_group)
  File "/opt/conda/lib/python3.7/site-packages/torch/distributed/distributed_c10d.py", line 864, in broadcast
    self._broadcast_model()
  File "/opt/conda/lib/python3.7/site-packages/deepspeed/runtime/engine.py", line 482, in _broadcast_model
    work = group.broadcast([tensor], opts)
RuntimeError: NCCL error in: /opt/conda/conda-bld/pytorch_1607370156314/work/torch/lib/c10d/ProcessGroupNCCL.cpp:784, invalid usage, NCCL version 2.7.8
    group=self.data_parallel_group)
  File "/opt/conda/lib/python3.7/site-packages/torch/distributed/distributed_c10d.py", line 864, in broadcast
    work = group.broadcast([tensor], opts)
RuntimeError: NCCL error in: /opt/conda/conda-bld/pytorch_1607370156314/work/torch/lib/c10d/ProcessGroupNCCL.cpp:784, invalid usage, NCCL version 2.7.8
```
Here is the output of my `ds_report`
```
--------------------------------------------------
DeepSpeed C++/CUDA extension op report
--------------------------------------------------
NOTE: Ops not installed will be just-in-time (JIT) compiled at
      runtime if needed. Op compatibility means that your system
      meet the required dependencies to JIT install the op.
--------------------------------------------------
JIT compiled ops requires ninja
ninja .................. [OKAY]
--------------------------------------------------
op name ................ installed .. compatible
--------------------------------------------------
cpu_adam ............... [NO] ....... [OKAY]
fused_adam ............. [NO] ....... [OKAY]
fused_lamb ............. [NO] ....... [OKAY]
 [WARNING]  sparse_attn requires one of the following commands '['llvm-config', 'llvm-config-9']', but it does not exist!
 [WARNING]  sparse_attn requires the 'cmake' command, but it does not exist!
 [WARNING]  sparse_attn requires CUDA version 10.1+, does not currently support >=11 or <10.1
sparse_attn ............ [NO] ....... [NO]
transformer ............ [NO] ....... [OKAY]
stochastic_transformer . [NO] ....... [OKAY]
utils .................. [NO] ....... [OKAY]
--------------------------------------------------
DeepSpeed general environment info:
torch install path ............... ['/opt/conda/lib/python3.7/site-packages/torch']
torch version .................... 1.7.1
torch cuda version ............... 11.0
nvcc version ..................... 11.0
deepspeed install path ........... ['/opt/conda/lib/python3.7/site-packages/deepspeed']
deepspeed info ................... 0.3.10, unknown, unknown
deepspeed wheel compiled w. ...... torch 1.7, cuda 11.0

```

**Comment by SeanNaren** [comment]
Hey!  I also ran into this and was able to fix this by installing the pytorch nightly builds. There is also a pre-release for 1.8 which might also work:

```
# install nightly
conda install pytorch torchvision torchaudio -c pytorch-nightly

# to install 1.8 pre-release
conda install -y -c pytorch-test -c conda-forge pytorch
```

**Comment by collinarnett** [comment]
Ok so for anyone reading this I managed to get it working.

I am using HuggingFace's interface for DeepSpeed so there were multiple things I needed to do. 

I installed the pre-release as suggested by @SeanNaren and installed DS from source AND installed the cuda 11.1 toolkit. So my DS report looks like the following:
```
 --------------------------------------------------
DeepSpeed C++/CUDA extension op report
--------------------------------------------------
NOTE: Ops not installed will be just-in-time (JIT) compiled at
      runtime if needed. Op compatibility means that your system
      meet the required dependencies to JIT install the op.
--------------------------------------------------
JIT compiled ops requires ninja
ninja .................. [OKAY]
--------------------------------------------------
op name ................ installed .. compatible
--------------------------------------------------
cpu_adam ............... [NO] ....... [OKAY]
fused_adam ............. [NO] ....... [OKAY]
fused_lamb ............. [NO] ....... [OKAY]
 [WARNING]  sparse_attn requires one of the following commands '['llvm-config', 'llvm-config-9']', but it does not exist!
 [WARNING]  sparse_attn requires the 'cmake' command, but it does not exist!
 [WARNING]  sparse_attn requires CUDA version 10.1+, does not currently support >=11 or <10.1
sparse_attn ............ [NO] ....... [NO]
transformer ............ [NO] ....... [OKAY]
stochastic_transformer . [NO] ....... [OKAY]
utils .................. [NO] ....... [OKAY]
--------------------------------------------------
DeepSpeed general environment info:
torch install path ............... ['/opt/conda/envs/deepspeed1/lib/python3.8/site-packages/torch']
torch version .................... 1.7.1
torch cuda version ............... 11.0
nvcc version ..................... 11.1
deepspeed install path ........... ['/opt/conda/envs/deepspeed1/lib/python3.8/site-packages/deepspeed']
deepspeed info ................... 0.3.11+6ee3b29, 6ee3b29, master
deepspeed wheel compiled w. ...... torch 1.7, cuda 11.0
```
I also compiled the latest `transformers` library from their master branch commit 77b86284 and had to manually change `local_rank` to 1
